import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return m[2].includes('↓')&&!m[2].includes('├')?flow(m[2].trim().split(/\n?↓\n?/).map(x=>x.trim())):code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||''};});
if(originals.length!==156||originals.some((s,i)=>+s.id!==450+i))throw Error('Нарушен порядок 450–605');
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${inline(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const architecture=()=>flow(['Instagram → ManyChat','UTM → Vercel'])+cards([['Аналитическая ветка','GA4 → Reports → Explore → наблюдения и гипотезы.'],['Операционная ветка','Форма → Apps Script → leads → очистка в Google Таблицах из темы 8.']]);
const extra=(id,title,steps,shot,check)=>({id,title,body:bullets(steps)+(check?result(check):''),shot});
const extras={
456:[extra('456a','Подготовьте данные и рабочий отчёт',['Откройте ресурс сайта из тем 6–9. Убедитесь, что события page_view, cta_click, form_start и generate_lead действительно собираются.','Выберите завершённый период, содержащий тесты Instagram и backend_guide. Свежим событиям нужно время для обработки.','Скачайте analysis-template.md из материалов. Запишите ресурс, период, часовой пояс и дату проверки.'],'GA4: выбранный ресурс, период и существующие события; рядом заполненная шапка отчёта.','Если данных мало, настройте исследование и честно зафиксируйте ограничение. Числа примеров не переносим в реальные результаты.')],
457:[extra('457a','Если нужного отчёта нет в меню',['Коллекции GA4 могут называться Life cycle или Business objectives. Найдите отчёт по названию, а не только по положению в меню.','Editor / Administrator: Reports → Library → найдите нужный отчёт. Его можно открыть и добавить в коллекцию.','Если прав нет, попросите владельца ресурса открыть отчёт; настройку Library разбираем в конце темы.'],'Reports: структура коллекций и доступный Traffic acquisition либо его карточка в Library.')],
461:[extra('461a','Включите сравнение дат',['Откройте Date range → Compare → Previous period.','Проверьте одинаковую длительность интервалов; исключите незавершённый день. Apply.','Сохраните обе даты в отчёт. Процент изменения вычисляйте относительно предыдущего периода.'],'Date range: основной и предыдущий период; сравнение включено.','Для 4 → 10: (10 − 4) / 4 = 150%. При исходном нуле процент роста не определён.')],
471:[extra('471a','Если instagram / social не появился',['Сверьте ресурс, период и точные значения UTM. Новая UTM не запускает новый сеанс автоматически.','Проверьте ссылку из темы 9 и метки на странице формы. В GA4 не подменяйте Session source полем First user source.','Проверьте задержку обработки, фильтры и качество данных. Пустая строка отчёта не доказывает отсутствие переходов.'],'Traffic acquisition: период, Session source / medium, состояние фильтров и фактический результат.')],
485:[extra('485a','Откройте Pages and screens',['Reports → Engagement → Pages and screens, либо найдите этот отчёт в текущей коллекции.','Выберите Page path and screen class. Найдите /guide.html и /contacts.html.','Сравните Views и Active users. Одна страница может быть открыта пользователем несколько раз.'],'Pages and screens: пути guide.html и contacts.html с Views и Active users.')],
489:[extra('489a','Проверьте generate_lead как Key event',['Admin → Data display → Events. Найдите generate_lead и проверьте отметку ключевого события.','Если её ещё нет и у вас есть нужные права, включите отметку. Запишите дату изменения: прошлые события не превращаются в key events задним числом.','В отчёте с селектором Key events выберите generate_lead вместо All events.'],'Events в Admin: generate_lead отмечен как Key event; отдельно селектор generate_lead в отчёте.')],
490:[extra('490a','Доля сеансов с результатом',['В Traffic acquisition найдите Session key event rate и выберите generate_lead, если доступен селектор.','Числитель: сеансы хотя бы с одним выбранным ключевым событием. Знаменатель: все сеансы выбранной группы.','Key events / Sessions — количество событий на сеанс. При повторных отправках оно не равно доле сеансов с результатом.'],'Traffic acquisition: Sessions, Key events и Session key event rate для generate_lead.')],
491:[extra('491a','Посмотрите технические характеристики',['Reports → User → Tech → Tech details, либо найдите Tech details в своей коллекции.','Выберите Device category; сравните mobile, desktop, tablet.','Добавьте сравнение Instagram и проверьте объём каждой группы перед выводами.'],'Tech details: Device category и показатели поведения для Instagram.')],
505:[extra('505a','Назовите исследование и задайте период',['В Variables измените название на «ОП03 · Instagram · анализ воронки».','Задайте те же даты, что в Reports. Период Explore проверяется отдельно.','Посмотрите доступный диапазон: детализация ограничена сроком хранения данных. Расширение срока не вернёт уже удалённые данные.'],'Explore: имя исследования и раскрытый календарь Variables с выбранными датами.')],
514:[extra('514a','Отделите все Key events от generate_lead',['На первой вкладке оставьте Sessions и Key events без фильтра Event name: здесь Key events — сумма отмеченных событий.','Создайте отдельную вкладку Free form «Lead events»: Rows → Session source; Values → Event count; Filter → Event name exactly matches generate_lead.','Не называйте Sessions на отфильтрованной по событию вкладке всеми входящими сеансами. Сравнивайте с исходной таблицей трафика.'],'Две вкладки: Sources без Event name-фильтра и Lead events с generate_lead и Event count.')],
518:[extra('518a','Проверьте метку конкретного Reel',['Variables → Dimensions + → найдите Session manual ad content → Import.','В Rows после Session source и Session campaign добавьте Session manual ad content.','Ожидайте reel01 только при наличии таких переходов. (not set) записывайте как отсутствие значения, а не как отдельный Reel.'],'Free form: source, campaign, Session manual ad content; фактические reel01 или (not set).')],
527:[extra('527a','Уберите фильтр, который исключает Direct',['В Settings → Filters удалите условие Session source = instagram, добавленное на слайде 522.','В Segment comparisons оставьте Instagram Sessions и Direct Sessions.','Проверьте, что оба сегмента применены к одной вкладке и сравниваются за одинаковый период.'],'Free form: два сегмента и отсутствие общего Instagram-фильтра.','Если Direct пуст, сначала исключите конфликт фильтра и сегмента, затем проверяйте данные.')],
530:[extra('530a','Определите рамки воронки',['Используем четыре шага: session_start → cta_click → form_start → generate_lead. page_view остаётся в диагностике, отдельным шагом этой воронки не будет.','Для базового маршрута выключите Make open funnel. Воронка считает пользователей, а не количество событий.','Не считайте её автоматически воронкой одного сеанса: пользовательская последовательность может пересекать сеансы. Зафиксируйте выбранные ограничения.'],'Funnel: Make open funnel выключен, заголовок вкладки и период.')],
535:[extra('535a','Примените все четыре шага',['В редакторе Steps проверьте Event name и точное имя каждого события.','Между шагами выберите is indirectly followed by, чтобы page_view и другие события не разрывали маршрут.','Для первого расчёта не ставьте Within. Нажмите Apply.'],'Edit funnel steps: четыре условия, косвенные переходы и Apply.','Если пользователей нет, проверяйте шаги по одному; подпись шага не заменяет условие.')],
541:[extra('541a','Сравните закрытую и открытую воронку',['Сохраните кадр закрытой воронки с теми же датами и условиями.','Включите Make open funnel, снимите результат и отметьте возможные входы на более поздних шагах.','Для основного кейса верните закрытую воронку. Не сравнивайте её проценты с открытой без пояснения.'],'Одинаковая воронка до и после Make open funnel; виден переключатель.')],
544:[extra('544a','Проверьте ограничение времени',['Steps → Edit. Для перехода CTA Click → Form Start включите Within и задайте 10 minutes.','Apply → сравните число дошедших с исходной воронкой. Меньший результат означает более строгое условие.','Запишите опыт отдельно и снимите Within для дальнейшего базового анализа.'],'Условие Within 10 minutes на переходе CTA → Form Start и результат после Apply.')],
548:[extra('548a','Если тип сегмента недоступен в технике',['Проверьте, разрешает ли эта техника применить Instagram Sessions и Direct Sessions. Нельзя незаметно заменить тип сегмента.','Для пользовательского сравнения создайте User segment «Users with Instagram sessions» с Session source exactly matches instagram; второй — с (direct).','Такие группы могут пересекаться и включать другие действия этих пользователей. Для основного кейса используйте фильтры вкладки по Session source и Session campaign.'],'Редактор пользовательского сегмента и его применение к Funnel; видны имя и область группы.')],
553:[extra('553a','Начните Path с пустой схемы',['На новой вкладке Path нажмите Start over.','Выберите Starting point → Event name → session_start.','Проверьте выбранную метрику: Event count считает события, Total users — пользователей. Запишите её в отчёт.'],'Path после Start over: Starting point и выбранная метрика.')],
558:[extra('558a','Переключите узлы на страницы',['Чтобы увидеть /about.html или /contacts.html, откройте Node type над нужным столбцом.','Выберите Page path and screen class, если доступно. При необходимости импортируйте это измерение в Variables.','Сравните фактические страницы после CTA. Отсутствие следующего узла не является отдельным событием exit.'],'Path: выбран Page path and screen class, видны реальные пути страниц.')],
559:[extra('559a','Постройте обратный путь',['Создайте отдельную вкладку Path «Before lead», чтобы сохранить прямой путь. Нажмите Start over.','Выберите Ending point → Event name → generate_lead.','Нажмите узел предыдущего шага, чтобы раскрыть ещё один уровень влево. Сохраните период и фильтры.'],'Path Before lead: Ending point generate_lead и два раскрытых уровня назад.')],
570:[extra('570a','Проверьте доступность данных Explore',['Admin → Data collection and modification → Data retention: посмотрите срок хранения детальных данных.','В Explore нажмите индикатор качества и запишите сообщение, а не только цвет значка.','Если данные не видны, проверьте период, фильтры, совместимость полей и завершение обработки. Не заменяйте пропуски нулями.'],'Data retention и открытая подсказка качества данных Explore; без изменения настроек ресурса.')],
575:[extra('575a','Создайте условие Custom Insight',['Home → Insights → View all insights → Create → Create new. Нужны Editor / Administrator.','Выберите Daily, группу All users, доступную метрику пользователей и условие % decrease more than 50. Сверьте сравниваемые периоды в форме.','Задайте имя «Падение пользователей». Для упражнения оставьте email-получателей пустыми; Create.'],'Форма Custom Insight: частота, метрика, условие, значение, имя и пустой список email.'),extra('575b','Убедитесь, что правило сохранено',['View all insights → Manage: найдите созданное правило и откройте его параметры.','Сохранённое правило ещё не означает обнаруженную аномалию. Оно появится как insight при выполнении условия.','Если прав нет, сохраните спецификацию правила в отчёте и отметьте, что оно не создано.'],'Manage insights: сохранённое правило либо честно зафиксированное ограничение прав.')],
580:[extra('580a','Создайте повторяемый отчёт',['Reports → Library → Create new report → Create detail report → Blank.','Добавьте Session campaign, Session source / medium; метрики Sessions, Engagement rate, Key events.','Назовите «Кампании · трафик и события» → Save. Отчёт появится в Library.'],'Редактор detail report: измерения, метрики и сохранённое имя.'),extra('580b','Добавьте отчёт в навигацию',['В Library создайте отдельную коллекцию: Create new collection → Blank. Назовите её «Практика ОП03».','Create new topic → «Кампании» → Apply. Перетащите новый detail report в эту тему; Save.','На карточке коллекции откройте меню → Publish. Проверьте появление в Reports. Для Viewer сохраните только спецификацию.'],'Library: отчёт внутри темы новой коллекции; Published и пункт Reports.')],
581:[extra('581a','Проверьте скачанный файл',['На нужной вкладке Explore нажмите Export data → CSV или доступный формат Google Sheets.','Откройте результат. Сверьте заголовки, строки и итог с активной вкладкой.','Сохраните файл вместе с периодом, фильтрами и метрикой в analysis-template.md. Экспорт не объединяет автоматически все источники курса.'],'Export data и открытый выгруженный файл с заголовками и фактическими значениями.')],
586:[extra('586a','Зафиксируйте единые условия кейса',['Период и часовой пояс одинаковы во всех результатах. Source = instagram; campaign = backend_guide.','В Reports используйте comparison с двумя условиями. В Explore добавьте оба фильтра на каждую нужную вкладку: они не обязаны переноситься сами.','Для Funnel и Path не задавайте Event name = generate_lead как общий фильтр: это удалит предыдущие события маршрута.'],'Настройки сравнения/фильтров: Session source instagram AND Session campaign backend_guide.')],
594:[extra('594a','Сверьте события с сохранёнными заявками',['В leads Google Таблиц отберите тот же период и source/campaign. Считайте уникальные непустые request_id.','Сравните с generate_lead только как отдельный контроль: повторные отправки, блокировщики и ошибки сохранения дают расхождения.','Запишите фактическое число строк, уникальных заявок и возможные причины различий.'],'Sheets: отбор периода и кампании, уникальные request_id и итог без чужих персональных данных.')],
597:[extra('597a','Сохраните вывод и план проверки',['Заполните шаблон: наблюдение с числителем и знаменателем; ограничение; гипотеза; одно изменение; метрика проверки.','Не меняйте одновременно DM, страницу и форму, если хотите понять эффект конкретного изменения.','Приложите экспорты и кадры. При малом объёме данных вывод — «данных недостаточно», затем план следующего наблюдения.'],'Заполненный итоговый отчёт: наблюдение, гипотеза, проверка и ограничения.')]
};
const custom={
450:architecture()+`<p class="lead">Раньше проверяли поступление данных. Теперь сравниваем группы, исследуем путь и формулируем гипотезы.</p>`+note('GA4 видит события сайта. Комментарии Instagram и сообщения ManyChat не становятся событиями GA4 автоматически.'),
452:cards([['Realtime','Проверить свежую активность.'],['Reports','Получить регулярные показатели.'],['Comparisons','Сопоставить группы в отчёте.'],['Explore','Настроить таблицу, воронку или пути.'],['Attribution','Разобрать вклад источников.'],['Insights и Custom Reports','Замечать изменения и сохранять повторяемый анализ.']]),
455:cards([['Reports','Сравнить трафик, страницы и события по готовым разрезам.'],['Explore','Задать маршрут, группы и условия исследования.']])+note('Исследование показывает связи и последовательности. Причину поведения нужно проверять отдельно.'),
456:cards([['01 / Reports','Период, Acquisition, страницы, события, устройства.'],['02 / Сравнение','Comparisons и экспорт.'],['03 / Free form','Поля, таблицы, фильтры и сегменты.'],['04 / Funnel','Шаги, переходы, потери и разбивка.'],['05 / Path','Прямой и обратный маршрут.'],['06 / Результат','Attribution, Insights, Custom Reports и итоговый кейс.']]),
461:cards([['Предыдущий период','4 события generate_lead.'],['Текущий период','10 событий generate_lead.'],['Изменение','+6 событий; рост на 150%.']])+note('Сначала уточняем единицу: здесь события отправки, а не подтверждённые уникальные заявки.'),
463:table(['Session source','Sessions'],[['instagram','40'],['(direct)','31'],['google','12']])+note('Условные числа для разбора: измерение группирует строки, метрика считает сеансы.'),
467:flow(['Один пользователь','Визит из Instagram','Позднее возвращение','Ещё один сеанс'])+note('Traffic acquisition использует источник сеанса. Прямое возвращение не обязано отображаться как (direct): действуют правила атрибуции. Новая UTM во время сеанса сама его не перезапускает.'),
469:click(['Reports','Acquisition','Traffic acquisition'])+result('Найдите таблицу каналов. При другой коллекции ориентируйтесь на название Traffic acquisition.'),
472:table(['Источник','Sessions','generate_lead · события'],[['instagram','100','5'],['(direct)','40','8']])+note('Условный пример. Пока можно сравнить объём событий; доля сеансов с заявкой требует другой метрики.'),
473:code('Engagement rate = Engaged sessions / Sessions × 100%','ДОЛЯ ВОВЛЕЧЁННЫХ СЕАНСОВ')+bullets(['Вовлечённый сеанс соответствует хотя бы одному критерию: длительность выше порога, ключевое событие или не менее двух просмотров страниц/экранов.','Порог длительности по умолчанию — 10 секунд; проверьте настройки потока.'])+result('Смотрите Sessions и Engagement rate рядом: высокая доля на трёх сеансах ещё не устойчивый результат.'),
476:table(['Session source / medium','Session campaign','Sessions'],[['instagram / social','backend_guide','52'],['instagram / social','frontend_guide','31'],['instagram / social','analytics_guide','19']])+note('Условный пример нескольких кампаний. На вашем ресурсе может быть только backend_guide.'),
480:cards([['Landing page','Первая просмотренная страница сеанса.'],['Наш маршрут','В теме 9 материал расположен на /guide.html; после CTA открывается /contacts.html.']])+note('Если ссылка из DM ведёт прямо на contacts.html, начальной страницей станет форма. Это другой маршрут.'),
481:click(['Reports','Engagement','Landing page'])+result('Если отчёта нет в текущей коллекции, используйте поиск по названию или Library с соответствующими правами.'),
482:bullets(['Найдите /guide.html, /contacts.html и /.','Сравните Sessions, Active users и доступные ключевые события за выбранный период.','Зафиксируйте реальную начальную страницу, даже если она отличается от плана.']),
483:click(['Landing page','+ рядом с измерением','Session source / medium'])+result('Для кампании backend_guide ожидаемый вход — /guide.html. Проверяйте фактические строки, а не заранее заданный ответ.'),
486:click(['Reports','Engagement','Events'])+code('page_view · scroll · click\nform_start · form_submit\ncta_click · generate_lead','ПРОВЕРЯЕМ НАЛИЧИЕ')+note('Enhanced measurement должен быть настроен. click обычно означает исходящую ссылку, а не любое нажатие; cta_click отправляет наш код. Отсутствующее событие сначала проверяем в сборе данных.'),
487:table(['Event name','Event count'],[['page_view','450'],['cta_click','81'],['form_start','32'],['generate_lead','18']])+note('Условный пример частот. Эта таблица не доказывает, что одни и те же пользователи прошли события по порядку.'),
490:table(['Источник','Sessions','generate_lead · события'],[['instagram','100','8'],['(direct)','50','7']])+note('8/100 и 7/50 — события на сеанс. Для доли успешных сеансов используем Session key event rate выбранного события.'),
492:cards([['Наблюдение в примере','90% Instagram-трафика приходится на mobile; доля сеансов с generate_lead ниже, чем на desktop.'],['Что проверить','Размер групп, одинаковый период, исправность событий и работу формы на телефоне.']])+note('Техническая проблема — гипотеза. График сам по себе не доказывает её причину.'),
495:click(['Add comparison','Create new','Session source','Exactly matches','instagram','Apply'])+result('Над отчётом появилась группа Instagram. Не выбирайте First user source для этого сравнения.'),
496:click(['Add comparison','Session source','Exactly matches','(direct)','Apply'])+result('Instagram и Direct видны одновременно. При необходимости уберите All users, чтобы оставить две группы.'),
499:click(['Отчёт','Share this report','Download file / Export'])+bullets(['Выберите доступный CSV, PDF или Google Sheets.','Проверьте период и сравнения до выгрузки.','Название файла и настройки сохраните в отчёте. Набор форматов зависит от поверхности GA4.']),
502:flow(['session_start','page_view','cta_click','form_start','generate_lead'])+note('Это возможная подробная модель. В основной практике зададим четыре шага без отдельного page_view: он может происходить между ними.'),
508:click(['Variables','Dimensions +','Найти и отметить','Import'])+code('Session source\nSession campaign\nSession manual ad content\nEvent name\nLanding page\nDevice category\nPage path and screen class','ПОЛЯ ДЛЯ ПРАКТИКИ')+result('Импортируйте доступные поля. Если название отличается, сверьте его область действия и смысл.'),
509:click(['Variables','Metrics +','Найти и отметить','Import'])+code('Active users\nTotal users\nSessions\nEvent count\nKey events\nEngagement rate','МЕТРИКИ')+note('Total users пригодится для Path. Наличие метрики в Variables не означает, что любая техника разрешит её использовать.'),
514:click(['Variables','Key events','Settings → Values'])+result('Рядом с Sessions появилась сумма ключевых событий. Если отмечено несколько событий, это ещё не число generate_lead.'),
515:table(['Источник','Sessions','Key events','Событий на сеанс'],[['instagram','100','8','0,08'],['(direct)','50','7','0,14'],['google','45','3','0,067']])+note('Условные данные. Здесь Direct имеет больше событий на сеанс; вывод о доле пользователей или качестве заявок из этой таблицы не следует.'),
516:click(['Rows','Session source','Session campaign','Nested rows → Yes'])+result('Источник раскрывается до кампаний. Если вложенность не включена, разрезы отображаются отдельными колонками.'),
518:code('utm_content=reel01\n↓\nSession manual ad content = reel01','МЕТКА → ИЗМЕРЕНИЕ')+note('Системное измерение UTM не требует создания custom dimension. В Google Sheets темы 7–9 utm_content отдельно не сохранялся.'),
519:table(['URL','Измерение уровня сеанса','Значение'],[['utm_source','Session source','instagram'],['utm_campaign','Session campaign','backend_guide'],['utm_content','Session manual ad content','reel01']]),
520:click(['Settings','Visualization','Table / Bar chart / …'])+note('Для упражнения сравните таблицу и столбчатую диаграмму. Линейный график требует времени по оси; не переносите в него разрез источников без проверки настроек.'),
525:click(['Variables','Segments +','Create a custom segment','Session segment'])+code('Name: Instagram Sessions\nInclude sessions when:\nSession source exactly matches instagram','УСЛОВИЕ')+result('Save and apply: сегмент появился в Variables и применяется к вкладке. Если доступен отдельный Save, затем перетащите его в Segment comparisons.'),
526:click(['Segments +','Session segment'])+code('Name: Direct Sessions\nSession source exactly matches (direct)','ВТОРОЙ СЕГМЕНТ')+result('Сохраните сегмент и добавьте его в Segment comparisons той же вкладки.'),
529:flow(['session_start','cta_click','form_start','generate_lead'])+note('Изучаем пользователей, прошедших заданные шаги. Событие submit в нашем проекте ещё не подтверждает запись в Sheets.'),
532:code('Step name: Session started\nEvent name exactly matches session_start','ШАГ 1')+note('session_start — начало сеанса. Первый визит нового пользователя — first_visit; это другое событие.'),
535:code('Step name: Lead submit\nEvent name exactly matches generate_lead','ШАГ 4')+result('Финал этой воронки — событие отправки формы. Реальные сохранённые заявки сверяем отдельно.'),
536:table(['Шаг','Пользователи · условный пример'],[['Session started','100'],['CTA Click','48'],['Form Start','21'],['Lead submit','11']])+result('В своём ресурсе снимите фактическую воронку. Не заменяйте реальные значения числами примера.'),
537:`<div class="funnel-lab"><p>Введите число пользователей каждого шага закрытой воронки. Пример условный.</p><div class="lab-inputs">${[['Начали',100],['CTA',48],['Начали форму',21],['Отправили',11]].map(([label,n],i)=>`<label>${label}<input data-funnel="${i}" type="number" min="0" step="1" value="${n}" inputmode="numeric"></label>`).join('')}</div><div id="funnel-result" aria-live="polite"></div><button id="funnel-reset">Вернуть пример</button></div>`,
538:table(['Переход','Потеря пользователей','Доля потерь'],[['100 → 48','52','52%'],['48 → 21','27','56,25%'],['21 → 11','10','47,62%']])+note('В примере первая потеря больше по числу людей. Между CTA и формой — наибольшая доля потерь. В выводе укажите, какой критерий используете.'),
543:cards([['Directly followed by','Следующее событие должно сразу соответствовать следующему шагу.'],['Indirectly followed by','Между шагами допустимы другие события.']])+flow(['cta_click','page_view формы','form_start'])+result('В основной практике выбираем Indirectly: переход на страницу формы создаёт промежуточный page_view.'),
545:click(['Variables → Device category','Settings → Breakdown'])+result('В таблице появились группы устройств. При переходах между устройствами разбивка пользователя относится к первому подходящему значению.'),
546:table(['Устройство','Form Start → Lead submit · условный пример'],[['desktop','70%'],['mobile','25%']])+note('Запишите также число пользователей каждого устройства. Различие процентов на малых группах ещё не основание менять форму.'),
548:bullets(['Добавьте Instagram Sessions и Direct Sessions в Segment comparisons, если техника принимает этот тип сегмента.','Уберите общий Instagram-фильтр перед сравнением с Direct.','Если сегмент недоступен, следующий шаг показывает пользовательский вариант и объясняет изменение смысла группы.']),
549:`<p class="lead">В выбранной группе и периоде доля перехода от form_start к generate_lead выше у Direct.</p>`+note('Это образец формулировки, а не результат вашего ресурса. Подставьте фактические числа и тип сравниваемых групп.'),
553:click(['Explore','Новая вкладка +','Path exploration'])+result('Для прямого пути создаём отдельную вкладку. После неё будет отдельная вкладка обратного пути.'),
557:cards([['Ожидаемый путь','cta_click → form_start.'],['Возможный наблюдаемый путь','cta_click → page_view → scroll → page_view; дальше зарегистрированных действий нет.']])+note('exit не является автоматически собираемым событием GA4. Конец зарегистрированного пути не доказывает, что человек закрыл сайт.'),
558:flow(['CTA','Страница about.html','Нет наблюдаемого продолжения'])+note('Это гипотетический маршрут. Чтобы увидеть страницы, переключите Node type. Проверьте период и фильтры до вывода о прекращении действий.'),
560:flow(['cta_click','page_view','form_start','generate_lead'])+note('Условная последовательность. Обратный Path показывает зарегистрированные предшествующие действия и может охватывать несколько сеансов.'),
565:click(['Advertising','Key events','Key event attribution paths'])+note('Состав раздела зависит от ресурса и прав. Если отчёт недоступен, зафиксируйте ограничение; не подключайте рекламу только ради скриншота.'),
566:bullets(['Вверху отчёта оставьте generate_lead вместо всех ключевых событий.','Укажите тот же период; выберите Source, Medium или Campaign.','Снимите фактические пути. При недостатке данных сохраните пустое состояние с условиями.'])+note('Это касания, известные аналитике. Просмотр Reel и чтение DM не появляются в отчёте только из-за подключения ManyChat.'),
569:code('2 / 3 × 100% ≈ 66,7%','МАЛАЯ ГРУППА')+note('Один дополнительный пользователь резко изменит процент. Сначала показываем числитель и знаменатель, затем формулируем осторожное наблюдение.'),
573:click(['Home','Insights','View all insights'])+cards([['Automated','Система обнаруживает необычные изменения.'],['Custom','Условия задаёт пользователь с правами редактора.']])+note('На небольшом ресурсе автоматических insights может пока не быть. Это не ошибка настройки.'),
575:cards([['Частота','Daily — ежедневная проверка.'],['Условие','Снижение выбранной метрики пользователей более чем на 50%.'],['Результат','Сигнал для исследования, а не объяснение причины.']])+note('Следующие экраны показывают создание и проверку правила. Название метрики выбираем из доступных в интерфейсе.'),
583:cards([['GA4 · пример','20 событий generate_lead: могли быть повторные отправки или события без сохранения.'],['Sheets · отдельный пример','20 уникальных заявок: 12 new, 5 in_progress, 3 done.']])+note('Совпадение чисел в примере не гарантирует соответствие один к одному. Для сверки нужны период, фильтры и ключи; GA4 не заменяет CRM.'),
590:code('Rows: Session campaign\nValues: Sessions, Key events\nFilters:\n  Session source exactly matches instagram\n  Session campaign exactly matches backend_guide','ОСНОВНОЙ КЕЙС')+note('Получится выбранная кампания. Для сравнения всех Instagram-кампаний сделайте копию вкладки и снимите только campaign-фильтр. Key events включает все отмеченные события.'),
591:flow(['session_start','cta_click','form_start','generate_lead'])+result('Closed, Indirectly, без Within; source и campaign заданы. Запишите пользователей, абсолютные потери и процент каждого перехода.'),
593:click(['Новая вкладка Path','Start over','Starting point','Event name','cta_click'])+result('Перенесите условия основного кейса. Раскройте следующий узел; для названий страниц измените Node type.'),
595:cards([['Наблюдение','Между CTA и формой не продолжили X из N пользователей — Y%.'],['Разрез','На mobile: A из B; на desktop: C из D.'],['Ограничение','Период, объём групп, качество данных и выбранные условия воронки.']])+note('Не утверждайте, что потеря на mobile максимальна, если это не подтверждается вашими данными.'),
599:table(['Вопрос','Инструмент'],[['Событие пришло сейчас?','Realtime / DebugView'],['Источник и кампания сеанса?','Traffic acquisition'],['Начальная страница?','Landing page'],['Просмотренные страницы и действия?','Pages and screens / Events'],['Различия групп?','Comparison / Segment'],['Потеря на заданном маршруте?','Funnel'],['Действия до или после события?','Path'],['Вклад касаний в результат?','Attribution']]),
600:checklist(['Snapshot и период','Traffic acquisition: source, campaign и второй разрез','Landing page и Events с generate_lead','Instagram vs Direct','Explore, Variables и Free form','Сегменты и их условия','Funnel: шаги, переходы, тип, Breakdown','Path: прямой и обратный маршрут','Attribution и доступные Insights','Экспорт и итоговый отчёт'])+`<p><a href="materials.html">Полный список кадров и шаблон отчёта →</a></p>`,
601:cards([['Поля и единицы','Dimension / Metric; Users / Sessions / Event count; Key event и реальная заявка.'],['Источники','User acquisition / Traffic acquisition; source / campaign / content; атрибуция.'],['Группы','Comparison / Filter / Segment; область действия и пересечение групп.'],['Последовательности','Funnel / Path; Open / Closed; Direct / Indirect; Within и Breakdown.'],['Выводы','Наблюдение, гипотеза, малые выборки, качество данных и план проверки.']]),
603:architecture(),
604:cards([['GA4','Источники, кампании, сеансы и события.'],['Google Sheets · leads','request_id, данные заявки и статус.'],['Google Sheets · leads_clean','Подготовленный набор из темы 8.']])+result('Следующая тема собирает показатели разных источников в один dashboard. Объединение по пользователям само собой не произойдёт.')
};
const hints={453:'Realtime — диагностика. Поле First user source не равно источнику текущего сеанса.',471:'Ожидание относится к корректно атрибутированному сеансу. Свежее событие может появиться в стандартном отчёте позже.',475:'После выбора второго измерения проверьте две колонки заголовков. Условие кампании добавляйте отдельно, если нужен только backend_guide.',487:'Event count не подтверждает ни порядок, ни принадлежность событий одним пользователям.',489:'В проекте generate_lead отправляется при submit. Статус Key event не меняет механизм отправки.',522:'Этот фильтр относится к текущей вкладке. Перед Instagram vs Direct его нужно удалить.',529:'Условия шага задаются явно; одинаковые подписи с разными условиями дают разные результаты.',547:'Если за период есть только backend_guide, сравнивать её с отсутствующими кампаниями нельзя.',550:'Меняйте один выбранный фактор, сохраняя определение метрики и сопоставимые периоды.',568:'Изменение модели в просмотре отчёта не требует менять общие Attribution settings ресурса.',571:'Сначала сверяем ресурс, период, часовой пояс, область измерений, метрики, фильтры и группы.',588:'Для кейса темы 9 ожидаемый вход — /guide.html. В отчёте фиксируем то, что произошло.',589:'Примените comparison с source и campaign. Event count фиксируем отдельно от пользователей Funnel.',592:'Не суммируйте пользователей разных групп без проверки пересечений. Малые числа указывайте рядом с процентами.',594:'Ending point generate_lead, метрика и условия кейса должны быть явно указаны.',598:'Пустой результат с объяснением ограничений лучше выдуманных чисел.'};
const extraShots={523:'Фильтр Explore: доступные операторы и выбранное точное значение instagram.',543:'Steps: варианты Directly и Indirectly; для базовой воронки выбран Indirectly.',544:'Редактор перехода CTA → Form Start с доступной настройкой Within.',587:'Traffic acquisition с периодом, instagram / social и backend_guide.',595:'Финальное наблюдение: этап, числитель, знаменатель, доля, период и ограничения.'};
const titles={452:'Инструменты анализа GA4',455:'Исследования Explore',464:'Как подобрать поля под вопрос',468:'Источник пользователя и источник сеанса',478:'Когда нужна гибкая настройка отчёта',501:'Что уже можно исследовать в Reports',505:'Начинаем с Free form',511:'Поля и отображение на вкладке',523:'Оператор и точное значение фильтра',529:'Настраиваем воронку',532:'Шаг 1. Начало сеанса',535:'Шаг 4. Событие отправки формы',538:'Потери в людях и процентах',546:'Сравнение устройств: пример',549:'Как сформулировать наблюдение',558:'Страницы после CTA',561:'Когда использовать Funnel и Path',569:'Выводы на малом объёме данных',591:'Найдите наибольшую потерю',595:'Запишите наблюдение с доказательствами',598:'Последовательность анализа',601:'Проверьте понимание',602:'От событий к наблюдениям и гипотезам',604:'Показатели разных систем'};
const stage=id=>{const n=parseInt(id);return n<457?'01 / От сбора к анализу':n<465?'02 / Период и поля':n<479?'03 / Источники и кампании':n<494?'04 / Страницы и события':n<503?'05 / Сравнения и экспорт':n<524?'06 / Free form':n<529?'07 / Фильтры и сегменты':n<551?'08 / Funnel':n<563?'09 / Path':n<570?'10 / Атрибуция':n<582?'11 / Качество и отчёты':n<587?'12 / Общий аналитический слой':'13 / Практика и выводы';};
const deck=[];for(const s of originals){if(titles[s.id])s.title=titles[s.id];if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
const dark=new Set(['450','456','462','468','478','488','501','503','511','524','529','539','551','561','563','569','582','586','598','602','605']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>`<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${s.body||custom[s.id]||md(s.text)}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`).join('\n');
const sources=[
['Области действия источников','https://support.google.com/analytics/answer/11080067?hl=en'],
['Explore: начало работы','https://support.google.com/analytics/answer/7579450?hl=en'],
['Funnel exploration','https://support.google.com/analytics/answer/9327974?hl=en'],
['Path exploration','https://support.google.com/analytics/answer/9317498?hl=en'],
['Создание сегментов','https://support.google.com/analytics/answer/9304353?hl=en'],
['Engagement rate','https://support.google.com/analytics/answer/12195621?hl=en'],
['Key event attribution paths','https://support.google.com/analytics/answer/10595568?hl=en'],
['Analytics Insights','https://support.google.com/analytics/answer/9443595?hl=en'],
['Создание detail report','https://support.google.com/analytics/answer/13844077?hl=en'],
['Коллекции и навигация','https://support.google.com/analytics/answer/10460557?hl=en']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 10 · GA4: отчёты и исследования</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads analytics"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 10<small>Reports → Funnel → Path → вывод</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(450)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>156 исходных слайдов 450–605 + ${deck.length-156} поясняющих экранов. Буква — дополнение после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика продолжает ресурс предыдущих тем. Числа примеров условные. Проверено по официальной документации 08.10.2026. Реальные кадры добавляются после съёмки. Список кадров и комплект — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const shotTable=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads analytics materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 10 / МАТЕРИАЛЫ</p><h1>GA4: отчёты и исследования</h1><p>${deck.length} экранов: все 156 исходных слайдов 450–605 и ${deck.length-156} промежуточных шагов.</p>${dl('ga4-analysis-lab.zip','Скачать комплект анализа')}<p><a href="files/analysis-template.md">Шаблон итогового отчёта</a> · <a href="files/README.md">Порядок практики</a> · <a href="files/field-map.csv">Карта полей CSV</a> · <a href="SCREENSHOTS.md">Список кадров / инструкция Claude</a></p>${cards([['Reports','Период → источник → кампания → страницы → события → сравнения.'],['Explore','Free form → группы → четыре шага Funnel → прямой и обратный Path.'],['Вывод','Наблюдение с числами, ограничение данных, гипотеза, одно изменение и план проверки.']])}<h2>Условия основного кейса</h2>${table(['Настройка','Значение'],[['Source / campaign','instagram / backend_guide'],['Landing page','Проверить /guide.html — маршрут темы 9'],['Воронка','session_start → cta_click → form_start → generate_lead'],['Переходы','Closed · Indirectly · без Within в базовом расчёте'],['Единицы','Sessions в трафике; пользователи Funnel; выбранная метрика Path'],['Результат','generate_lead отдельно от уникальных заявок Sheets']])}<h2>Скриншоты · ${shots.length}</h2><p>PNG помещаются в shots/ с указанными именами. После съёмки выполните node build.mjs. Пока видны честно подписанные заглушки.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>PNG</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${shotTable}</tbody></table></div><h2>Официальная документация</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}<p>Проверено 08.10.2026. Названия меню могут отличаться по языку и опубликованным коллекциям ресурса.</p></main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'deck.json'),JSON.stringify(deck.map((s,i)=>({position:i+1,id:s.id,title:s.title,stage:stage(s.id),screenshot:s.shot?`shots/${s.id}-shot.png`:null})),null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# ОП.03 · Тема 10 · GA4 Reports и Explorations

## Задание для Claude

Сними реальные интерфейсы по презентации последовательно. Рабочая папка: op03-informacionnye-tehnologii/lessons/10-ga4-explorations/shots/. Каждый PNG называй точно по таблице. «Экран» — позиция в колоде, «исходник» — постоянный номер; буква — промежуточный шаг. Ссылка на слайд: index.html#450, index.html#456a и т. д.

Сначала прочитай files/README.md и analysis-template.md. Используй тот же ресурс GA4, что в теме 9. Запиши период и часовой пояс. Все основные кадры снимай на одном ресурсе и периоде; для сравнения дат и Within фиксируй изменение отдельно. Не выдавай условные числа презентации за данные ресурса. Пустые состояния снимай с видимыми настройками и объяснением.

Доступ: Explore и отчёты — в доступном аккаунте; Custom Insights и Library требуют Editor / Administrator. Изменения правил и публикацию новой коллекции делай только в согласованном ресурсе. Email-уведомления другим пользователям не подключай. Не меняй общую атрибуцию или срок хранения ради кадра. Если прав нет, зафиксируй ограничение; не рисуй интерфейс.

Проверяй смысл: Session source вместо First user source; Direct = (direct); Key events не всегда только generate_lead; перед сравнением Instagram/Direct убери общий Instagram-фильтр. На Funnel/Path не оставляй Event name = generate_lead в общих фильтрах — он обрежет маршрут. Для основного кейса на каждой вкладке нужны source=instagram И campaign=backend_guide. Проверяй тип сегмента; не подменяй сессионную группу пользовательской без подписи.

Основной Funnel: четыре шага, Closed, Indirectly, без Within. Path: явно выбранная метрика, отдельные вкладки прямого и обратного маршрута. Итог — реальные числители, знаменатели и гипотеза, не заранее обещанный результат.

Снимай PNG с читаемым текстом, желательно 1600×1000 и выше. На шаге с двумя состояниями допустим один кадр с обоими состояниями либо два снимка, объединённых в PNG без изменения данных. Скрывай чужие персональные данные и секреты; оставляй настройки, период и значения, необходимые для проверки. Записывай время, интерфейс, фактический результат и имя PNG в shots/evidence.json.

После съёмки: node build.mjs в папке темы, проверить каждый PNG в увеличении, проверить manifest. Сейчас запланировано ${shots.length} кадров.

| Экран | Исходник | PNG | Что снять | Статус |
|---|---|---|---|---|
`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/ga4-analysis-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X',zip,'README.md','analysis-template.md','field-map.csv','CHECKLIST.md'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,extras:deck.length-originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
