# Что делает каждая команда урока целиком. Показывается первой строкой в разборе команды.

SUMMARY = {
'whoami': 'Выводит имя пользователя, от имени которого работает оболочка.',
'id': 'Выводит UID, GID основной группы и все группы текущего пользователя.',
'id root': 'Выводит номера и группы учётной записи root.',
'getent passwd ubuntu root': 'Выводит строки учётных записей ubuntu и root из базы пользователей.',
'wc -l /etc/passwd': 'Считает строки в /etc/passwd, то есть число учётных записей.',
'cut -d: -f1,3,7 /etc/passwd | head -8': 'Вырезает из строк /etc/passwd имя, UID и оболочку и оставляет первые восемь строк.',
'grep bash /etc/passwd': 'Выводит строки /etc/passwd, в которых встречается bash, — учётные записи с оболочкой bash.',
'grep -c nologin /etc/passwd': 'Считает строки /etc/passwd со словом nologin — учётные записи без входа в систему.',
'getent passwd www-data': 'Выводит строку служебной учётной записи веб-сервера www-data.',
'ps -eo user= | sort | uniq -c': 'Выводит владельца каждого процесса, сортирует список и считает процессы каждой учётной записи.',
'ls -l /etc/passwd /etc/shadow': 'Выводит права, владельца и группу файлов passwd и shadow рядом.',
'cat /etc/shadow': 'Пытается вывести /etc/shadow от имени обычного пользователя; доступа нет.',
'sudo grep ubuntu /etc/shadow': 'С правами root выводит строку /etc/shadow пользователя ubuntu.',
'sudo grep www-data /etc/shadow': 'С правами root выводит строку /etc/shadow служебной записи www-data.',
'sudo passwd -S ubuntu': 'Выводит состояние пароля ubuntu: задан ли пароль, дату смены и сроки.',
'groups': 'Выводит имена групп текущего пользователя; первая — основная.',
'id -Gn': 'Выводит имена всех групп текущего пользователя.',
'getent group sudo adm': 'Выводит строки групп sudo и adm из базы групп.',
'grep ubuntu /etc/group': 'Выводит строки /etc/group, в которых встречается ubuntu.',
'ls -l /var/log/syslog': 'Выводит владельца, группу и права системного журнала.',
'ls -ld /home/ubuntu': 'Выводит права самого домашнего каталога ubuntu, не заходя внутрь.',
'sudo whoami': 'Выполняет whoami с правами root; команда печатает root.',
'sudo id': 'Выполняет id с правами root; UID и GID равны 0.',
'ls /root': 'Пытается вывести домашний каталог root от имени обычного пользователя; доступа нет.',
'sudo ls -a /root': 'Выводит содержимое /root вместе со скрытыми файлами с правами root.',
'sudo -l': 'Выводит правила sudo, которые действуют для текущего пользователя.',
'ls -l /etc/sudoers': 'Выводит права на файл правил sudo.',
'sudo grep -v "^#" /etc/sudoers | grep -v "^$"': 'Выводит /etc/sudoers без строк-комментариев и без пустых строк.',
'sudo ls /etc/sudoers.d': 'Выводит дополнительные файлы правил sudo.',
'journalctl _COMM=sudo -n 6 --no-pager': 'Выводит шесть последних записей журнала от программы sudo.',
'sudo -i': 'Открывает командную оболочку root. Выход — exit.',
'sudo groupadd devteam': 'Создаёт группу devteam.',
'sudo useradd -m -s /bin/bash -c "Anna Developer" anna': 'Создаёт учётную запись anna с домашним каталогом, оболочкой bash и полным именем.',
'getent passwd anna': 'Выводит строку учётной записи anna.',
'getent group devteam': 'Выводит строку группы devteam вместе со списком участников.',
'sudo ls -la /home/anna': 'С правами root выводит содержимое домашнего каталога anna со скрытыми файлами.',
'ls -la /etc/skel': 'Выводит файлы каталога-образца, которые копируются каждому новому пользователю.',
'sudo adduser boris': 'Создаёт учётную запись boris по шагам: группа, пользователь, домашний каталог, пароль и полное имя.',
'sudo passwd anna': 'Задаёт пароль учётной записи anna; пароль вводится дважды.',
'sudo useradd -m -s /bin/bash -c "Viktor Tester" viktor': 'Создаёт учётную запись viktor с домашним каталогом и оболочкой bash.',
'sudo passwd viktor': 'Задаёт пароль учётной записи viktor.',
'sudo usermod -aG devteam anna': 'Добавляет anna в группу devteam, сохраняя остальные группы.',
'sudo usermod -aG devteam boris': 'Добавляет boris в группу devteam, сохраняя остальные группы.',
'id anna': 'Выводит номера и группы anna.',
'id boris': 'Выводит номера и группы boris.',
'sudo groupadd testers': 'Создаёт группу testers.',
'sudo usermod -aG testers viktor': 'Добавляет viktor в группу testers, сохраняя остальные группы.',
'id viktor': 'Выводит номера и группы viktor или сообщает, что такой записи нет.',
'sudo usermod -G devteam viktor': 'Заменяет весь список дополнительных групп viktor одной группой devteam: testers пропадает.',
'sudo usermod -G testers viktor': 'Задаёт viktor список дополнительных групп заново: только testers.',
'tail -n 3 /etc/passwd': 'Выводит три последние строки /etc/passwd — новые учётные записи.',
'tail -n 5 /etc/group': 'Выводит пять последних строк /etc/group — новые группы.',
'sudo tail -n 3 /etc/shadow': 'С правами root выводит три последние строки /etc/shadow — хеши паролей новых записей.',
'ls -l /home': 'Выводит домашние каталоги с владельцами и правами.',
'sudo mkdir /srv/devteam': 'Создаёт каталог /srv/devteam; владелец — root.',
'ls -ld /srv/devteam': 'Выводит права, владельца и группу самого каталога /srv/devteam.',
'sudo chgrp devteam /srv/devteam': 'Меняет группу каталога /srv/devteam на devteam.',
'sudo chmod 2770 /srv/devteam': 'Устанавливает права: setgid, все права владельцу и группе, никаких прав остальным.',
'sudo -u anna touch /srv/devteam/plan.txt': 'От имени anna создаёт пустой файл plan.txt в общем каталоге.',
'echo "draft by boris" | sudo -u boris tee -a /srv/devteam/plan.txt': 'От имени boris дописывает строку в конец файла plan.txt.',
'sudo -u boris ls -l /srv/devteam': 'От имени boris выводит содержимое общего каталога с владельцами файлов.',
'sudo -u viktor ls /srv/devteam': 'От имени viktor пытается вывести содержимое общего каталога.',
'ls /srv/devteam': 'От имени текущего пользователя пытается вывести содержимое общего каталога.',
'sudo ls -l /srv/devteam': 'С правами root выводит содержимое общего каталога.',
'su - viktor': 'Открывает оболочку viktor с полным входом; спрашивает пароль viktor.',
'journalctl -t sudo --no-pager | grep "NOT in sudoers"': 'Выводит записи sudo об отказах: пользователя нет в правилах.',
'sudo grep "NOT in sudoers" /var/log/auth.log': 'Ищет те же записи об отказах в текстовом журнале входов.',
'journalctl _COMM=su -n 3 --no-pager': 'Выводит три последние записи журнала от программы su.',
'sudo userdel -r viktor': 'Удаляет учётную запись viktor вместе с домашним каталогом.',
'sudo groupdel testers': 'Удаляет группу testers.',
'ls /home': 'Выводит имена домашних каталогов.',
'getent group mobile-dev mobile-qa sudo': 'Выводит строки трёх групп со списками участников.',
'id lead dev qa guest': 'Выводит номера и группы четырёх пользователей команды.',
'ls -l /srv/mobile': 'Выводит каталоги проекта с группами и правами.',
'sudo bash ~/Downloads/team-lab-check.sh': 'Запускает скрипт проверки с правами root: он проверяет записи, группы, права и доступ каждого пользователя.',
}
