import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {copy,titles} from './content.mjs';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)\]\(([^)]+)\)/g,(m,text,url)=>/^https?:/.test(url)?`<a href="${url}" target="_blank" rel="noopener noreferrer">${text}</a>`:`<a class="file-link" href="${url}" download>${text}</a>`);
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const sourceSlides=[...source.matchAll(/^# Слайд (\d+)\.[\s\S]*?(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>({id:+m[1],title:m[0].match(/## Заголовок\s+([\s\S]*?)(?=\n## )/)?.[1].trim(),shot:m[0].match(/## Скриншот\s+([\s\S]*?)(?=\n## |\n---|$)/)?.[1].trim()}));
if(sourceSlides.length!==82||sourceSlides.some((s,i)=>s.id!==89+i||!copy[s.id]))throw Error('Expected every source slide 89–170');
// Редакторское сокращение: определения и выводы уже раскрыты на соседних экранах.
const omitted=new Set([91,99,118,120,121,122,123,124,125,127,134,136,138,141,149,154,155,159]);
const noShot=new Set([126,135]); // на этих экранах разбор кода занимает оба столбца
const slides=sourceSlides.filter(s=>!omitted.has(s.id));
slides.unshift({id:88,title:titles[88],shot:null}); // вводный экран: что меняется по сравнению с темой 5
// Рабочий цикл публикации: один подробный проход перед первой правкой кода.
const cycleShots={201:'GitHub: кнопка Code, вкладка HTTPS и скопированный адрес репозитория.',202:'VS Code: команда Git: Clone и поле для адреса репозитория.',203:'VS Code Explorer: файлы склонированного проекта, открыт index.html.',204:'VS Code: изменение сохранено, метка M у файла в Explorer.',205:'VS Code Source Control: список изменённых файлов и сравнение версий.',206:'VS Code: сообщение коммита и кнопка Commit.',207:'VS Code: кнопка Sync Changes после коммита.',208:'GitHub: новый коммит в истории репозитория.',209:'Vercel Deployments: коммит со статусами Ready и Production.',210:'Production-сайт: изменение видно на опубликованной странице.'};
const cycle=[200,201,202,203,204,205,206,207,208,209,210].map(id=>({id,title:titles[id],shot:cycleShots[id]||null}));
slides.splice(slides.findIndex(s=>s.id===103),0,...cycle);
// Подробный проход Tag Assistant → DebugView: показываем каждый переход.
const debugShots={226:'Tag Assistant: список сообщений и объект параметров события cta_click.',220:'Tag Assistant: список доменов и кнопка «Добавить домен».',221:'Tag Assistant: окно подключения с введённым Production URL.',222:'Вкладка отладки: адрес с gtm_debug и плашка «Tag Assistant подключен».',223:'GA4: путь Администратор → Просмотр данных → DebugView.',224:'GA4 DebugView: минуты слева, лента секунд в центре, верхние события справа.',225:'Нажатие CTA на сайте и событие cta_click в ленте DebugView.'};
const debugFlow=[220,221,222,226].map(id=>({id,title:titles[id],shot:debugShots[id]}));
slides.splice(slides.findIndex(s=>s.id===143),0,...debugFlow);
slides.splice(slides.findIndex(s=>s.id===144),0,{id:223,title:titles[223],shot:debugShots[223]});
slides.splice(slides.findIndex(s=>s.id===145),0,{id:224,title:titles[224],shot:debugShots[224]},{id:225,title:titles[225],shot:debugShots[225]});
// Практика: готовый скрипт с дополнительными метриками.
const practice=[230,233,231,234,235,232].map(id=>({id,title:titles[id],shot:null}));
slides.splice(slides.findIndex(s=>s.id===162),0,...practice);
slides.splice(slides.findIndex(s=>s.id===151),0,{id:236,title:titles[236],shot:null});
const stage=id=>id===236?'Custom Dimensions':id>=230?'Практика':id>=220?'DebugView':id>=200?'Публикация изменений':id<95?'Событийная модель':id<111?'Автоматические измерения':id<119?'Форма и бизнес-смысл':id<132?'Рекомендуемое событие':id<141?'Собственное событие':id<150?'DebugView':id<155?'Custom Dimensions':id<161?'Key Events':'Путь пользователя';
const leadCode=`const leadForm = document.querySelector('#lead-form');
if (leadForm) {
  leadForm.addEventListener('submit', (event) => {
    event.preventDefault();
    if (typeof gtag === 'function') {
      gtag('event', 'generate_lead', {
        lead_source: 'contact_form'
      });
    }
    document.querySelector('#form-status').textContent =
      'Учебная форма проверена. Данные не отправлены.';
  });
}`;
const checklist=['Enhanced Measurement','scroll в Realtime','click по внешней ссылке','file_download','form_start','form_submit','Код generate_lead','generate_lead в Realtime','Код cta_click','Параметры cta_click в DebugView','lead_source в DebugView','Custom Dimension button_name','generate_lead как Key Event'];
const shotLabels={
95:'GA4: данные веб-потока — URL проекта, Measurement ID и блок Enhanced Measurement.',96:'GA4: блок Enhanced Measurement; переключатель находится в положении On.',97:'GA4: открытая панель Enhanced Measurement со списком автоматических измерений.',101:'GA4 Realtime: в списке событий видно scroll после прокрутки длинной страницы.',103:'VS Code: внешняя ссылка на GitHub в index.html, видны href и target.',104:'GA4 Realtime: событие click после перехода по внешней ссылке.',107:'VS Code Explorer: файл assets/analytics-guide.pdf находится в проекте.',108:'VS Code: HTML-ссылка на analytics-guide.pdf с атрибутом download.',109:'GA4 Realtime: событие file_download после нажатия ссылки на PDF.',112:'GA4: в настройках Enhanced Measurement включён пункт Form interactions.',113:'Форма Contacts в браузере и её HTML с id="lead-form" в VS Code.',115:'GA4 Realtime: событие form_start после первого взаимодействия с формой.',116:'GA4 Realtime после отправки учебной формы: form_start получен, form_submit не появился.',119:'VS Code: открыт js/script.js и найден блок обработки формы.',120:'VS Code: строка querySelector для #lead-form.',122:'VS Code: вызов gtag с событием generate_lead внутри submit-обработчика.',124:'VS Code: generate_lead с параметром lead_source: contact_form.',126:'VS Code: целиком виден итоговый обработчик lead-form без второго submit-обработчика.',128:'VS Code Source Control: изменения contacts.html и script.js готовы к коммиту.',129:'Vercel Deployments: нужный коммит имеет статусы Ready и Production.',130:'Production-сайт: форма Contacts после одной успешной учебной отправки; виден URL.',131:'GA4 Realtime: событие generate_lead после отправки формы.',133:'VS Code: кнопка #program-cta в index.html.',134:'VS Code: querySelector для #program-cta.',135:'VS Code: click-обработчик cta_click; виден один обработчик кнопки.',139:'Source Control и Vercel: коммит CTA опубликован, deployment Ready.',140:'GA4 Realtime: событие cta_click после одного нажатия кнопки.',143:'Google Tag Assistant: подключён Production URL учебного сайта.',144:'GA4 DebugView: открыт экран, выбрано своё debug-устройство.',145:'GA4 DebugView: в ленте видна последовательность событий тестового визита.',146:'GA4 DebugView: раскрыто событие generate_lead.',147:'GA4 DebugView: у generate_lead виден lead_source=contact_form.',148:'GA4 DebugView: у cta_click видны button_name=program и page_section=hero.',151:'GA4 Custom definitions: открыт список и кнопка создания определения.',152:'GA4 Create custom dimension: Event scope и параметр button_name.',153:'GA4 Create custom dimension: Event scope и параметр page_section.',157:'GA4 Events: в списке найдено событие generate_lead.',158:'GA4 Events: generate_lead отмечено как Key Event.',160:'GA4 Realtime: новое generate_lead после настройки Key Event.'};

// Разбор кода по строкам: клик по строке открывает объяснение рядом с кодом.
const codewalks={
lead:{file:'js/script.js',lines:[
["const leadForm = document.querySelector('#lead-form');","Находим форму","querySelector ищет элемент по селектору и возвращает его или null. Селектор #lead-form совпадает с id формы в contacts.html.","Опечатка в id — вернётся null, обработчик не установится, а в консоли не будет ни одной ошибки."],
["if (leadForm) {","Проверяем, что форма есть","Один script.js подключён к трём страницам, а форма только на Contacts. На Home и About leadForm равен null.","Без проверки на главной странице возникнет ошибка: Cannot read properties of null."],
["  leadForm.addEventListener('submit', (event) => {","Слушаем отправку формы","Событие submit возникает, когда браузер проверил обязательные поля и готов отправить форму.","Незаполненная форма submit не вызывает: сначала сработает встроенная проверка полей."],
["    event.preventDefault();","Останавливаем перезагрузку страницы","По умолчанию браузер уходит на новый адрес. Здесь мы остаёмся на странице и показываем результат на месте.","Из-за этой строки автоматическое form_submit не засчитывается — проверяли на шаге 11."],
["    if (typeof gtag === 'function') {","Проверяем, что тег загрузился","Функцию gtag объявляет код Google Tag в head. Если тег не вставлен или заблокирован, функции не будет.","Без проверки страница падает с ошибкой gtag is not defined, и сообщение о проверке формы не покажется."],
["      gtag('event', 'generate_lead', {","Отправляем событие","Первый аргумент — команда, второй — имя события. Имя generate_lead рекомендовано Google для заявки.","Своё имя вроде zayavka сломает совместимость с готовыми отчётами Google."],
["        lead_source: 'contact_form'","Добавляем параметр","Третий аргумент — объект параметров. lead_source отвечает на вопрос, откуда пришла заявка.","Сюда нельзя класть имя, телефон или почту: в GA4 запрещены персональные данные."],
["      });","",""],
["    }","",""],
["    document.querySelector('#form-status').textContent =","Показываем результат человеку","Событие ушло в GA4 незаметно для посетителя. Строка в #form-status подтверждает, что форма обработана.","Если блок #form-status удалён из вёрстки, строка вызовет ошибку на null."],
["      'Учебная форма проверена. Данные не отправлены.';","",""],
["  });","",""],
["}","",""]]},
utm:{file:'js/metrics.js',lines:[
["const params = new URLSearchParams(window.location.search);","Читаем адрес страницы","URLSearchParams разбирает часть адреса после знака вопроса и даёт доступ к каждой метке по имени.","Разбор строки вручную ломается на кириллице и на метках, записанных в другом порядке."],
["const utmSource = params.get('utm_source');","Берём источник кампании","get возвращает значение метки или null, если её в адресе нет.","Без проверки на null событие уйдёт с пустым источником и засорит отчёт."],
["if (utmSource) {","Отправляем только для переходов с метками","Прямые заходы и переходы внутри сайта метки не содержат, событие для них не нужно.","Без условия utm_visit будет приходить на каждый просмотр и перестанет означать переход по кампании."],
["  gtag('event', 'utm_visit', {","Своё имя события","Имя описывает смысл: визит по размеченной ссылке. Оно не заменяет источник сессии, который GA4 считает сам.","Имя вроде utm сообщает только про технику, а не про действие."],
["    utm_source: utmSource,","Откуда пришли","Например, telegram или vk — площадка, с которой поставили ссылку.","Случайные значения вроде tg, Telegram и telegram_1 разнесут одну площадку на три строки отчёта."],
["    utm_medium: params.get('utm_medium') || 'not_set',","Тип канала","social, email, cpc. Если метки нет, подставляем not_set, чтобы отличать её отсутствие от ошибки.","Пустая строка в параметре выглядит в отчёте как отсутствие данных, и причину уже не найти."],
["    utm_campaign: params.get('utm_campaign') || 'not_set',","Название кампании","Одно и то же название для всех ссылок одной рассылки или запуска.","Разные названия у ссылок одной кампании сделают сравнение бессмысленным."],
["    landing_page: window.location.pathname","Страница входа","Путь без домена и без параметров: так видно, куда именно вела ссылка.","Полный адрес с параметрами затащит в GA4 лишние данные из строки запроса."],
["  });","",""],
["}","",""]]},
cta:{file:'js/script.js',lines:[
["const programCta = document.querySelector('#program-cta');","Находим кнопку","Тот же приём, что и с формой: ищем элемент по уникальному id. Кнопка есть только на главной странице.","Два элемента с одним id — браузер возьмёт первый, и счёт событий разойдётся с ожиданием."],
["if (programCta) {","Проверяем наличие кнопки","На About и Contacts кнопки нет, поэтому обработчик ставим только там, где элемент найден.","Пропущенная проверка ломает скрипт на двух страницах из трёх."],
["  programCta.addEventListener('click', () => {","Слушаем нажатие","click — обычное событие DOM. Одно нажатие вызывает обработчик один раз.","Повторное подключение script.js удвоит обработчики: одно нажатие даст два события."],
["    document.querySelector('#program-preview').hidden = false;","Показываем описание программы","Это видимый результат для посетителя: скрытый блок становится видимым.","Событие в GA4 и изменение на странице — разные вещи; проверять нужно и то и другое."],
["    gtag('event', 'cta_click', {","Отправляем своё событие","Имени для нажатия CTA у Google нет, поэтому задаём собственное в lowercase_snake_case.","Имена чувствительны к регистру: CTA_Click и cta_click попадут в отчёты как разные события."],
["      button_name: 'program',","Уточняем, какая кнопка","Постоянное значение позволит отличить эту кнопку от других, когда их станет несколько.","Динамическое значение вроде текста кнопки разнесёт одно действие на десятки вариантов."],
["      page_section: 'hero'","Уточняем, где кнопка стоит","hero — верхний блок страницы. Тот же параметр пригодится для кнопок в других секциях.","Значения придумывают заранее и записывают в договорённости проекта, иначе разрез бесполезен."],
["    });","",""],
["  });","",""],
["}","",""]]}};
function code(s,lang='javascript'){return `<figure class="code"><figcaption>${esc(lang)} · <button type="button" data-copy>Копировать</button></figcaption><pre><code>${esc(s)}</code></pre></figure>`;}
function widget(kind,args){
const parts=args.split(';');
if(kind==='flow')return '<ol class="flow">'+args.split(' → ').map((x,i)=>{const[a,b]=x.split('|');return `<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(a)}</b><span>${inline(b||'')}</span></li>`}).join('')+'</ol>';
if(kind==='events')return '<dl class="definitions">'+parts.map(x=>{const[a,b]=x.split('|');return `<div><dt>${inline(a)}</dt><dd>${inline(b)}</dd></div>`}).join('')+'</dl>';
if(kind==='packet'){const [name,fields]=args.split('|');return `<div class="packet"><div class="packet-head"><small>EVENT NAME</small><strong>${esc(name)}</strong></div><dl>${fields.split(';').map(p=>{const at=p.indexOf('=');return `<div><dt>${esc(p.slice(0,at))}</dt><dd>${esc(p.slice(at+1))}</dd></div>`}).join('')}</dl><span class="caption">Учебный состав события · параметры проверяем в DebugView</span></div>`;}
if(kind==='note')return `<aside class="note">${inline(args)}</aside>`;
if(kind==='files')return '<div class="file-cards">'+args.split(';').map(name=>{const full=path.join(root,'files',name.trim());const text=fs.readFileSync(full,'utf8');const size=(Buffer.byteLength(text)/1024).toFixed(1).replace('.',',');return `<article class="file-card"><b>${esc(name.trim())}</b><small>${size} КБ</small><button type="button" data-copy-file data-b64="${Buffer.from(text,'utf8').toString('base64')}">Копировать файл</button><a class="file-link" href="files/${esc(name.trim())}" download>Скачать</a></article>`}).join('')+'</div>';
if(kind==='fields')return '<dl class="fields">'+parts.map(x=>{const[a,b]=x.split('|');return `<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`}).join('')+'</dl>';
if(kind==='timeline')return '<ol class="timeline">'+parts.map((t,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><code>${esc(t)}</code></li>`).join('')+'</ol>';
if(kind==='leadcode')return code(leadCode);
if(kind==='codewalk'){const w=codewalks[args.trim()];return `<div class="codewalk" data-walk="${esc(args.trim())}"><ol class="cw-code">${w.lines.map(([src,title,text,err],i)=>title?`<li><button type="button" data-cw="${i}"><code>${esc(src)}</code></button></li>`:`<li class="cw-plain"><code>${esc(src)}</code></li>`).join('')}</ol><aside class="cw-note"><p class="caption">${esc(w.file)} · нажмите строку</p><div class="cw-body"><h3>Что делает каждая строка</h3><p>Нажмите любую подсвеченную строку слева: появится объяснение, зачем она нужна и что ломается без неё.</p></div></aside>${w.lines.map(([src,title,text,err],i)=>title?`<template data-cw-note="${i}"><h3>${esc(title)}</h3><p>${esc(text)}</p><p class="cw-err"><b>Если убрать:</b> ${esc(err)}</p></template>`:'').join('')}</div>`;}
if(kind==='scroll')return `<div class="scroll-model"><label>Глубина просмотра: <output>0%</output><input type="range" min="0" max="100" value="0" aria-label="Глубина прокрутки"></label><div class="depth"><i></i><span>порог 90%</span></div><p role="status">Глубина 0%. Порог не пройден, событий scroll: 0.</p><button type="button" data-reset-scroll>Новый просмотр</button><small>Локальная модель · ничего не отправляет в Google</small></div>`;
if(kind==='decision')return `<ol class="decision"><li><b>Собирается автоматически?</b><span>Да → проверяем и используем существующее событие.</span></li><li><b>Есть рекомендуемое имя?</b><span>Да → реализуем отправку с именем Google.</span></li><li><b>Нужен свой смысл?</b><span>Создаём Custom Event и описываем его параметры.</span></li></ol>`;
if(kind==='comparison')return '<table><caption>Учебный пример, не данные аккаунта</caption><thead><tr><th>Источник</th><th>Пользователи</th><th>С заявкой</th><th>Доля</th></tr></thead><tbody><tr><td>Telegram</td><td>100</td><td>12</td><td>12%</td></tr><tr><td>VK</td><td>180</td><td>7</td><td>3,9%</td></tr><tr><td>Direct</td><td>50</td><td>9</td><td>18%</td></tr></tbody></table>';
if(kind==='funnel')return '<div class="funnel">'+[['page_view',1000,100],['cta_click',300,70],['form_start',120,49],['generate_lead',80,35]].map(([n,c,w])=>`<div style="--w:${w}%"><code>${n}</code><b>${c}</b></div>`).join('')+'</div>';
if(kind==='checklist')return '<ol class="checklist">'+checklist.map(t=>`<li><label><input type="checkbox">${esc(t)}</label></li>`).join('')+'</ol>';
if(kind==='quiz')return '<div class="quiz">'+[['Event и parameter','Event описывает действие; parameter уточняет подробности. Например, cta_click и button_name=program.'],['Automatic, Recommended и Custom','Автоматическое измерение выполняет тег; рекомендуемое имя Google реализуем сами; собственное имя определяем для своей задачи.'],['DebugView и Custom Dimension','DebugView показывает параметр конкретного события. Custom Dimension регистрирует разрез для отчётов.'],['Key Event','Это статус важного действия в ресурсе GA4. Он сам не создаёт событие и не добавляет обработчик.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')+'</div>';
throw Error('Unknown widget '+kind);
}
function render(md){let result=[],lines=md.trim().split('\n'),i=0;while(i<lines.length){const l=lines[i];if(!l.trim()){i++;continue}if(l.startsWith('~~~')){const lang=l.slice(3);let body=[];i++;while(i<lines.length&&!lines[i].startsWith('~~~'))body.push(lines[i++]);i++;result.push(code(body.join('\n'),lang));continue}if(l.startsWith(':::')){const [,kind,args='']=l.match(/^:::(\w+)\s*(.*)$/);result.push(widget(kind,args));i++;continue}let p=[];while(i<lines.length&&lines[i].trim()&&!/^(:::|~~~)/.test(lines[i]))p.push(lines[i++]);result.push('<p>'+inline(p.join(' '))+'</p>')}return result.join('\n')}
const trace=`<div class="event-lab"><div><p class="caption">ДЕМОНСТРАЦИЯ · ЛОКАЛЬНО</p><h3>Действие → запись события</h3><p>Нажмите кнопку и раскройте запись.</p><button type="button" data-demo-event="cta_click">Посмотреть программу</button><button type="button" data-demo-event="generate_lead">Проверить учебную форму</button><button type="button" data-demo-clear>Очистить</button></div><output class="event-log" aria-live="polite">Журнал пуст. В GA4 ничего не отправляется.</output></div>`;
const sources=[['Enhanced Measurement','https://support.google.com/analytics/answer/9216061?hl=ru'],['Рекомендуемые события','https://developers.google.com/analytics/devguides/collection/ga4/reference/events#generate_lead'],['DebugView','https://support.google.com/analytics/answer/7201382?hl=ru'],['Custom Dimensions','https://support.google.com/analytics/answer/14240153?hl=ru'],['Key Events','https://support.google.com/analytics/answer/13128484?hl=ru'],['Имена событий','https://support.google.com/analytics/answer/13316687?hl=ru']];
let manifest=[];
const sections=slides.map((s,i)=>{let title=titles[s.id]||s.title;let body=render(copy[s.id]);if(s.id===92)body+=trace;const file=`shots/${s.id}-shot.png`;if(s.shot&&!noShot.has(s.id)){const requested=shotLabels[s.id]||cycleShots[s.id]||debugShots[s.id]||s.shot.replace(/\n+/g,' ');const exists=fs.existsSync(path.join(root,file));manifest.push({slide:s.id,title,requested,file,status:exists?'captured':'pending'});if(exists)body+=`<figure class="shot"><button data-zoom><img src="${file}" alt="${esc(requested)}" loading="lazy"></button><figcaption>${esc(requested)}</figcaption></figure>`;else body+=`<figure class="capture-slot"><div aria-hidden="true"><span>МЕСТО ДЛЯ СКРИНШОТА</span><b>${esc(file)}</b></div><figcaption>${inline(requested)} <a href="SCREENSHOTS.md#slide-${s.id}">чек-лист ↗</a></figcaption></figure>`;}return `<section class="lesson-slide ${[88,89,117,132,170].includes(s.id)?'dark':''}" id="slide-${s.id}" data-title="${esc(title)}" data-stage="${stage(s.id)}" aria-labelledby="title-${s.id}"><div class="lesson-inner"><p class="kicker">${stage(s.id)}<span>${s.id===88?'ПЛАН ЗАНЯТИЯ':s.id===236?'ИСХОДНИК 150a':s.id>=230?'ПРАКТИКА':s.id>=220?'ОТЛАДКА':s.id>=200?'РАБОЧИЙ ЦИКЛ':'ИСХОДНИК '+s.id} · ${i+1} / ${slides.length}</span></p><h${i===0?1:2} id="title-${s.id}">${inline(title)}</h${i===0?1:2}><div class="content">${body}</div></div></section>`}).join('\n');
const html=`<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0C2733"><title>Тема 6 · События GA4 · ОП.03</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head>
<body class="events6"><a class="skip" href="#lesson-slides">К слайду</a><header class="lesson-header"><a class="brand6" href="../../index.html"><span>И/Т</span><b>ОП.03 · ТЕМА 06<small>События · параметры · ключевые действия</small></b></a><nav aria-label="Управление"><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources">Источники</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${slides.length}</span></nav></header>
<main id="lesson-slides" tabindex="-1">${sections}</main><footer class="lesson-footer"><span id="chapter">Событийная модель</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next" aria-label="Следующий слайд">Далее →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${slides.length}" aria-valuenow="1"><i id="progress"></i></div></footer>
<dialog id="contents"><header><h2>Тема 6 · ${slides.length} слайд</h2><button data-close aria-label="Закрыть">✕</button></header><p>Сохранены исходные номера сценария; дублирующие экраны пропущены. Прямая ссылка: index.html#147.</p><div class="contents-list">${slides.map((s,i)=>`<button data-go="${s.id}"><b>${String(i+1).padStart(2,'0')}</b><span>${inline(titles[s.id]||s.title)}</span><small>${s.id}</small></button>`).join('')}</div></dialog>
<dialog id="sources"><header><h2>Источники и материалы</h2><button data-close aria-label="Закрыть">✕</button></header><p>Итоговая версия: ${slides.length} слайд из авторского сценария 89–170. Технические сведения сверены с документацией Google.</p>${sources.map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗</a>`).join('')}<p>39 кадров для пошаговой инструкции перечислены в материалах.</p><a href="materials.html">Материалы и рабочий пример →</a><button id="print">Печать / сохранить PDF</button></dialog>
<dialog id="visual"><header><h2>Скриншот</h2><button data-close aria-label="Закрыть">✕</button></header><img alt=""></dialog><div id="announcement" class="sr-only" aria-live="polite"></div><noscript><p>JavaScript выключен: все слайды доступны последовательно.</p></noscript></body></html>`;
fs.writeFileSync(path.join(root,'index.html'),html);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(manifest,null,2)+'\n');
const cycleIds=new Set([201,202,203,204,205,206,207,208,209,210]);
const debugIds=new Set([220,221,222,223,224,225,226]);
const ga4Ids=new Set([95,96,97,101,104,109,112,115,116,131,140,143,144,145,146,147,148,151,152,153,157,158,160]);
const publishIds=new Set([129,130,139]);
const groups=[['Рабочий цикл публикации',m=>cycleIds.has(m.slide)],['Tag Assistant и DebugView: переходы',m=>debugIds.has(m.slide)],['GA4 и Tag Assistant',m=>ga4Ids.has(m.slide)],['Публикация и сайт',m=>publishIds.has(m.slide)],['Редактор и код',()=>true]];
let rest=[...manifest];let shotText='# Список скриншотов · Тема 6\n\nВсего: **'+manifest.length+'**. Каждый файл вставляется на одноимённый слайд автоматически после команды `node build.mjs`. До съёмки на слайде видна пустая рамка. Снимать личный учебный проект; скрыть аккаунт, почту и другие личные данные. Интерфейс должен показывать указанный результат, а не только открытый раздел.\n\n';
for(const [name,test] of groups){const batch=rest.filter(test);rest=rest.filter(x=>!batch.includes(x));if(!batch.length)continue;shotText+=`## ${name}\n\n`+batch.map(s=>`<a id="slide-${s.slide}"></a>\n\n- [ ] **${s.slide}. ${s.title}** — ${s.requested}\n  - Файл: \`${s.file}\``).join('\n\n')+'\n';}
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),shotText);
console.log(`Built ${slides.length} slides, ${manifest.length} planned screenshots`);
