'use strict';
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const progress=$('.progress span');
function readingProgress(){const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=(max>0?Math.min(100,scrollY/max*100):100)+'%'}
addEventListener('scroll',readingProgress,{passive:true});addEventListener('resize',readingProgress);addEventListener('load',readingProgress);
if('ResizeObserver'in window)new ResizeObserver(readingProgress).observe(document.body);
readingProgress();
const dialog=$('#image-dialog');let lastZoom;
$$('.zoom').forEach(button=>button.addEventListener('click',()=>{lastZoom=button;const img=$('img',dialog);img.src=button.dataset.image;img.alt=$('img',button).alt;$('p',dialog).textContent=img.alt;dialog.showModal()}));
dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close()}});
dialog.addEventListener('close',()=>lastZoom?.focus());
function pressed(buttons,current){buttons.forEach(b=>b.setAttribute('aria-pressed',String(b===current)))}
const architecture=$('[data-architecture]');
if(architecture){$$('[data-mode]',architecture).forEach(button=>button.addEventListener('click',()=>{pressed($$('[data-mode]',architecture),button);const production=button.dataset.mode==='production';const names=production?['Пользователи','API × 3','База / кэш','Очередь','Worker × 5']:['Разработчик','FastAPI','Хранилище'];const route=$('.system-route',architecture);route.replaceChildren();names.forEach((name,i)=>{if(i){const arrow=document.createElement('i');arrow.textContent='→';arrow.setAttribute('aria-hidden','true');route.append(arrow)}const cell=document.createElement('span');cell.textContent=name;cell.className=production?'active':'';route.append(cell)});$('.widget-detail',architecture).textContent=production?'Много параллельных операций. Часть работы продолжается после ответа API. Для восстановления прошлого нужны сохранённые сигналы.':'Один запрос. Терминал и состояние процесса доступны разработчику.'}))}
const history=$('[data-history]');
if(history){let current=[78,80,82,79,81,80];let frame;const draw=(values)=>{const points=values.map((v,i)=>[55+i*119,190-v*1.6]);$('.history-line',history).setAttribute('points',points.map(p=>p.join(',')).join(' '));const dots=$('.history-dots',history);dots.replaceChildren();points.forEach(([x,y],i)=>{const circle=document.createElementNS('http://www.w3.org/2000/svg','circle');circle.setAttribute('cx',x);circle.setAttribute('cy',y);circle.setAttribute('r','4');const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=`09:0${i}: ${Math.round(values[i])}%`;circle.append(title);dots.append(circle)})};draw(current);$$('[data-series]',history).forEach(b=>b.addEventListener('click',()=>{pressed($$('[data-series]',history),b);const next=b.dataset.series==='steady'?[78,80,82,79,81,80]:[20,23,22,25,60,80];cancelAnimationFrame(frame);const old=current.slice();const start=performance.now();const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?0:420;function tick(now){const t=duration?Math.min(1,(now-start)/duration):1;current=old.map((v,i)=>v+(next[i]-v)*t);draw(current);if(t<1)frame=requestAnimationFrame(tick)}frame=requestAnimationFrame(tick);$('svg',history).setAttribute('aria-label','CPU в процентах: '+next.join(', ')+'. Последнее значение 80%.');$('.widget-detail',history).textContent=next.join(' → ')+'%. Последнее значение: 80%. '+(b.dataset.series==='steady'?'Колебания около устойчивого уровня.':'За короткий интервал появилась новая нагрузка; нужно проверить влияние на пользователя.')}))}
const quantile=$('[data-quantile]');
if(quantile&&window.TELEMETRY_DATA){let order='original';let selected;function draw(){const rows=TELEMETRY_DATA.requests.slice();if(order==='sorted')rows.sort((a,b)=>a.client_ms-b.client_ms);const chart=$('.duration-chart',quantile);const max=Math.max(...rows.map(r=>r.client_ms));chart.replaceChildren();rows.forEach((row,index)=>{const bar=document.createElement('button');bar.type='button';bar.style.height=Math.max(2,row.client_ms/max*90)+'%';bar.className=(row.scenario==='slow'?'slow':row.status>=500?'error':'')+(selected===row.number?' selected':'');bar.setAttribute('aria-label',`Запрос ${row.number}, ${row.client_ms.toFixed(1)} мс, HTTP ${row.status}; позиция ${index+1}`);bar.title=bar.getAttribute('aria-label');bar.setAttribute('aria-pressed',String(selected===row.number));const span=document.createElement('span');span.textContent=row.number;bar.append(span);bar.addEventListener('click',()=>{selected=row.number;draw();$('.widget-detail',quantile).textContent=`Запрос №${row.number}: ${row.client_ms.toFixed(3)} мс, HTTP ${row.status}. `+(order==='sorted'?`Позиция ${index+1} из 20. `:'')+(order==='sorted'&&index===18?'Это 19-е значение — p95 по ближайшему рангу.':'')});chart.append(bar)})}draw();$$('[data-order]',quantile).forEach(b=>b.addEventListener('click',()=>{order=b.dataset.order;pressed($$('[data-order]',quantile),b);selected=undefined;draw();$('.widget-detail',quantile).textContent=order==='sorted'?`19-я позиция: ${TELEMETRY_DATA.requests.map(r=>r.client_ms).sort((a,b)=>a-b)[18].toFixed(3).replace('.',',')} мс — это p95 по методу ближайшего ранга. Быстрый ответ с ошибкой тоже входит в выборку.`:'Показан порядок отправки. Медленные запросы — №7 и №17, ошибка — №13.'}))}
const log=$('[data-log]');
if(log){const texts={timestamp:'Время события с часовым поясом. Помогает сопоставить историю, но не заменяет идентификатор запроса.',level:'Уровень важности записи. ERROR не сообщает частоту проблемы и число пострадавших операций.',service:'Компонент, создавший запись. В нескольких экземплярах дополнительно нужен идентификатор instance.',event:'Что произошло: request_completed. Такое событие можно считать, если известно, что оно создаётся один раз на операцию.',status:'Результат HTTP. Код 200 сам по себе не подтверждает корректность бизнес-действия.',request_id:'Связывает события одного запроса. В метрике с неограниченными значениями породил бы слишком много рядов.',duration_ms:'Длительность обработчика в миллисекундах. Не включает весь путь клиента по сети.'};$$('[data-field]',log).forEach(b=>b.addEventListener('click',()=>{pressed($$('[data-field]',log),b);$('.widget-detail',log).textContent=texts[b.dataset.field]}))}
const waterfall=$('[data-waterfall]');
if(waterfall&&window.TELEMETRY_DATA){const event=TELEMETRY_DATA.slow;const spans=[{name:'GET /products',offset_ms:0,duration_ms:event.duration_ms},...event.spans];let selected=0;$('.trace-end',waterfall).textContent=event.duration_ms.toFixed(1)+' мс';function draw(){const root=$('.waterfall-rows',waterfall);root.replaceChildren();spans.forEach((s,i)=>{const row=document.createElement('div');row.className='waterfall-row'+(i===selected?' active':'');const btn=document.createElement('button');btn.textContent=s.name;btn.setAttribute('aria-pressed',String(i===selected));btn.addEventListener('click',()=>{selected=i;draw()});const track=document.createElement('div');track.className='span-track';track.setAttribute('aria-label',`${s.name}: начало ${s.offset_ms.toFixed(1)} мс; длительность ${s.duration_ms.toFixed(1)} мс`);const bar=document.createElement('div');bar.className='span-bar';bar.style.left=(s.offset_ms/event.duration_ms*100)+'%';bar.style.width=Math.min(100-s.offset_ms/event.duration_ms*100,s.duration_ms/event.duration_ms*100)+'%';track.append(bar);row.append(btn,track);root.append(row)});const s=spans[selected];$('.widget-detail',waterfall).textContent=`${s.name}: от ${s.offset_ms.toFixed(1)} до ${(s.offset_ms+s.duration_ms).toFixed(1)} мс, длительность ${s.duration_ms.toFixed(1)} мс. `+(selected===2?'Основное ожидание в этом сценарии внесено сюда через asyncio.sleep.':selected===0?'Родительский интервал уже включает дочерние этапы.':'Положение полосы задано смещением относительно начала обработчика.');$('[data-trace-step="next"]',waterfall).disabled=selected===spans.length-1}draw();$$('[data-trace-step]',waterfall).forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.traceStep==='reset'?0:Math.min(spans.length-1,selected+1);draw()}))}
const investigation=$('[data-investigation]');
if(investigation){let index=0;const steps=[['Жалоба: иногда 4–5 секунд','Один повторный запрос прошёл за 180 мс.','Одна проверка быстрая. Частота замедлений неизвестна.','Есть ли распределение длительностей за интервал жалобы?'],['Изменилось распределение','У /products вырос p95. Доля ошибок и поток запросов без заметного изменения.','Есть ухудшение длительности выбранного маршрута. Число затронутых пользователей пока неизвестно.','Совпадает ли задержка у всех экземпляров и версий?'],['Один экземпляр отличается','Длинные запросы сосредоточены на api-2. CPU и память похожи на другие экземпляры.','Область поиска сузилась до api-2. Высокая загрузка CPU не подтверждена.','Какие этапы длинного запроса отличаются от быстрого?'],['Ожидание перед SQL','В выбранной трассе acquire_connection занимает 2,8 с, SELECT — 35 мс.','Выбранная операция ждала соединение. Сам SQL в этой трассе короткий.','Почему соединение было недоступно: занятость, конфигурация, длительное удержание?'],['Гипотеза для проверки','На api-2 после релиза пул уменьшили с 10 до 2. Другие экземпляры сохранили 10.','Изменение согласуется с симптомом, но нужна проверка при сравнимой нагрузке.','Восстановить конфигурацию в контролируемом опыте и сопоставить ожидание, нагрузку и последствия.']];function draw(){const s=steps[index];$('.step-count',investigation).textContent=`${index+1} / ${steps.length}`;$('.finding-title',investigation).textContent=s[0];$('.finding-fact',investigation).textContent=s[1];$('.finding-known',investigation).textContent=s[2];$('.finding-question',investigation).textContent=s[3];$('[data-investigate="prev"]',investigation).disabled=index===0;$('[data-investigate="next"]',investigation).disabled=index===steps.length-1}$$('[data-investigate]',investigation).forEach(b=>b.addEventListener('click',()=>{index=Math.max(0,Math.min(steps.length-1,index+(b.dataset.investigate==='next'?1:-1)));draw()}));draw()}
const exercise=$('[data-signal-exercise]');
if(exercise)$('[data-check-signals]',exercise).addEventListener('click',()=>{let correct=0;const sets=$$('fieldset',exercise);sets.forEach(set=>{const values=$$('input:checked',set).map(x=>x.value).sort().join(',');const answer=set.dataset.answer.split(',').sort().join(',');const ok=values===answer;if(ok)correct++;const feedback=$('.feedback',set);feedback.hidden=false;if(!feedback.dataset.explanation)feedback.dataset.explanation=feedback.textContent;feedback.textContent=(ok?'Верно. ':'Пересмотрите выбор. ')+feedback.dataset.explanation});$('.exercise-score',exercise).textContent=`Верных строк: ${correct} из ${sets.length}. Можно изменить выбор и проверить снова.`});
const scrape=$('[data-scrape]');
if(scrape){let step=0;const texts=['1. Приложение обновляет свои измерения при обработке запросов.','2. Prometheus отправляет HTTP GET к /metrics приложения. Это pull-сбор.','3. Приложение возвращает текущие числа. Prometheus сохраняет наблюдения с отметкой времени.','4. Grafana запрашивает данные у Prometheus и отображает результат.'];$('[data-scrape-step]',scrape).addEventListener('click',()=>{step=(step+1)%texts.length;$('.widget-detail',scrape).textContent=texts[step];const cells=$$('.scrape-route>div',scrape);cells.forEach(x=>x.classList.remove('active'));cells[step===0?0:step===3?4:2].classList.add('active');$('.scrape-route .scrape-arrow',scrape).textContent=step===2?'→ данные':'← HTTP GET'})}
// Без JavaScript видны команды обеих систем; переключатель скрывает лишние только после загрузки скрипта.
$$('.os-commands').forEach(root=>{const show=os=>$$('[data-command]',root).forEach(block=>block.hidden=block.dataset.command!==os);const buttons=$$('[data-os]',root);show((buttons.find(b=>b.getAttribute('aria-pressed')==='true')||buttons[0]).dataset.os);buttons.forEach(b=>b.addEventListener('click',()=>{pressed(buttons,b);show(b.dataset.os)}))});
