import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||''};});
if(originals.length!==90||originals.some((s,i)=>+s.id!==264+i))throw Error('Нарушен исходный порядок 264–353');
const extras={
272:[{id:'272a',title:'Как выгрузить заявки из темы 7',body:click(['Google Sheets','Лист leads','Файл','Скачать','CSV'])+bullets(['Откройте учебную таблицу темы 7 и выберите лист leads.','Файл → Скачать → Значения, разделённые запятыми (.csv, текущий лист).','Сохраните выгрузку отдельно как leads_export.csv. Рабочую таблицу не меняйте.'])+note('Это снимок одного листа. Power Query в этом занятии не подключён к Google Sheets напрямую.'),shot:'Google Sheets: выбран лист leads, раскрыто Файл → Скачать, пункт CSV.',accent:'Текущий лист и пункт CSV.'},
{id:'272b',title:'Учебная копия отличается от выгрузки',body:cards([['В теме 7','9 полей, отдельные utm_source и utm_medium, полный UUID.'],['В практике 8','8 входных полей: source_medium объединяет source и medium через |. ID сокращены для чтения.']])+note('Для повторяемого упражнения берём готовый leads_dirty.csv ниже. Не нужно портить живые заявки или отправлять REQ-001 в Apps Script.') }],
273:[{id:'273a',title:'Подготовьте папку до запуска Excel',body:dl('power-query-lab.zip','Скачать комплект практики')+bullets(['Распакуйте архив целиком в постоянную папку.','В data найдите leads_dirty.csv, резервную v1 и вторую версию v2.','В result позже сохраните книгу. CSV импортируем из распакованной папки, не из ZIP.'])+result('Файл data/leads_dirty.csv доступен; его путь не изменится до конца практики.'),shot:'Проводник или Finder: распакованная lesson_power_query, папки data и result; в data видны три CSV.'}],
277:[{id:'277a',title:'Перед началом проверьте Excel',body:cards([['Основной маршрут','Настольный Excel для Windows: Данные → Получить данные → Из файла → Из текста/CSV.'],['Если вы на Mac','В Microsoft 365 проверьте Данные → Получить данные (Power Query) и наличие редактора. Названия меню могут отличаться.']])+note('Если редактора Power Query нет, используйте подготовленный компьютер с нужной версией Excel. Не заменяйте эту практику обычным открытием CSV или ручной очисткой ячеек.'),shot:'Excel: вкладка Данные и доступная команда получения данных / Power Query; зафиксировать ОС и версию в evidence.json.'}],
282:[{id:'282a',title:'Начнём без автоматической смены типов',body:click(['Text/CSV preview','Data Type Detection','Do not detect data types'])+bullets(['Если настройка доступна, выберите «Не определять типы данных».','Если её нет — продолжайте. В редакторе проверим автоматически добавленный Changed Type.','Первые строки должны разбиваться на 8 столбцов, русские имена — читаться.'])+result('UTF-8, запятая, 8 исходных полей; wrong_date пока читается как текст.'),shot:'Окно импорта: UTF-8, Comma и список Data Type Detection, если доступен в установленной версии.'}],
285:[{id:'285a',title:'Убедитесь, что первая строка — заголовки',body:bullets(['В заголовках ожидаем request_id, created_at, name и остальные поля CSV.','Если видны Column1…Column8, выберите Главная → Использовать первую строку как заголовки.','Если имена уже правильные — эту команду повторно не нажимайте.'])+result('8 именованных столбцов и 5 строк заявок. Заголовок не стал заявкой, REQ-001 не исчез.'),shot:'Power Query: имена восьми столбцов и пять записей; при необходимости команда Use First Row as Headers.'}],
296:[{id:'296a',title:'Как назначить Text нескольким столбцам',body:bullets(['Удерживая Ctrl (на Mac — ⌘), выделите заголовки семи полей, кроме created_at.','Transform → Data Type → Text. Если предложено — Replace current / Заменить текущий шаг.','Если ранний Changed Type уже исказил значения, вернитесь к нему и исправьте типы; не удаляйте поздние шаги наугад.'])+result('У request_id и остальных текстовых полей значок ABC. Затем отдельно задаём created_at.'),shot:'Выделенные текстовые столбцы и меню Data Type → Text.'}],
303:[{id:'303a',title:'Внутренний двойной пробел — отдельный шаг',body:code('« Иван  Тестов »\nTrim → «Иван  Тестов»\nReplace Values: два пробела → один\nРезультат → «Иван Тестов»','ТОЛЬКО СТОЛБЕЦ name')+bullets(['Выберите name → Transform → Replace Values.','В Value to find введите два обычных пробела, в Replace with — один.','Здесь Match entire cell contents выключен: заменяем фрагмент внутри имени.'])+note('Это явное учебное правило для повторяющихся обычных пробелов. Trim и Clean его не выполняют.'),shot:'Replace Values для name: два пробела заменяются одним. Рядом результат Иван Тестов.',accent:'В подписи пояснить невидимые символы: 2 пробела → 1 пробел.'}],
312:[{id:'312a',title:'Не забудьте края campaign и status',body:click(['utm_campaign + status','Transform','Format','Trim'])+bullets(['Выделите utm_campaign и status; примените Trim.','После этого « new » станет «new». Одного lowercase для удаления пробелов недостаточно.','На следующем шаге выделяем уже все четыре категориальных поля.'])+result('Краевые пробелы удалены и у UTM, и у статуса.'),shot:'Выделены utm_campaign и status, раскрыта команда Trim.'}],
330:[{id:'330a',title:'Подготовьте вторую версию и сохраните первую',body:dl('lesson_power_query/data/leads_dirty_v2.csv','Скачать v2 отдельно')+bullets(['V1 содержит 5 записей; v2 — 8, включая новые REQ-006…REQ-008.','Резервная версия leads_dirty_v1_backup.csv уже лежит в data.','Закройте Power Query Editor через Close & Load, дождитесь загрузки и сохраните книгу.'])+note('Новый запрос не создаём. Существующий Source по-прежнему читает leads_dirty.csv.'),shot:'Папка data: рабочий leads_dirty.csv, резервная v1 и файл leads_dirty_v2.csv.'}],
331:[{id:'331a',title:'Как заменить содержимое без смены пути',body:bullets(['В текстовом редакторе откройте leads_dirty_v2.csv и скопируйте всё содержимое, включая заголовок.','Откройте data/leads_dirty.csv → выделите всё → вставьте v2 → сохраните в UTF-8.','Проверьте имя: именно leads_dirty.csv, без дополнительного .txt.'])+result('В рабочем CSV теперь 8 заявок и те же 8 заголовков. Книга остаётся подключена к прежнему пути.'),shot:'Текстовый редактор: рабочий leads_dirty.csv после замены, видны REQ-006…REQ-008.'}],
337:[{id:'337a',title:'Сохраните обновлённую книгу',body:click(['Power Query','Close & Load','Дождаться загрузки','Сохранить книгу'])+bullets(['Сохраните result/power_query_leads.xlsx после обновления.','Для сдачи сохраните всю папку практики вместе с CSV и контрольными кадрами.','При переносе на другой компьютер проверьте путь Source; при необходимости исправьте его через Data Source Settings.'])+result('Книга содержит запрос, его шаги и актуальный результат. Одного CSV для сохранения запроса недостаточно.'),shot:'Excel: результат после Refresh и сохранение книги result/power_query_leads.xlsx.'}]
};
const custom={
264:`<p class="lead">В теме 7 форма отправляла заявку в Google Sheets. Теперь готовим копию этих данных для анализа.</p>${flow(['Форма','Apps Script','Google Sheets','CSV → Power Query'])}${note('GA4 остаётся параллельной веткой: generate_lead описывает событие, а не содержимое клиентской заявки.')}<p><strong>Что делать, когда строк много, а значения записаны по-разному?</strong></p>`,
265:cards([['Пять вариантов', '`Telegram` · ` telegram` · `TELEGRAM` · `tg` · ` Telegram `'],['Одно правило','Trim → lowercase → точная замена tg на telegram.']])+code('telegram','ЕДИНОЕ ЗНАЧЕНИЕ'),
266:cards([['Сегодня','CSV → 15 ручных исправлений → результат.'],['Завтра','Новый CSV → те же 15 исправлений заново.']])+note('Ручные действия трудно воспроизвести и проверить на большом наборе.'),
267:flow(['Источник','Правила преобразования','Результат'])+note('Настраиваем правила один раз. При обновлении они применяются к новой версии источника.'),
268:cards([['Подключение','CSV, книги Excel, базы данных и другие источники.'],['Подготовка','Типы, текст, структура столбцов, ошибки и объединения.'],['Повторение','Refresh заново читает источник и выполняет сохранённые шаги.']]),
269:cards([['Источник','leads_dirty.csv остаётся неизменным при преобразованиях.'],['Запрос','Хранит последовательность действий над копией данных.'],['Результат','Загружается в Excel как отдельная таблица.']]),
270:cards([['Extract · получить','Прочитать учебный CSV.'],['Transform · преобразовать','Очистить текст, разделить поля и назначить типы.'],['Load · загрузить','Вывести результат в книгу Excel.']]),
271:flow(['CSV','Импорт','Типы и Error','Trim / Clean','Split / Rename','lowercase / Replace','Загрузка','Новый CSV / Refresh']),
273:code('lesson_power_query/\n├── data/\n│   ├── leads_dirty.csv\n│   ├── leads_dirty_v1_backup.csv\n│   └── leads_dirty_v2.csv\n├── result/\n│   └── power_query_leads.xlsx  ← создадите в Excel\n└── README.md','ПАПКА ПРАКТИКИ'),
274:code('request_id,created_at,name,email,direction,source_medium,utm_campaign,status\nREQ-001,2026-09-23 12:40:00," Иван  Тестов ",student1@example.com,backend," Telegram | Social ","LESSON07","NEW"\nREQ-003,wrong_date," Петр",student3@example.com,frontend," telegram|SOCIAL ","Lesson07","done"','ФРАГМЕНТ CSV · ПОЛНЫЙ ФАЙЛ В АРХИВЕ')+note('5 строк данных, 8 столбцов. ID — учебные метки; значения вымышленные.'),
275:cards([['Формат','Пробелы по краям и внутри имени; разный регистр.'],['Структура','source и medium соединены в source_medium.'],['Смысл и тип','TG — псевдоним telegram; wrong_date не является датой.']]),
276:code('request_id  created_at  name  email  direction\nutm_source  utm_medium  utm_campaign  status','9 ПОЛЕЙ ПОСЛЕ SPLIT')+cards([['Было','« Иван  Тестов » · « Telegram | Social » · NEW'],['Стало','Иван Тестов · telegram · social · new']])+note('Двойной пробел внутри имени исправим отдельной заменой. Ошибочную дату сохраним видимой; «очищено» пока не значит «проверено полностью».'),
278:click(['Excel','Пустая книга','Сохранить как'])+code('lesson_power_query/result/power_query_leads.xlsx','ИМЯ КНИГИ')+result('Открыта пустая книга .xlsx. CSV остаётся отдельным входным файлом.'),
279:click(['Excel','Data / Данные'])+`<p>Найдите группу <strong>Get & Transform Data / Получение и преобразование данных</strong>. Отсюда запускается импорт.</p>`+result('Работаем во вкладке Данные, а не открываем CSV двойным щелчком.'),
280:click(['Данные','Получить данные','Из файла','Из текста/CSV'])+`<p>Выберите команду <strong>From Text/CSV</strong>. Она создаёт подключение, на основе которого построим запрос.</p>`,
284:cards([['Load','Загружает результат без перехода к ручной настройке шагов.'],['Transform Data','Открывает редактор, где мы настроим преобразования.']])+result('Нажмите Transform Data / Преобразовать данные.'),
285:bullets(['Слева Queries — список запросов.','В центре Data Preview — результат выбранного шага.','Сверху Ribbon — команды преобразования.','Справа Query Settings — имя и параметры.','Внутри неё Applied Steps — порядок действий.']),
289:flow(['Source','Promoted Headers*','Changed Type*','Преобразования'])+note('* Эти шаги могут быть добавлены автоматически. Важна их функция, а не точное написание или язык названия.'),
290:bullets(['Нажмите Source в Applied Steps и посмотрите исходный этап.','Если заголовки подняты отдельным шагом, на Source они ещё будут обычной строкой.','После просмотра вернитесь на последний шаг. Новые действия добавляйте в конце цепочки.'])+result('Вы просмотрели историю и снова выбрали последний Applied Step.'),
296:cards([['created_at','Date/Time — отдельный столбец даты и времени.'],['Остальные 7 полей','Text: request_id, name, email, direction, source_medium, utm_campaign, status.']])+note('REQ-001 — идентификатор, а не число. Ведущие символы и нули сохраняем.'),
297:click(['created_at','Значок типа','Date/Time'])+`<p>Выберите <strong>Дата/время</strong>, сохранив и дату, и часы с минутами.</p>`+note('Если корректные даты тоже дают Error, проверьте «Изменить тип → С использованием языкового стандарта»: Date/Time и подходящую локаль. wrong_date останется ошибкой при любой локали.'),
300:bullets(['Выделите ячейку Error в created_at строки REQ-003.','В деталях найдите причину, сообщение и исходное значение wrong_date.','Нажимайте область ячейки рядом с Error, если щелчок по ссылке запускает переход к значению.'])+result('Причина — невозможность преобразовать текст в дату; остальные значения и строки доступны.'),
301:cards([['Сегодня','Сохраняем строку REQ-003 и Error в created_at. Не применяем Remove Errors или подмену даты.'],['Следующая тема','Разделяем корректные и проблемные строки, сверяем количество и строим отчёт качества.']]),
302:click(['name','Transform','Format','Trim'])+code('« Иван  Тестов » → «Иван  Тестов»','ПРОБЕЛЫ ПО КРАЯМ')+result('В Applied Steps появился Trimmed Text. Внутри имени пока два пробела.'),
307:click(['source_medium','Home','Split Column','By Delimiter'])+`<p>Выберите разделение <strong>по разделителю</strong>. В следующем окне укажем символ и способ разделения.</p>`,
303:code('« Иван  Тестов »\n        ↓ Trim\n«Иван  Тестов»','ДВА ВНУТРЕННИХ ПРОБЕЛА ОСТАЛИСЬ')+note('Trim работает по краям. Одинарные и двойные пробелы внутри строки он не нормализует.'),
304:click(['Текстовые поля','Transform','Format','Clean'])+bullets(['Выделите name, email, direction, source_medium, utm_campaign, status.','Примените Clean / Очистить: удаляются управляющие символы.','В нашем v1 управляющих символов нет: видимый результат может не измениться.'])+result('Появился шаг Cleaned Text; количество строк не изменилось.'),
305:cards([['Trim','Убирает пробелы по краям: « Иван » → «Иван».'],['Clean','Удаляет управляющие символы, например перенос строки внутри значения.'],['Replace','Отдельно заменяет два обычных пробела внутри имени одним.']]),
308:click(['Split Column','By Delimiter','Custom: |'])+bullets(['Впишите вертикальную черту | — один символ, без пробелов.','Выберите Each occurrence of the delimiter.','В дополнительных параметрах: разделить на столбцы, не на строки. Нажмите OK.'])+result('В учебных значениях ровно один |: ожидаем два столбца и те же 5 строк.'),
310:bullets(['Дважды щёлкните заголовок source_medium.1 → введите utm_source → Enter.','Аналогично source_medium.2 → utm_medium.','Проверьте написание: без пробелов в именах и без повторяющихся заголовков.'])+result('Таблица содержит 9 столбцов; source_medium заменён двумя UTM-полями.'),
313:click(['4 категориальных поля','Transform','Format','lowercase'])+code('utm_source    Telegram → telegram\nutm_medium    SOCIAL → social\nutm_campaign  LESSON07 → lesson07\nstatus        NEW → new','ВЫДЕЛИТЕ ЭТИ ЧЕТЫРЕ СТОЛБЦА')+note('Имя и email в этой практике не переводим в нижний регистр.'),
316:click(['utm_source','Transform','Replace Values'])+code('Value to find:  tg\nReplace with:   telegram\nAdvanced options:\n☑ Match entire cell contents','ТОЧНАЯ ЗАМЕНА КАТЕГОРИИ')+result('Меняется только целое значение tg. Части других названий источников не затрагиваются.'),
318:bullets(['Откройте список фильтра status и проверьте доступные значения.','После Trim и lowercase у v1 остаются new и done.','Если увидели « new » — вернитесь к шагу Trim статуса и исправьте его.'])+note('Просматриваем список; отмените фильтр, чтобы не скрыть строки.'),
319:bullets(['Стрелка в заголовке status → список значений.','Проверьте, нет ли неожиданных категорий и пустот.','Закройте список кнопкой Cancel / Отмена, не снимая флажки.'])+result('Applied Step «Filtered Rows» не добавился. Все 5 строк остаются в запросе.'),
322:code('Source → заголовки → типы\nTrim name → замена двойного пробела → Clean\nSplit source_medium → Rename\nTrim UTM → Trim campaign/status\nlowercase → точная замена tg','НАШ РЕЦЕПТ')+note('Имена шагов зависят от языка Excel. Несколько однотипных действий могут объединяться в один шаг.'),
324:click(['View / Вид','Formula Bar / Строка формул'])+`<p>Выберите простой шаг Trim или lowercase. Посмотрите автоматически созданное выражение M.</p>`+note('Ничего вручную не меняем. Цель — увидеть, что интерфейс сохраняет действия как код.'),
326:click(['Power Query Editor','Home / Главная','Close & Load'])+`<p>Дождитесь загрузки. Если появился выбор места: <strong>Table / Таблица → New worksheet / Новый лист</strong>.</p>`+result('В книге появился результат запроса leads_clean. Ошибка в одной дате не должна исчезнуть из учёта.'),
327:bullets(['Проверьте 9 заголовков и 5 записей.','Найдите REQ-003: проблема даты остаётся видимой. Вид ошибки на листе может отличаться от Error в редакторе.','Если загрузка сообщает о проблемах, откройте запрос и детали. Не удаляйте строку ради красивого результата.'])+result('На лист загружен результат запроса, а не исходный CSV.'),
330:cards([['V1','5 записей · одна неправильная дата.'],['V2','8 записей · три новые заявки · две неправильные даты.']])+note('Новый набор находится в data/leads_dirty_v2.csv. Правила остаются прежними.'),
333:click(['Excel','Data / Данные','Refresh All / Обновить всё'])+bullets(['Дождитесь завершения обновления в Queries & Connections.','Пока идёт загрузка, не закрывайте книгу и не меняйте CSV.','Если результат прежний, проверьте путь Source и факт сохранения CSV.'])+result('После обновления ожидаем 8 строк вместо 5.'),
336:code('REQ-006\nname          Елена\nutm_source    telegram\nutm_medium    social\nutm_campaign  lesson08\nstatus        new','НОВАЯ СТРОКА ИЗ V2')+note('Найдите также REQ-008: wrong_date снова должен стать Error. Новые данные прошли те же правила.'),
337:click(['Data','Queries & Connections','leads_clean','Правой кнопкой → Edit'])+bullets(['Сравните список Applied Steps с кадром до Refresh.','Строк стало 8; шаги Trim, Split, Rename и Replace не создавались заново.','Вернитесь на последний шаг перед проверкой результата.']),
341:flow(['Первый шаг с ошибкой','Предыдущий рабочий шаг','Что ожидалось?','Что изменилось?'])+note('Для пропавшего source_medium исправляют схему источника или согласованно меняют запрос. Удаление случайного шага может скрыть причину.'),
342:cards([['Source','CSV — сохранённые исходные значения.'],['Query','Последовательность правил и подключение.'],['Result','Таблица Excel после выполнения запроса.']]),
345:flow(['UTM → сайт','Форма','Google Sheets','CSV','Power Query','Набор для анализа'])+note('Параллельно форма отправляет событие в GA4. Имена и email не передаются в аналитическое событие.'),
349:checklist(['Импортирован leads_dirty.csv','Запрос назван leads_clean','Типы заданы явно','Error в created_at изучен и сохранён','Trim и Clean применены','source_medium разделён','UTM-поля переименованы','Статус и campaign очищены','Регистр нормализован','tg точно заменён на telegram','Результат загружен: 5 строк','Источник заменён и Refresh дал 8 строк']),
350:checklist(['Исходный CSV','Окно Text/CSV Preview','Power Query Editor целиком','Applied Steps','Типы столбцов','Error в created_at','Детали ошибки','Операция Trim','Настройки Split Column','Два UTM-поля после Split','Операция lowercase','Точная замена tg → telegram','Таблица leads_clean','Команда Refresh All','Новая строка REQ-006 после Refresh']),
351:checklist(['Для чего нужен Power Query?','Чем Source отличается от Query и Result?','Что хранит Applied Steps?','Зачем назначать типы?','Чем Trim отличается от Clean?','Зачем разделять source_medium?','Как работает точная замена?','Почему ошибку даты не скрываем?','Что делает Refresh?','Почему переименование поля ломает шаг?']),
352:cards([['Первый запуск','DIRTY CSV → Applied Steps → результат.'],['Следующий запуск','NEW CSV → те же Applied Steps → новый результат.']])+`<p class="lead">Мы сохранили способ обработки данных, а не только один исправленный файл.</p>`,
353:flow(['Очищенный формат','Можно ли доверять данным?','Контроль качества'])+bullets(['Дубли ID и обязательные поля.','Неизвестные значения и отдельный error query.','Сверка количества строк и контроль Refresh.'])
};
const hints={281:'Выберите файл из распакованной папки data; не v2 и не резервную копию.',282:'Для файлов из комплекта: File Origin 65001 / UTF-8, Delimiter Comma.',283:'Не сохраняйте нечитаемый текст обратно поверх CSV. Исправьте File Origin в окне импорта.',292:'Переименовываем запрос, а не CSV. Имя файла источника остаётся leads_dirty.csv.',295:'Если типы определены автоматически, проверьте Changed Type до новых преобразований. Преобразование уже испорченного ID обратно в Text не восстановит исходные символы.',298:'Одна ошибочная ячейка не означает, что весь запрос перестал работать. Проверьте четыре корректные даты.',302:'Выбирайте заголовок name, а не одну ячейку: команда применяется ко всему столбцу.',307:'Выбираем source_medium. Разделитель CSV — запятая; разделитель внутри этого поля — |.',312:'Для двух соседних полей используйте Shift по заголовкам или Ctrl/⌘. Не выделяйте created_at.',317:'Проверьте Source или CSV: TG остаётся в исходнике. Меняется результат шага.',325:'Открывайте CSV в текстовом редакторе и не сохраняйте изменений. Сравните его с последним шагом запроса.',328:'Имя листа и имя запроса — разные настройки. Здесь оба называем leads_clean.',331:'Заменяем содержимое вручную только для опыта Refresh. Преобразования Power Query исходник не меняли.',338:'Это разбор сценария: рабочий файл сейчас переименовывать не нужно.',340:'Ошибка шага может остановить загрузку целиком; ошибка ячейки относится к конкретному значению.'};
// Дополнительные кадры для действий, которые в исходнике были только визуальными схемами.
const extraShots={274:'Исходный leads_dirty.csv в текстовом редакторе: заголовок и пять строк; видны wrong_date, TG и пробелы.',275:'Тот же CSV крупно: выделены проблемы формата, структуры и даты.',296:'Заголовки восьми столбцов Power Query со значками назначенных типов.',330:'leads_dirty_v2.csv в текстовом редакторе: новые строки REQ-006…REQ-008.',331:'Два файла в редакторе перед заменой: источник leads_dirty.csv и версия leads_dirty_v2.csv.',341:'Диагностика на отдельной копии запроса: первый ошибочный шаг и предыдущий рабочий шаг. Рабочий источник не портить.'};
const stage=id=>{const n=parseInt(id);return n<278?'01 / От заявок к CSV':n<293?'02 / Импорт и редактор':n<302?'03 / Типы и ошибки':n<306?'04 / Очистка текста':n<323?'05 / Структура и категории':n<330?'06 / Запрос и загрузка':n<338?'07 / Новый CSV и Refresh':n<349?'08 / Диагностика и качество':'09 / Практика и итог';};
const deck=[];for(const s of originals){if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
const dark=new Set(['264','267','270','271','289','301','321','329','335','342','345','347','352','353']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>{const body=s.body||custom[s.id]||md(s.text);return `<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${body}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`;}).join('\n');
const sources=[['Замена значений и Match entire cell contents','https://learn.microsoft.com/en-us/power-query/replace-values'],['Ошибки ячейки и шага','https://learn.microsoft.com/en-us/power-query/dealing-with-errors'],['Text.Trim','https://learn.microsoft.com/en-us/powerquery-m/text-trim'],['Text.Clean','https://learn.microsoft.com/en-us/powerquery-m/text-clean'],['Типы данных и локаль','https://learn.microsoft.com/en-us/power-query/data-types'],['Разделение по разделителю','https://learn.microsoft.com/en-us/power-query/split-columns-delimiter']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 8 · Power Query: подготовка данных</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads pq"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 08<small>CSV → правила → Refresh</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(264)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>90 исходных слайдов 264–353 + ${deck.length-90} поясняющих экранов. Буква в номере обозначает дополнение сразу после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика выполняется через интерфейс Excel. Примеры CSV вымышленные. Все учебные файлы и список кадров — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const table=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads pq materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 08 / МАТЕРИАЛЫ</p><h1>Power Query: подготовка данных</h1><p>Воспроизводимая практика: исходный CSV → сохранённые преобразования → новая версия → Refresh.</p>${dl('power-query-lab.zip','Скачать комплект практики')}<div class="cards">${[['leads_dirty.csv','V1 · 5 строк'],['leads_dirty_v2.csv','V2 · 8 строк'],['leads_dirty_v1_backup.csv','Резервная V1']].map(([f,t])=>`<article><h3>${t}</h3><p>${f}</p>${dl('lesson_power_query/data/'+f,'Скачать CSV')}</article>`).join('')}</div><h2>Ожидаемый результат</h2>${cards([['Первая загрузка','5 строк, 9 столбцов. REQ-003 сохраняет ошибку created_at.'],['После Refresh','8 строк, 9 столбцов. Ошибочные даты: REQ-003 и REQ-008.'],['Контроль REQ-006','Елена / telegram / social / lesson08 / new.']])}<p>Это учебные данные, не экспорт настоящих заявок. Готовая книга .xlsx не подменяет практику: студент создаёт запрос сам. Короткие ID не предназначены для отправки в Apps Script темы 7.</p><p><a href="files/lesson_power_query/README.md">Пошаговая памятка и восстановление v1</a> · <a href="SCREENSHOTS.md">Инструкция по скриншотам</a> · <a href="LESSON.md">Структура и уточнения</a></p><h2>Скриншоты · ${shots.length}</h2><p>Сохраните настоящий кадр в shots/ под указанным именем. Затем выполните node build.mjs из папки темы. До съёмки слайды показывают подписанные заглушки.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>Файл</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${table}</tbody></table></div><h2>Источники</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}</main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# ОП.03 · Тема 8 · ${shots.length} кадров\n\nПапка: op03-informacionnye-tehnologii/lessons/08-power-query-cleaning/shots/\n\nСнимать реальные интерфейсы Excel / Power Query, текстового редактора и учебного Google Sheets. ОС и версия Excel должны быть согласованы между кадрами. Поля и названия команд должны читаться. Не заменять интерфейс рисованными макетами. Примеры только вымышленные.\n\nПорядок: распаковать files/power-query-lab.zip; пройти слайды, сохранить кадры; заменить источник v2; Refresh и снять результат. Ошибки даты не удалять. Для демонстрации ошибки схемы использовать отдельную копию запроса и CSV.\n\nНомера 264–353 сохранены. Суффикс a/b обозначает добавленный шаг. Сохранять файлы по точным именам. После добавления PNG выполнить node build.mjs и проверить увеличенный кадр в презентации. Описание фактической съёмки записать в shots/evidence.json.\n\n| Экран | Исходник | Файл | Что снять | Статус |\n|---|---|---|---|---|\n`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/power-query-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'lesson_power_query'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
