import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SHEETS.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||''};});
if(originals.length!==90||originals.some((s,i)=>+s.id!==264+i))throw Error('Нарушен исходный порядок 264–353');
const extras={
272:[{id:'272a',title:'Как выгрузить заявки из темы 7',body:click(['Google Sheets','Лист leads','Файл','Скачать','CSV'])+bullets(['Откройте учебную таблицу темы 7 и выберите лист leads.','Файл → Скачать → Формат CSV (.csv).','Файл сохранится в папку «Загрузки» с именем «GA4 Analytics Lab — Leads - leads.csv». Рабочую таблицу не меняйте.'])+note('Скачивается только текущий лист. Так же в конце темы скачивается очищенный результат.'),shot:'Google Sheets: выбран лист leads, раскрыто Файл → Скачать, пункт CSV.',accent:'Текущий лист и пункт CSV.'},
{id:'272b',title:'Учебная копия отличается от выгрузки',body:cards([['В теме 7','9 полей, отдельные utm_source и utm_medium, полный UUID.'],['В практике 8','8 входных полей: source_medium объединяет source и medium через |. ID сокращены для чтения.']])+note('Для повторяемого упражнения используется готовый leads_dirty.csv. Живые заявки не меняются, REQ-001 в Apps Script не отправляется.') }],
273:[{id:'273a',title:'Распакуйте папку практики',body:dl('data-cleaning-lab.zip','Скачать комплект практики')+bullets(['Распакуйте архив целиком в постоянную папку.','В data лежат leads_dirty.csv, резервная копия v1 и вторая версия v2.','В result в конце занятия сохраняется очищенный CSV.'])+result('Файл data/leads_dirty.csv найден в распакованной папке.'),shot:'Finder: распакованная lesson_data_cleaning, папки data и result; в data видны три CSV.'}],
277:[{id:'277a',title:'Где создаётся таблица',body:bullets(['Откройте Google Таблицы в браузере под своим аккаунтом Google.','Нажмите «Пустая таблица» или плитку с плюсом.','Работаем в новой таблице. Таблицу заявок из темы 7 не меняем.'])+result('Открыт список таблиц, видна кнопка создания пустой таблицы.'),shot:'Главная страница Google Таблиц с кнопкой создания пустой таблицы.'}],
319:[{id:'319a',title:'Уберите фильтр',body:click(['Данные','Удалить фильтр'])+bullets(['После проверки фильтр больше не нужен.','Откройте меню Данные и выберите Удалить фильтр.','Значки фильтра в заголовках пропадут, все строки останутся на месте.'])+result('В заголовках leads_clean нет значков фильтра.'),shot:'Меню Данные с пунктом Удалить фильтр.',accent:'Удалить фильтр.'}],
324:[{id:'324a',title:'Как выглядит режим показа формул',body:bullets(['Во второй строке вместо значений видны формулы.','Столбцы узкие, поэтому в ячейках видно только начало: =ARRAYFORMULA(… Полный текст показывает строка формул выбранной ячейки.','В G2 формулы нет, там значение social: столбец G заполняет формула из F2.','Выключите режим той же командой Вид → Показать → Формулы.'])+result('Режим выключен, в ячейках снова видны значения.'),shot:'Лист leads_clean в режиме показа формул.'}],
330:[{id:'330a',title:'Файлы второй выгрузки',body:dl('lesson_data_cleaning/data/leads_dirty_v2.csv','Скачать v2 отдельно')+bullets(['V1 содержит 5 заявок, v2 — 8, включая новые REQ-006…REQ-008.','Резервная копия leads_dirty_v1_backup.csv нужна, чтобы повторить упражнение с начала.','Файлы в папке data не редактируются.'])+note('Для v2 новая таблица не создаётся. Файл импортируется на лист source той же таблицы.'),shot:'Папка data: leads_dirty.csv, резервная v1 и leads_dirty_v2.csv.'}],
337:[{id:'337a',title:'Сохраните результат в CSV',body:click(['Лист leads_clean','Файл','Скачать','CSV'])+bullets(['Откройте лист leads_clean — скачивается только текущий лист.','Файл сохранится в папку «Загрузки» с именем «leads_cleaning - leads_clean.csv».','Таблица leads_cleaning остаётся на Google Диске вместе с формулами.'])+result('В «Загрузках» появился файл leads_cleaning - leads_clean.csv.'),shot:'Лист leads_clean: раскрыто Файл → Скачать, пункт CSV.'},
{id:'337b',title:'Перенесите CSV в папку result',body:bullets(['Откройте «Загрузки» и найдите leads_cleaning - leads_clean.csv.','Перетащите файл в папку result практики.','Переименуйте его в leads_clean.csv: выделите файл и нажмите Enter (в Windows — F2).'])+result('В result лежит leads_clean.csv: 8 заявок, 9 столбцов, у REQ-003 и REQ-008 значение #VALUE!.'),shot:'Папка result с файлом leads_clean.csv.'}],
340:[{id:'340a',title:'Создайте копию для опыта',body:click(['Файл','Создать копию'])+bullets(['Опыт с изменённым заголовком ставится на копии: рабочая таблица не меняется.','В поле «Название» введите leads_cleaning — копия для проверки структуры.','Нажмите Создать копию. Копия откроется в новой вкладке.'])+result('Открыта копия таблицы с листами source, leads_clean и check.'),shot:'Окно «Копировать файл»: название копии и кнопка Создать копию.'}]
};
const custom={
267:flow(['Источник','Правила','Результат'])+note('Правила записываются один раз. При новой выгрузке они применяются к новым данным.'),
269:cards([['source','Копия CSV. Значения не исправляются вручную.'],['leads_clean','Формулы берут значения из source и очищают их.'],['Результат','Значения, которые формулы выводят на лист leads_clean.']]),
270:cards([['Extract · получить','Импорт CSV на лист source.'],['Transform · преобразовать','Формулы листа leads_clean очищают значения.'],['Load · выдать','Лист leads_clean — готовая таблица для анализа.']])+note('Сокращённо этот процесс называют ETL.'),
271:flow(['CSV','Импорт на source','Лист leads_clean','Дата и #VALUE!','СЖПРОБЕЛЫ / ПЕЧСИМВ','SPLIT / СТРОЧН','tg → telegram','v2 → повторный импорт']),
342:cards([['Source','Лист source — копия CSV.'],['Rules','Формулы второй строки leads_clean.'],['Result','Значения, которые формулы выводят на лист leads_clean.']]),
345:flow(['UTM → сайт','Форма','Google Sheets · leads','CSV','Таблица leads_cleaning','Данные для анализа'])+note('Параллельно форма отправляет событие generate_lead в GA4. Имена и email в аналитическое событие не передаются.'),
349:checklist(['leads_dirty.csv импортирован на лист source','Лист leads_clean с девятью заголовками','Формулы во второй строке всех столбцов','Формат «Дата и время» для created_at','Найдена и прочитана ошибка #VALUE!','Проверен список значений status','v2 импортирован на тот же лист source','Проверены REQ-006 и REQ-008','leads_clean.csv сохранён в result','Лист check с проверкой структуры']),
350:checklist(['Исходный leads_dirty.csv','Окно «Импорт файла» с настройками','Лист source после импорта','Формула в A2 листа leads_clean','Ошибка #VALUE! и её подсказка','Формула SPLIT в F2','Список фильтра status','Режим показа формул','Итоговый leads_clean на v1','leads_clean после импорта v2','Строка REQ-006','Лист check с проверкой структуры']),
351:checklist(['Зачем разделять листы source и leads_clean?','Что делает ARRAYFORMULA?','Чем СЖПРОБЕЛЫ отличается от ПЕЧСИМВ?','Как SPLIT разделяет source_medium?','Почему замена tg стоит после СТРОЧН?','Почему ошибку #VALUE! не скрывают?','Что происходит при повторном импорте на лист source?','Почему перестановка столбцов в CSV опасна?']),
352:cards([['Первая выгрузка','CSV v1 → source → формулы leads_clean → результат.'],['Следующая выгрузка','CSV v2 → source → те же формулы → новый результат.']])+`<p class="lead">Сохранён способ обработки данных: его можно применить к любой следующей выгрузке той же структуры.</p>`
};
const hints={281:'Выберите leads_dirty.csv из распакованной папки data. Файл v2 и резервную копию пока не открывайте.',285:'Если данные легли в один столбец, повторите импорт с разделителем «Запятая».',288:'Формулу можно вводить и с английскими названиями функций: после ввода они отобразятся по-русски. Если таблица не принимает формулу, откройте Файл → Настройки и выберите в поле «Региональные настройки» значение «Россия».',298:'Одна ошибочная ячейка не останавливает остальные формулы. Проверьте четыре корректные даты.',307:'Разделитель CSV — запятая. Разделитель внутри поля source_medium — вертикальная черта |.',317:'Откройте лист source и найдите TG в строке REQ-005.',325:'Лист source не редактируйте: сравнивайте значения глазами.',333:'Перед импортом откройте лист source: «Заменить текущий лист» заменяет тот лист, который открыт.',338:'Это разбор сценария: рабочий файл сейчас менять не нужно.'};
const stage=id=>{const n=parseInt(id);return n<278?'01 / От заявок к CSV':n<288?'02 / Импорт на лист source':n<293?'03 / Лист правил':n<303?'04 / Типы и ошибки':n<306?'05 / Очистка текста':n<323?'06 / Структура и категории':n<330?'07 / Проверка результата':n<338?'08 / Новая выгрузка':n<349?'09 / Структура и качество':'10 / Практика и итог';};
const deck=[];for(const s of originals)deck.push(s,...(extras[s.id]||[]));
const dark=new Set(['264','267','270','271','289','301','321','329','335','342','345','347','352','353']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>{const body=s.body||custom[s.id]||md(s.text);return `<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${body}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`;}).join('\n');
const sources=[['Импорт таблиц и наборов данных','https://support.google.com/docs/answer/40608?hl=ru'],['ARRAYFORMULA','https://support.google.com/docs/answer/3093275?hl=ru'],['СЖПРОБЕЛЫ (TRIM)','https://support.google.com/docs/answer/3094140?hl=ru'],['ПЕЧСИМВ (CLEAN)','https://support.google.com/docs/answer/3267340?hl=ru'],['SPLIT','https://support.google.com/docs/answer/3094136?hl=ru'],['СТРОЧН (LOWER)','https://support.google.com/docs/answer/3094083?hl=ru'],['LET','https://support.google.com/docs/answer/13190535?hl=ru'],['ЗНАЧЕН (VALUE)','https://support.google.com/docs/answer/3094220?hl=ru'],['JOIN','https://support.google.com/docs/answer/3094077?hl=ru']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 8 · Google Таблицы: подготовка данных</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads pq"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 08<small>CSV → формулы → новая выгрузка</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(264)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>90 слайдов 264–353 + ${deck.length-90} поясняющих экранов. Буква в номере обозначает дополнение сразу после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика выполняется в Google Таблицах. Примеры CSV вымышленные. Все учебные файлы и список кадров — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const table=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads pq materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 08 / МАТЕРИАЛЫ</p><h1>Google Таблицы: подготовка данных</h1><p>Воспроизводимая практика: исходный CSV → лист source → формулы leads_clean → новая выгрузка.</p>${dl('data-cleaning-lab.zip','Скачать комплект практики')}<div class="cards">${[['leads_dirty.csv','V1 · 5 строк'],['leads_dirty_v2.csv','V2 · 8 строк'],['leads_dirty_v1_backup.csv','Резервная V1']].map(([f,t])=>`<article><h3>${t}</h3><p>${f}</p>${dl('lesson_data_cleaning/data/'+f,'Скачать CSV')}</article>`).join('')}</div><h2>Ожидаемый результат</h2>${cards([['Первая выгрузка','5 строк, 9 столбцов. У REQ-003 в created_at ошибка #VALUE!.'],['После импорта v2','8 строк, 9 столбцов. Ошибочные даты: REQ-003 и REQ-008.'],['Контроль REQ-006','Елена / telegram / social / lesson08 / new.']])}<p>Все данные вымышленные. Готовая таблица не выдаётся: студент вводит формулы сам. Короткие ID не предназначены для отправки в Apps Script темы 7.</p><p><a href="files/lesson_data_cleaning/README.md">Пошаговая памятка и восстановление v1</a> · <a href="SCREENSHOTS.md">Инструкция по скриншотам</a> · <a href="LESSON.md">Структура и уточнения</a></p><h2>Скриншоты · ${shots.length}</h2><p>Сохраните настоящий кадр в shots/ под указанным именем. Затем выполните node build.mjs из папки темы. Пока кадра нет, слайд показывает подписанную заглушку.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>Файл</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${table}</tbody></table></div><h2>Источники</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}</main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# ОП.03 · Тема 8 · ${shots.length} кадров\n\nПапка: op03-informacionnye-tehnologii/lessons/08-power-query-cleaning/shots/\n\nСнимать настоящие интерфейсы Google Таблиц, Finder и текстового редактора. Все кадры таблицы — в одной таблице leads_cleaning одного аккаунта. Поля и названия команд должны читаться. Не заменять интерфейс рисованными макетами. Примеры только вымышленные.\n\nПорядок: распаковать files/data-cleaning-lab.zip; пройти слайды по порядку; импортировать v2 на лист source и снять результат. Ошибки даты не удалять. Проверку структуры показывать на копии таблицы.\n\nНомера 264–353 сохранены. Суффикс a/b обозначает добавленный шаг. Сохранять файлы по точным именам. После добавления PNG выполнить node build.mjs и проверить увеличенный кадр в презентации. Описание фактической съёмки записать в shots/evidence.json.\n\n| Экран | Исходник | Файл | Что снять | Статус |\n|---|---|---|---|---|\n`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/data-cleaning-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'lesson_data_cleaning'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
