import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return m[2].includes('↓')&&!m[2].includes('├')?flow(m[2].trim().split(/\n?↓\n?/).map(x=>x.trim())):code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||''};});
if(originals.length!==96||originals.some((s,i)=>+s.id!==354+i))throw Error('Нарушен порядок 354–449');
const host='https://ga4-analytics-lab-ivanov.vercel.app';
const url=host+'/guide.html?utm_source=instagram&utm_medium=social&utm_campaign=backend_guide&utm_content=reel01';
const architecture=()=>flow(['Instagram · комментарий','ManyChat · private DM','Кнопка с UTM','Vercel · материал'])+cards([['GA4','События поведения на сайте и контекст перехода.'],['Форма → Apps Script → Sheets','Запись заявки и её UTM; получение строки проверяем отдельно.']]);
const extras={
363:[{id:'363a',title:'Сначала подготовьте обещанный материал',body:dl('instagram-funnel-lab.zip','Скачать комплект')+bullets(['Распакуйте архив. В files/site лежат guide.html и guide.js.','Добавьте оба файла в корень существующего репозитория сайта, рядом с contacts.html.','Откройте guide.html в редакторе: замените G-2CNN55NJF7 на ID своего веб-потока, если используете другой проект.'])+result('На странице уже есть backend-чек-лист и кнопка перехода к заявке. Один Google tag; личные данные в события не передаются.'),shot:'Редактор существующего сайта: guide.html и guide.js рядом с contacts.html; виден ID веб-потока.'},
{id:'363b',title:'Опубликуйте страницу в существующем проекте',body:code('git add guide.html guide.js\ngit commit -m "Add backend guide landing page"\ngit push','В РЕПОЗИТОРИИ УЧЕБНОГО САЙТА')+bullets(['В Vercel откройте связанный проект → Deployments. Дождитесь Ready для нового коммита.','Откройте Production URL + /guide.html. Проверьте материал и переход к /contacts.html.','Если публикации нет или открывается 404, сначала исправьте путь. ManyChat пока не включайте.'])+note('Комплект подготовлен в презентации. Эти действия публикуют его на вашем сайте; сама презентация не меняет внешний проект.'),shot:'Vercel Deployment Ready с новым коммитом и опубликованная /guide.html без 404.'},
{id:'363c',title:'Проверьте метки на обоих страницах',body:code(url,'ТЕСТОВЫЙ URL')+bullets(['Откройте ссылку; нажмите «Перейти к заявке».','На /contacts.html должны остаться все четыре UTM в адресной строке.','guide.js переносит только четыре разрешённые UTM. Обычные ссылки сайта сами этого не делают.'])+result('Форма читает UTM из собственного URL. Потеря меток до формы даст неверный источник заявки.'),shot:'guide.html и contacts.html: на обеих страницах одинаковые четыре UTM в адресной строке.'}],
369:[{id:'369a',title:'Сверьте лимиты своего workspace',body:click(['ManyChat','Settings','Billing / план'])+bullets(['Посмотрите свой тариф и доступные Live Automations.','Для практики нужна одна automation и несколько учебных контактов.','Старые аккаунты и отдельные предложения могут иметь другие условия. Не подключайте платный тариф только ради совпадения экрана.']),shot:'Экран текущего плана ManyChat: название и лимиты; скрыть платёжные реквизиты.'}],
371:[{id:'371a',title:'Выберите доступный способ подключения',body:cards([['Через Instagram','Если предложен этот вариант, войдите в учебный Professional Account. Для базового сценария не требуется отдельно придумывать Facebook Page.'],['Через Meta / Business Suite','Следуйте мастеру: понадобятся связанные ресурсы и необходимые права управления. Выберите именно учебный профиль.']])+note('Названия и набор способов зависят от подключения. Зафиксируйте использованный вариант в журнале кадров.'),shot:'Мастер подключения ManyChat: доступные способы входа, выбран подходящий учебному аккаунту.'}],
373:[{id:'373a',title:'Подтвердите доступ к учебному профилю',body:bullets(['Сверьте имя Instagram-профиля на экране разрешений.','Прочитайте запрашиваемые права на комментарии и сообщения.','Подтвердите подключение и дождитесь возврата в ManyChat.'])+result('Подключение должно завершиться для выбранного аккаунта. Пароли и коды подтверждения в кадр не включаем.'),shot:'Экран разрешений подключения: имя учебного профиля и запрашиваемые права, без секретов.'}],
376:[{id:'376a',title:'Опубликуйте учебный Post или Reel',body:click(['Instagram','Создать +','Публикация / Reel','Поделиться'])+code('Хотите чек-лист «Как начать изучать backend»?\nНапишите ГАЙД в комментариях — получите ссылку в Direct.','ПОДПИСЬ')+bullets(['Добавьте учебное изображение или короткий ролик; включите комментарии.','Опубликуйте и скопируйте ссылку на публикацию.','Сохраните её в отчёт: эту же публикацию выбираем в ManyChat.']),shot:'Опубликованный учебный Post/Reel: подпись с ГАЙД, комментарии доступны; сохранить ссылку.'}],
405:[{id:'405a',title:'Сохраните понятное имя сценария',body:code('IG · Backend Guide · Reel 01','ИМЯ AUTOMATION')+bullets(['Измените название в верхней части редактора.','Сверьте Specific Post, keyword, Public Reply и единственный Private Reply.','Кнопка ведёт на опубликованный guide.html с четырьмя UTM.']),shot:'Flow Builder с названием IG · Backend Guide · Reel 01 и настроенной схемой.'}],
408:[{id:'408a',title:'Проверьте измерение формы до полного теста',body:click(['GA4','Admin','Data streams','Веб-поток','Enhanced measurement'])+bullets(['Проверьте Form interactions, если в следующем опыте ожидаете form_start.','form_start — первый контакт с формой в сеансе; его повторное появление не гарантировано.','Для DebugView подключите сайт через Tag Assistant, как в теме 6. Без режима отладки используйте Realtime.']),shot:'GA4: правильный веб-поток и Form interactions в Enhanced measurement.'}],
416:[{id:'416a',title:'Отдельно проверяем адрес и атрибуцию',body:bullets(['В Tag Assistant подключите полный URL материала с UTM. Откройте GA4 → Admin → DebugView.','Найдите page_view и параметр page_location: адрес должен содержать четыре метки.','В Reports → Acquisition → Traffic acquisition после обработки данных проверьте Session source / medium и Session campaign.'])+note('Realtime может показывать First user source — первый источник пользователя, а не текущий переход. Новая UTM не начинает новый сеанс автоматически.'),shot:'DebugView: page_view → page_location с UTM. Позже отдельный кадр Traffic acquisition с Session source / medium.'}],
418:[{id:'418a',title:'С материала переходим к форме',body:click(['guide.html','Перейти к заявке','contacts.html'])+bullets(['Нажмите кнопку на странице материала: это событие cta_click на сайте.','Сверьте UTM в URL формы. Введите тестовые значения.','Нажатие «Получить материал» внутри Instagram не является нашим сайтом и не отправляет его cta_click.']),shot:'Страница материала с CTA и открывшаяся форма с сохранёнными UTM.'}],
421:[{id:'421a',title:'Свяжите проверку с конкретной заявкой',body:bullets(['Запишите время теста и request_id новой строки.','Сверьте имя учебного теста, направление backend, статус new и три UTM.','Если событие GA4 есть, а строки нет, проверьте Network формы, адрес Apps Script /exec и журнал Executions.'])+note('Текущий generate_lead отправляется при submit, до подтверждения записи Apps Script. Источник истины о сохранении — новая строка Sheets.'),shot:'Одна тестовая строка Sheets: request_id, время, backend, new и три UTM; без чужих персональных данных.'}],
428:[{id:'428a',title:'Три ветки с разными ссылками',body:bullets(['Рабочий базовый сценарий сохраните. В отдельном черновике создайте Private Reply с обычными кнопками Backend / Frontend / Analytics.','Каждую кнопку свяжите с отдельным следующим Instagram Message. Это взаимодействие отличается от Open Website и открывает окно сообщений.','В каждом следующем сообщении добавьте ссылку на соответствующий опубликованный материал.'])+note('Первый Private Reply: один блок. Продолжение запускается нажатием обычной кнопки; автоматическую цепочку без взаимодействия не добавляем.'),shot:'Дополнительный черновик: три обычные кнопки первого DM ведут к трём сообщениям со ссылками.'}],
430:[{id:'430a',title:'Проверка дополнительных веток',body:checklist(['Подготовлены три разных материала, все URL открываются','У каждой ветки своя utm_campaign','UTM переходят к форме из каждого материала','Preview проверяет все три кнопки','Тестовый аккаунт подтвердил нужный текст и ссылку'])+note('В комплекте готов только backend-материал. Frontend и Analytics — расширение задания: сначала создайте страницы, затем публикуйте дополнительную automation.'),shot:'Preview дополнительного сценария: выбранная ветка, её сообщение и соответствующий UTM URL.'}]
};
const custom={
371:click(['ManyChat','Settings','Instagram','Connect'])+result('Запустите мастер подключения учебного Professional Account.'),
415:click(['GA4','Reports','Realtime'])+result('Проверьте активность после перехода на сайт. Используйте веб-поток именно учебного домена.'),

354:flow(['UTM → сайт','Форма → Apps Script','Google Sheets','Очистка в Google Таблицах'])+cards([['Уже умеем','GA4 фиксирует поведение; Sheets хранит заявку. Тема 8 научила очищать данные в Google Таблицах.'],['Новый вопрос','Как привести пользователя с внешней площадки к материалу и форме?']]),
359:flow(['Учебный Reel','Комментарий ГАЙД','Private DM','Получить материал','guide.html'])+result('Одна публикация, одно ключевое слово, один материал. Далее пользователь сам решает перейти к заявке.'),
363:checklist(['Учебный Professional Instagram и отдельный аккаунт для теста','ManyChat workspace с доступной automation','Учебный Post или Reel','Существующий Vercel-сайт с работающей contacts.html','GA4 веб-поток этого сайта','Google Sheets leads и рабочий Apps Script'])+note('Сначала проверяем сайт: обещанный материал должен открываться, а тестовая форма — создавать строку.'),
366:click(['Profile','Menu','Account type and tools','Switch to professional account'])+bullets(['Выберите категорию и Creator либо Business. Завершите мастер.','Названия разделов могут отличаться по версии приложения и языку.'])+result('Проверьте тип аккаунта в настройках, затем Professional dashboard.'),
369:cards([['25','Active Contacts за месяц'],['4','Live Automations'],['1','Пользователь workspace']])+note('Параметры нового Free по официальной справке на 30.09.2026. Фактические ограничения проверяем в своём workspace; возможны другие условия для старых аккаунтов.'),
374:click(['Settings and activity','Messages and story replies','Message controls','Connected tools'])+result('Allow access to messages включён для подключённых инструментов. Путь зависит от версии Instagram.'),
379:click(['Automation','+ New Automation','Start From Scratch','Start with a blank'])+result('Открыт редактор новой automation для подключённого Instagram.'),
381:click(['+ New Trigger','Instagram','User comments on your Post or Reel'])+result('Выбран триггер комментариев к публикации, а не входящих DM.'),
385:code('ГАЙД','KEYWORD')+bullets(['Выберите условие комментария с заданным словом и добавьте ГАЙД.','Для первого опыта используйте именно это слово. Дополнительные варианты добавляйте только после базовой проверки.'])+result('Any comment не выбран. Сохраните правило.'),
387:code('Проверьте Direct — там будет ссылка на материал.','PUBLIC REPLY')+note('Публичный ответ помогает найти DM, но не доказывает его доставку. Проверяем Direct отдельно.'),
388:cards([['Вариант 1','Проверьте Direct — там будет ссылка.'],['Вариант 2','Загляните в личные сообщения за материалом.'],['Вариант 3','Ссылка на чек-лист — в Direct.']]),
392:click(['После Trigger','Instagram','Send Message','Send as a Private Reply'])+result('Первый DM связан с комментарием. Настраиваем один блок текста с кнопкой.'),
393:code('Привет! Вот чек-лист «Как начать изучать backend».\nНажмите «Получить материал», чтобы открыть его на сайте.','ТЕКСТ PRIVATE REPLY'),
394:cards([['Базовый сценарий','Один Private Reply с кнопкой Open Website. Нажатие открывает сайт.'],['Продолжение диалога','Open Website не создаёт opt-in и не открывает 24-часовое окно. Для следующих DM нужен ответ, обычная кнопка или quick reply.']])+note('К первому Private Reply не добавляем автоматические Next Steps, задержки или запрос данных. Дополнительный диалог разберём в ветвлении.'),
402:code(url,'ССЫЛКА НА ОПУБЛИКОВАННЫЙ МАТЕРИАЛ')+result('Если работаете на другом проекте, замените домен. Путь /guide.html должен уже существовать.'),
403:click(['Получить материал','Open Website','Website URL'])+code(url,'ВСТАВИТЬ ПОЛНЫЙ URL')+result('Сохраните кнопку. Проверьте отсутствие пробелов, один знак ? и разделители &.'),
411:code('Проверьте Direct — там будет ссылка на материал.','ОЖИДАЕМЫЙ PUBLIC REPLY')+result('Ответ находится под комментарием тестового аккаунта. Следующий шаг — проверить входящий DM, включая запросы сообщений.'),
416:cards([['В URL','instagram / social / backend_guide / reel01'],['В GA4','Различаем источник первого пользователя и источник сеанса. Проверяем scope выбранного отчёта.']])+note('Realtime подтверждает активность. Проверка page_location с UTM и проверка Session source — разные действия.'),
418:flow(['page_view материала','cta_click на сайте','form_start при взаимодействии','generate_lead при submit'])+note('form_start зависит от Enhanced measurement и первого взаимодействия в сеансе. GA4 видит только сайт, а не все шаги внутри Instagram.'),
419:code('Имя: Тест Instagram Reel01\nEmail: student@example.com\nНаправление: Backend','ТОЛЬКО УЧЕБНЫЕ ДАННЫЕ')+bullets(['Заполните обязательные поля и нажмите отправку один раз.','Ожидаем событие GA4 и отдельно новую строку в leads.','Текст успешной отправки на странице ещё не подтверждает запись в Sheets.']),
420:click(['GA4','Realtime / DebugView','generate_lead'])+note('В текущем сайте событие означает попытку отправки валидной формы. Успешную запись обязательно проверяем следующим шагом в Sheets. Для DebugView нужен режим отладки.'),
422:code('utm_source   = instagram\nutm_medium   = social\nutm_campaign = backend_guide','ОЖИДАЕМ В СТРОКЕ LEADS')+note('Текущая форма и схема Sheets сохраняют три UTM. utm_content=reel01 остаётся в URL и используется GA4; отдельного столбца для него здесь пока нет.'),
423:architecture(),
426:cards([['Trigger','Появился комментарий к выбранной публикации.'],['Condition','Комментарий содержит ГАЙД.'],['Action','Система отправляет Private DM.'],['Переход пользователя','Пользователь нажимает Open Website. Само получение DM сайт не открывает.']]),
432:bullets(['По ограничению Instagram триггер обрабатывает первый комментарий пользователя под конкретной публикацией.','Повторный комментарий этого же пользователя не является новым надёжным тестом.','Для чистого теста используйте другого учебного пользователя или новую учебную публикацию.'])+note('Не начинайте тест с постороннего слова, рассчитывая затем повторить ГАЙД тем же аккаунтом под тем же постом.'),
439:cards([['Другие входы','Входящий DM, ответы и упоминания Story, комментарии Live.'],['Проверяем доступность','Набор триггеров, включая Follow-to-DM, зависит от тарифа, аккаунта и способа подключения.']])+note('В этой практике нужен только Post and Reel Comments Trigger.'),
440:architecture(),
442:flow(['100 просмотров','30 комментариев','24 открытия DM','18 переходов','7 начали форму','4 заявки'])+cards([['Иллюстрация, не измерение','Это условные числа одной группы. GA4 не собирает просмотры Reel и чтение DM как события сайта.'],['Где проверить проблему','До комментария теряем 70%; от перехода к началу формы — 61%. Сначала уточняем сопоставимость счётчиков и период.']]),
443:flow(['Realtime · проверка сигнала','Обработка данных','Explore · исследование'])+note('Исследуем только реально настроенные события сайта. Данные могут появиться позже Realtime; Instagram-этапы потребуют отдельного источника и согласования метрик.'),
445:checklist(['Аккаунт Professional и Instagram Connected','Опубликованный учебный Reel/Post','Trigger, Specific Post, keyword, Public Reply','Private Reply, кнопка и полный UTM URL','Flow целиком, Preview и Live','Комментарий, ответ и входящий DM','Материал и форма с сохранёнными UTM','GA4: переход, события и generate_lead','Sheets: новая строка и три UTM'])+`<p><a href="materials.html">Все кадры по отдельным шагам → Материалы</a></p>`,
447:architecture(),
448:cards([['Instagram','Источник взаимодействия.'],['ManyChat','Правила и автоматический ответ.'],['UTM','Контекст перехода.'],['GA4','Поведение на сайте.'],['Sheets','Заявка и её статус.'],['Тема 8','Очистка данных в Google Таблицах.']])+result('Следующая задача — исследовать, на каких этапах сайта теряются пользователи.')
};
// Шаги, снятые 01.10.2026 на учебном стенде (shots/steps): дополнительные экраны и уточнения под настоящий интерфейс.
const X=(id,title,body,shot)=>({id,title,body,shot});
extras[366]=[
X('366a','Выберите тип «Автор»',bullets(['Мастер спрашивает: «Что из перечисленного описывает вас лучше всего?»','Выберите **Автор** (Creator) и нажмите **Далее**. Тип **Компания** тоже подходит, но для учебного профиля достаточно автора.']),'Мастер переключения: выбран тип «Автор».'),
X('366b','Экран возможностей аккаунта автора',bullets(['Instagram перечисляет, что даёт профессиональный аккаунт: управление профилем, папку «Входящие» для запросов, статистику.','Нажмите **Далее**.']),'Экран описания аккаунта автора с кнопкой Далее.'),
X('366c','Выберите категорию',bullets(['Выберите категорию, например **Личный блог**.','Флажок **Показывать категорию в профиле** можно снять: на работу ManyChat он не влияет.','Нажмите **Готово**.']),'Список категорий: выбран «Личный блог».'),
X('366d','Подтвердите переключение',bullets(['Instagram предупреждает: профиль станет общедоступным, запросы на подписку одобрятся автоматически.','Для учебного профиля это допустимо. Нажмите **Продолжить**.'])+note('Профессиональный аккаунт не бывает закрытым. Поэтому для практики нужен отдельный учебный профиль.'),'Окно «Переключиться на профессиональный аккаунт?» с кнопкой Продолжить.'),
X('366e','Аккаунт автора готов',bullets(['Появится сообщение «Ваш аккаунт автора Instagram готов!».','Нажмите **Готово** и откройте свой профиль.']),'Экран «Ваш аккаунт автора Instagram готов!».')];
extras[369]=[{id:'369a',title:'Где посмотреть свой тариф',body:bullets(['Тарифы ManyChat показывает в конце регистрации, после подключения Instagram (экран 373c).','Позже тариф и лимиты открываются в **Settings → Billing → Subscriptions**.','Внизу левого меню ManyChat виден счётчик **Free contacts limit**, например 0/25.'])+note('Не подключайте платный тариф и пробный период ради практики: учебному сценарию хватает Free.')}];
extras[370]=[X('370a','Выберите канал Instagram',bullets(['После регистрации ManyChat спрашивает: «Where would you like to start?».','Нажмите **Instagram**. Остальные каналы можно подключить позже.']),'ManyChat: экран выбора канала, первая плитка Instagram.')];
extras[371]=[X('371a','Выберите способ подключения',bullets(['Нажмите **See More Options**: под кнопкой Connect Via Meta появятся ещё два способа.','**Connect Via Instagram** подключает профессиональный аккаунт без страницы Facebook. Его и выбираем для учебного профиля.','**Connect Via Meta** и **Meta Business Suite** нужны, если Instagram уже связан со страницей Facebook.']),'Connect Instagram: раскрыты варианты Connect Via Instagram и Meta Business Suite.')];
extras[373]=[
X('373a','Подтвердите доступ к учебному профилю',bullets(['Проверьте имя профиля в строке «Manychat-IG запрашивает доступ к …».','Переключатели доступа к комментариям и сообщениям оставьте включёнными: без них Trigger и Private Reply не работают.','Нажмите **Разрешить**. Окно закроется, вы вернётесь в ManyChat.'])+result('Пароли и коды подтверждения в кадр не включаем.'),'Окно разрешений Instagram для Manychat-IG.'),
X('373b','Instagram подключён, короткая анкета',bullets(['ManyChat пишет «Your Instagram is connected!» и задаёт три вопроса: для кого аккаунт, как он зарабатывает, какие сервисы используете.','Ответы влияют только на подсказки и шаблоны. Для практики подойдут **For myself** и **I don\'t monetize my account**; вопрос о сервисах можно пропустить кнопкой Next.']),'ManyChat: «Your Instagram is connected!» и первый вопрос анкеты.'),
X('373c','Выберите тариф Free',bullets(['На последнем экране регистрации ManyChat показывает тарифы.','Нажмите **Continue with Free**. На этом экране видны лимиты Free: 25 активных контактов в месяц, до 4 активных автоматизаций, 1 пользователь.']),'Экран тарифов: Free и кнопка Continue with Free.'),
X('373d','Стартовая страница ManyChat',bullets(['Откроется Home с готовыми шаблонами. Шаблоны не используем: схему соберём с нуля.','Если появится окно про смену платформы сообщений (Intercom → Braze), нажмите **Maybe Later**.']),'ManyChat Home после регистрации.')];
extras[376]=[
X('376b','Загрузите изображение',bullets(['В меню **Создать** выберите **Публикация**.','Откроется окно «Создание публикации». Нажмите **Выбрать на компьютере** и укажите учебную картинку.']),'Окно создания публикации.'),
X('376c','Покажите изображение целиком',bullets(['Instagram по умолчанию обрезает картинку. Нажмите значок **Расширить** в левом нижнем углу, чтобы картинка вошла целиком.','Нажмите **Далее** на экранах обрезки и фильтров.']),'Редактор: картинка развёрнута целиком.'),
X('376d','Добавьте подпись',code('Хотите чек-лист «Как начать изучать backend»? Напишите ГАЙД в комментариях — получите ссылку в Direct.','ПОДПИСЬ')+bullets(['Вставьте подпись в поле рядом с аватаркой.','Нажмите **Поделиться**.']),'Экран «Новая публикация»: введена подпись с ГАЙД.'),
{id:'376a',title:'Найдите опубликованный пост',body:bullets(['Откройте профиль и нажмите на новую публикацию.','Проверьте подпись и поле «Добавьте комментарий…»: комментарии открыты.','Скопируйте адрес публикации из адресной строки и сохраните для отчёта.']),shot:'Опубликованный учебный Post/Reel: подпись с ГАЙД, комментарии доступны; сохранить ссылку.'}];
extras[379]=[X('379a','Start from a blank canvas',bullets(['Нажмите **Start From Scratch** в правом верхнем углу окна шаблонов.','В меню выберите **Start from a blank canvas**. Пункты Post or Reel comment, Story reply и Direct message открывают мастер с готовым Trigger, их не используем.']),'Меню Start From Scratch: пункт Start from a blank canvas.')];
extras[389]=[X('389a','Сохраняйте панель кнопкой Save',bullets(['Если щёлкнуть по схеме, не нажав Save, ManyChat спросит «Going to leave without saving?».','Нажмите **Keep Editing**, затем **Save** внизу панели. Leave закроет панель без сохранения.']),'Окно Going to leave without saving? с кнопками Keep Editing и Leave.')];
extras[395]=[X('395a','Выберите Open website',bullets(['В окне **Edit Button** ниже названия перечислены действия кнопки.','Нажмите **Open website**: появится поле **Website URL**.','Instagram, AI Step и Perform Actions продолжают диалог внутри Instagram; Condition, Randomizer и Smart Delay на Free недоступны.']),'Edit Button: выбрано действие Open website, поле Website URL пустое.')];
extras[405]=[X('405b','Переименуйте automation',bullets(['Нажмите на значок карандаша рядом с Untitled в верхней строке.','Выделите старое имя, введите новое и нажмите Enter.']),'Поле имени automation в режиме редактирования.'),extras[405][0]];
extras[412]=[
X('412a','Откройте запрос',bullets(['Нажмите на запрос от учебного профиля.','Над сообщением Instagram пишет, что профиль написал вам из-за комментария к публикации.','В веб-версии кнопка «Получить материал» не отображается: её видно только в приложении Instagram.']),'Запрос на переписку: текст Private Reply и кнопки Заблокировать, Удалить, Accept.'),
X('412b','Примите запрос',bullets(['Нажмите **Accept**.','Instagram спросит, в какую папку переместить переписку. Выберите **Общие** или **Основные**.']),'Окно выбора папки: Основные, Общие, Отмена.'),
X('412c','Переписка перенесена',bullets(['Запрос исчез из списка, переписка открыта как обычный чат.','Теперь учебный профиль может отвечать без ограничений запроса.']),'Переписка после принятия запроса.')];
extras[419]=[X('419a','Сообщение об отправке',bullets(['Под кнопкой появится «Заявка отправлена. Проверьте строку в таблице по request_id: REQ-…».','Скопируйте request_id: по нему ищем строку в leads.']),'Форма после отправки с request_id.')];
Object.assign(custom,{
366:click(['Настройки','Тип аккаунта и инструменты','Переключение на профессиональный аккаунт'])+bullets(['Так путь выглядит в веб-версии. В приложении: Профиль → Меню → Тип аккаунта и инструменты.','Мастер задаст три вопроса: тип аккаунта, категорию и подтверждение. Каждый экран разобран дальше.']),
370:click(['app.manychat.com','Sign up','Google или почта'])+bullets(['Зарегистрируйтесь по почте (придёт ссылка для входа) или кнопкой **Google**.','Если появится окно о cookie, выберите **Reject all**.']),
371:click(['Instagram','Connect Instagram','See More Options'])+bullets(['Новый аккаунт ManyChat подключает Instagram прямо в мастере регистрации.','Если аккаунт ManyChat уже был: **Settings → Instagram → Connect**.']),
374:click(['Настройки','Приложения и сайты','Активные'])+bullets(['В веб-версии подключение видно здесь: Manychat-IG с датой авторизации.','Доступ к сообщениям настраивается в приложении: Настройки и действия → Сообщения и ответы на истории → Управление сообщениями → Подключённые инструменты.'])+result('Manychat-IG есть в списке активных. Кнопка Удалить отключает ManyChat от аккаунта.'),
379:click(['Automation','New Automation','Start From Scratch','Start from a blank canvas'])+result('Открыт пустой Flow Builder: блок When… и блок Instagram Send Message.'),
381:click(['+ New Trigger','Instagram','User comments on your Post or Reel'])+result('Выбран триггер комментариев к публикации. Слева откроется мастер из трёх шагов.'),
385:code('гайд','KEYWORD')+bullets(['Шаг 2 из 3: оставьте **Specific Keywords**, нажмите **+ Keyword**, введите слово и нажмите Enter.','ManyChat не различает регистр: ГАЙД, Гайд и гайд — одно слово.','Нажмите **Continue**.'])+result('Any comment не выбран.'),
387:code('Отправили в Direct 👌\nМатериал уже в сообщениях\nПроверьте Direct — там ссылка на материал','PUBLIC REPLY · ТРИ ВАРИАНТА')+bullets(['Шаг 3 из 3: оставьте **Yes, random multiple replies** и замените три английских варианта своими.','Нажмите **Save**.'])+note('Публичный ответ помогает найти DM, но не доказывает его доставку. Direct проверяем отдельно.'),
388:cards([['Вариант 1','Отправили в Direct 👌'],['Вариант 2','Материал уже в сообщениях'],['Вариант 3','Проверьте Direct — там ссылка на материал']])+note('ManyChat выбирает вариант случайно для каждого комментария.'),
392:click(['Блок Instagram · Send Message','Send','As private reply'])+result('В пустой схеме блок сообщения уже соединён с Trigger. Настраиваем в нём один текст с кнопкой.'),
403:click(['Получить материал','Open website','Website URL'])+code(url,'ВСТАВИТЬ ПОЛНЫЙ URL')+bullets(['Нажмите **Done**.','На Free ManyChat предупреждает: перед сайтом пользователь 2 секунды видит страницу переадресации.'])+result('Проверьте отсутствие пробелов, один знак ? и разделители &.'),
411:bullets(['Обновите страницу публикации.','Нажмите **Смотреть все ответы (1)** под комментарием тестового аккаунта.'])+result('Под комментарием один из трёх вариантов Public Reply. Следующий шаг — Direct тестового аккаунта, включая запросы на переписку.'),
419:code('Имя: Тест Инстаграм\nEmail: student9@example.com\nНаправление: Backend','ТОЛЬКО УЧЕБНЫЕ ДАННЫЕ')+bullets(['Заполните поля и нажмите **Отправить заявку** один раз.','Ожидаем событие GA4 и отдельно новую строку в leads.'])});
extras[416]=[X('416b','Подключите Tag Assistant',click(['tagassistant.google.com','Добавить домен','URL материала с UTM','Подключить'])+bullets(['Вставьте полный адрес guide.html с четырьмя метками и нажмите **Подключить**.','Сайт откроется в новом окне с параметром gtm_debug. В Tag Assistant появится «Подключен» и найденный тег G-2CNN55NJF7.','Перезагрузите открывшуюся страницу и прокрутите её: события с флагом debug_mode уйдут в DebugView.'])+note('Код сайта для этого не меняется. После проверки нажмите **Остановить отладку**.'),'Tag Assistant: подключён домен ga4-analytics-lab-ivanov.vercel.app, найден тег G-2CNN55NJF7.'),extras[416][0]];
extras[416][1].body=click(['GA4','Администратор','DebugView','page_view','page_location'])+bullets(['Через минуту после перезагрузки в ленте DebugView появятся page_view, scroll и user_engagement.','Нажмите **page_view** и раскройте параметр **page_location**: в адресе видны четыре UTM.','Источник сеанса проверяйте позже в Reports → Acquisition → Traffic acquisition: Session source / medium и Session campaign.'])+note('Realtime может показывать First user source — первый источник пользователя, а не текущий переход. Новая UTM не начинает новый сеанс автоматически.');
extras[428]=[X('428b','Первое сообщение с тремя кнопками',bullets(['Создайте отдельный черновик: Automation → New Automation → Start From Scratch → Start from a blank canvas. Рабочую automation не меняйте.','Нажмите блок Send Message, введите вопрос и добавьте три кнопки: Backend, Frontend, Analytics.','Для каждой кнопки выберите действие **Instagram**: ManyChat создаст и соединит отдельный блок Send Message #1, #2, #3.'])+note('Справа на схеме видно, что каждая кнопка ведёт к своему сообщению.'),'Черновик ветвления: первое сообщение с кнопками Backend, Frontend, Analytics.'),extras[428][0]];
extras[428][1].body=bullets(['Откройте каждое следующее сообщение стрелкой «›» у кнопки в боковой панели.','Введите текст ветки и добавьте кнопку **Получить материал** → **Open website**.','В ссылке меняется только utm_campaign: backend_guide, frontend_guide, analytics_guide.','Блоки веток ManyChat ставит друг на друга. Перетащите их за заголовок, чтобы схема читалась сверху вниз.'])+note('Черновик не публикуется (DRAFT). На учебном стенде все три кнопки ведут на guide.html с разными метками: страниц frontend и analytics пока нет.');
const hints={382:'На тарифе Free доступен только Specific Post or Reel: All Posts и Next Post помечены UPGRADE.',406:'Preview проверяет сообщение и ссылку, но не заменяет реальный тест триггера комментариев.',408:'Публикуйте только после проверки материала, UTM и Preview. После правок используйте Update.',409:'Тестовый аккаунт ещё не комментировал эту публикацию. Запишите время начала опыта.',430:'Для разных материалов нужны реальные опубликованные страницы. Смена utm_campaign сама по себе не меняет содержимое сайта.',444:'Explore исследует события сайта. Instagram traffic — условие отбора по источнику, а не отдельное событие Instagram в GA4.'};
const extraShots={376:'Instagram: открыто меню Создать с пунктом Публикация.',402:'Полный URL материала с четырьмя UTM в редакторе, без сокращателя ссылок.'};
const stage=id=>{const n=parseInt(id);return n<363?'01 / Зачем нужна автоматизация':n<376?'02 / Подготовка стенда':n<390?'03 / Публикация и Trigger':n<406?'04 / Private Reply и UTM':n<415?'05 / Публикация и тест':n<423?'06 / GA4 и реальная заявка':n<432?'07 / Архитектура и ветвление':n<440?'08 / Диагностика':'09 / Практика и следующий шаг';};
const deck=[];for(const s of originals){if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
const dark=new Set(['354','357','358','376','380','389','400','404','406','417','420','432','436','442','449','454','455','456','458']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>`<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${s.body||custom[s.id]||md(s.text)}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`).join('\n');
const sources=[['ManyChat: комментарии и ограничения Private Reply','https://help.manychat.com/hc/en-us/articles/14281316989724-Instagram-Post-and-Reel-Comments-Trigger'],['Подключение Instagram','https://help.manychat.com/hc/en-us/articles/14281290924444-How-to-connect-Instagram-to-Manychat'],['Free plan','https://help.manychat.com/hc/en-us/articles/25800197498652-Free-plan'],['Диагностика подключения','https://help.manychat.com/hc/en-us/articles/14281291094428-Can-t-connect-Instagram-to-Manychat'],['GA4 Enhanced measurement','https://support.google.com/analytics/answer/9216061?hl=en'],['Области действия источников GA4','https://support.google.com/analytics/answer/11080067?hl=en'],['UTM и сеанс','https://support.google.com/analytics/answer/11242841?hl=en']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 9 · Instagram → ManyChat → заявка</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads automation"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 09<small>Комментарий → DM → сайт → заявка</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(354)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>96 исходных слайдов 354–449 + ${deck.length-96} поясняющих экранов. Буква — дополнение после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика выполняется на учебных аккаунтах. Проверено по официальной документации 30.09.2026. Реальные кадры добавляются после съёмки. Список кадров и комплект — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const table=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads automation materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 09 / МАТЕРИАЛЫ</p><h1>От комментария до заявки</h1><p>${deck.length} экранов: 96 исходных слайдов 354–449 и ${deck.length-96} промежуточных шагов.</p>${dl('instagram-funnel-lab.zip','Скачать комплект практики')}<p><a href="files/README.md">Порядок практики</a> · <a href="SCREENSHOTS.md">Задание для съёмки / Claude</a> · <a href="LESSON.md">Уточнения к исходнику</a></p>${cards([['Сайт','Готовые guide.html и guide.js: материал, тег GA4, CTA и перенос UTM. Публикуются отдельно в существующем проекте.'],['ManyChat','Тексты Post, Public Reply, Private Reply и ссылка с четырьмя UTM в messages.md.'],['Проверка','TESTS.md: маршрут от первого комментария до новой строки и диагностика.']])}<h2>Кадры · ${shots.length}</h2><p>Исходный номер — постоянная ссылка на слайд. Буква обозначает промежуточный шаг. Каждый PNG заменяет свою заглушку после node build.mjs.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>Файл</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${table}</tbody></table></div><h2>Официальная документация</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}</main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# ОП.03 · тема 9 · Instagram и ManyChat · ${shots.length} кадров

Задание для Claude: пройди учебный сценарий по презентации последовательно. Снимай настоящие интерфейсы Instagram, ManyChat, сайта, Vercel, GA4 и Google Sheets. Не подменяй их нарисованными экранами.

Сохраняй PNG в op03-informacionnye-tehnologii/lessons/09-instagram-manychat/shots/ по точным именам ниже. Ссылки на слайды: index.html#354, index.html#363a и т. д. Колонка «экран» — позиция в презентации; «исходник» — постоянный номер из текста.

Подготовка: прочитай files/README.md, опубликуй guide.html и guide.js в существующем учебном сайте; сверь ID GA4. Используй учебный Professional Instagram и отдельный тестовый аккаунт. Настрой одну публикацию, слово ГАЙД и один Private Reply с Open Website. Все изменения аккаунтов и публикации выполняй в согласованном учебном стенде. Пароли, коды входа, чужие переписки и персональные данные в кадр не включай.

До первого комментария проверь Live и работающую ссылку. Для этой публикации тестовый пользователь ещё не должен был комментировать. Один тест: комментарий → DM → материал → кнопка на сайте → форма → событие GA4 → новая строка Sheets. Не заменяй проверку сохранения заявки одним событием generate_lead.

Кадры дополнительных веток 428a/430a нужны только после выполнения дополнительного задания; остальные снимаются по основному маршруту. Для широких интерфейсов желательно 1600×1000 или больше, текст читаемый; мобильные экраны сохраняй вертикально. Можно делать несколько кадров в один PNG, если шаг явно просит сравнить два состояния. В evidence.json записывай время, систему, фактический результат и имя файла. Не отмечай captured до сохранения реального кадра.

После добавления PNG выполни node build.mjs в папке темы. Открой каждый кадр в увеличении, проверь соответствие шага и отсутствие секретов.

| Экран | Исходник | PNG | Что снять | Статус |
|---|---|---|---|---|
`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/instagram-funnel-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'site','README.md','messages.md','TESTS.md'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
