import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return m[2].includes('↓')&&!m[2].includes('├')?flow(m[2].trim().split(/\n?↓\n?/).map(x=>x.trim())):code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||'',remark:p['Примечание']||''};});
if(originals.length!==137||originals.some((s,i)=>+s.id!==735+i))throw Error('Нарушен порядок 735–871');
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${inline(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
import {content} from './content.mjs';
const {extras,custom,hints,extraShots,titles,stage,dark,sources,schema}=content({cards,flow,code,note,result,bullets,checklist,click,table,dl,originals});
const deck=[];for(const s of originals){if(titles[s.id])s.title=titles[s.id];if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>`<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${s.body||custom[s.id]||md(s.text)}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`).join('\n');
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 11 · HubSpot CRM</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads crm"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 11<small>Contact ↔ Deal → процесс</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(735)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>137 исходных слайдов 735–871 + ${deck.length-137} поясняющих экранов. Буква — дополнение после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика продолжает ресурс предыдущих тем. Числа примеров условные. Проверено по официальной документации 08.10.2026. Реальные кадры добавляются после съёмки. Список кадров и комплект — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const shotTable=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads crm materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 11 / МАТЕРИАЛЫ</p><h1>HubSpot CRM: от заявки к процессу</h1><p>${deck.length} экранов: все 137 исходных слайдов 735–871 и ${deck.length-137} промежуточных шагов.</p>${dl('hubspot-crm-lab.zip','Скачать комплект практики')}<p><a href="files/README.md">Порядок работы</a> · <a href="files/sheets-preparation.md">Формулы Google Таблиц</a> · <a href="files/reconciliation.md">Отчёт сверки</a> · <a href="SCREENSHOTS.md">Скриншоты / инструкция Claude</a></p>${cards([['Основной импорт','crm_import.csv: три заявки. Contacts create/update по Email; Deals create new.'],['Повторное обращение','repeat_contact.csv: только REQ-101. Старую заявку REQ-001 повторно не загружаем.'],['Подготовка данных','leads_clean-demo.csv и формулы в Sheets; полный Request ID, согласованные Stage и даты.']])}<p>${dl('crm_import.csv','Основной CSV')} ${dl('repeat_contact.csv','Вторая заявка Ивана')} ${dl('leads_clean-demo.csv','Исходные учебные строки')} ${dl('property-map.csv','Карта полей')}</p><h2>Сопоставление 12 столбцов</h2>${table(['CSV','Object','Property'],schema)}<h2>Проверка результата</h2><p>После первого импорта на чистом учебном стенде: три Contacts и три Deals. Иван создан вручную до импорта; повторный Contact не нужен. После контрольного импорта: три Contacts и четыре Deals, два из которых связаны с Иваном. Счётчики импорта сверяем по фактическим Record ID.</p><h2>Скриншоты · ${shots.length}</h2><p>Снимайте реальные экраны в порядке урока. Сохраните PNG в shots/ и выполните node build.mjs. До съёмки отображаются подписанные заглушки.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>PNG</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${shotTable}</tbody></table></div><h2>Официальная документация</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}<p>Проверено 08.10.2026. Реальный интерфейс зависит от аккаунта и прав; внешний импорт в рамках подготовки презентации не выполнялся.</p></main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'deck.json'),JSON.stringify(deck.map((s,i)=>({position:i+1,id:s.id,title:s.title,stage:stage(s.id),screenshot:s.shot?`shots/${s.id}-shot.png`:null})),null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# Тема 11 · HubSpot CRM · ${shots.length} кадров

## Задание для Claude

Открой op03-informacionnye-tehnologii/lessons/11-hubspot-crm/index.html и выполняй шаги последовательно. Сохраняй настоящие PNG в op03-informacionnye-tehnologii/lessons/11-hubspot-crm/shots/ по именам таблицы. «Экран» — позиция, «исходник» — постоянный номер слайда; ссылка index.html#735 или #818a. Соседние кадры могут показывать разные части одного экрана, но подписи и значения должны читаться.

До съёмки прочитай files/README.md, sheets-preparation.md и reconciliation.md. Работай в учебном аккаунте с вымышленными example.com. Не имитируй интерфейс и успешные результаты. Если шаг недоступен, сними реальное состояние и запиши причину. Регистрацию и подтверждение входа выполняет владелец аккаунта; пароли/коды не включай в кадр.

Порядок: Account → Contact → один существующий учебный Pipeline Applications → пять стадий → шесть Deal Properties → Google Sheets → CSV → Advanced import Contacts + Deals → mapping → проверка → Stage/Note/Task → Saved View → новая заявка прежнего Contact.

Первый файл crm_import.csv содержит REQ-001/002/003. Иван уже создан вручную. Contacts сопоставляй по Email; Deals создавай новыми. В mapping обязательно включи pipeline → Deal → Pipeline, created_at → Application Created At. Формат YMD, часовой пояс Europe/Moscow для файлов комплекта. Request ID — обычное текстовое поле, оно не предотвращает дубли при повторном Create new.

Не загружай полный файл снова ради кадра. При ошибках сначала сверь созданные Deal и Record ID; исправление созданных — через update, создание — только отсутствующих. На слайде 863 используй отдельный repeat_contact.csv с одной строкой REQ-101. После него один Contact Ивана связан с двумя Deals. Не отправляй письма, не подключай рассылки и не приглашай пользователей ради снимков. Notes явно помечены как учебная имитация.

Снимай состояния в момент шага: начальная доска — до переноса, Done/Rejected — после. Смена Stage не обновляет Sheets и не завершает Task. Права рабочего аккаунта и рабочий Pipeline не меняй. Если есть реальные данные, используй учебный стенд и не включай их в кадр.

Рекомендуемый размер — от 1600×1000, читаемый масштаб. Если нужны два состояния, допустим составной кадр без изменения данных. В evidence.json укажи время, имя PNG, объект/URL без секретов, фактическое состояние. После добавления кадров: node build.mjs, проверить manifest и увеличение каждого PNG.

| Экран | Исходник | Имя PNG | Что снять | Статус |
|---|---|---|---|---|
`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/hubspot-crm-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X',zip,'README.md','sheets-preparation.md','crm_import.csv','repeat_contact.csv','leads_clean-demo.csv','property-map.csv','reconciliation.md'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,extras:deck.length-originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
