// Rebuild the static presentation and screenshot brief from SOURCE.md.
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const inline = s => esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const p = s => `<p>${inline(s)}</p>`;
const callout = s => `<aside class="lab-note">${inline(s)}</aside>`;
const list = a => `<ul class="lab-list">${a.map(t=>`<li>${inline(t)}</li>`).join('')}</ul>`;
const code = (s,label='ПРИМЕР') => `<figure class="lab-code"><figcaption>${label}</figcaption><pre><code>${esc(s)}</code></pre></figure>`;
const flow = (a,cls='') => `<ol class="lab-flow ${cls}">${a.map((x,i)=>`<li class="reveal"><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x.split('|')[0])}</b><span>${inline(x.split('|')[1]||'')}</span></li>`).join('')}</ol>`;
const cards = a => `<div class="lab-cards">${a.map(([label,title,text])=>`<article class="reveal"><small>${label}</small><h3>${inline(title)}</h3><p>${inline(text)}</p></article>`).join('')}</div>`;
const tree = code('ga4-analytics-lab/\n├── index.html\n├── about.html\n├── contacts.html\n├── css/\n│   └── style.css\n├── js/\n│   └── script.js\n└── README.md','СТРУКТУРА ПРОЕКТА');
const C = {};
C[20]=p('На прошлом занятии мы создали **Analytics Account**, **GA4 Property** и **Web Data Stream**. Для знакомства указали `bytecamp.ru` и получили Measurement ID.')+flow(['GA4 Property|создан ✓','Web Data Stream|создан ✓','bytecamp.ru|временный учебный URL','G-XXXXXXXXXX|получен ✓'])+callout('Теперь подключим собственный сайт, данные которого будем анализировать.');
C[21]=p('Каждый студент работает со своим сайтом: изменяет код, устанавливает Google Tag, проверяет события и экспериментирует с UTM.')+cards([['РАБОЧИЙ ПРОЕКТ','bytecamp.ru','Настоящий сайт и его аналитику не изменяем.'],['УЧЕБНЫЙ ПРОЕКТ','student-project.vercel.app','Своя копия кода, собственная публикация и учебный поток GA4.']]);
C[22]=p('Пройдём путь от шаблона до первого посещения в Realtime. Сайт опубликуем дважды: сначала без тега, затем с аналитикой.')+flow(['Шаблон|готовые HTML / CSS / JS','GitHub|своя копия','VS Code|локальный проект','Vercel|первая публикация','Публичный URL|адрес сайта','Web Stream|обновление адреса','Google Tag|код на всех страницах','Vercel|повторная публикация','GA4 Realtime|проверка событий'],'roadmap');
C[23]=p('Откройте шаблон учебного проекта. Он уже содержит HTML, CSS и JavaScript.')+'<div class="template-link"><small>ШАБЛОН GA4-LAB</small><strong><a href="https://github.com/MaximBytecamp/ga4-analytics-lab" target="_blank" rel="noopener noreferrer">MaximBytecamp / ga4-analytics-lab ↗</a></strong><span>Нажмите Use this template, чтобы создать свою копию.</span></div>'+callout('Сегодня работаем с готовым сайтом. Его структура — на следующем слайде.');
C[24]=p('Три страницы, один файл стилей и один файл JavaScript — основа дальнейшей практики.')+`<div class="lab-split">${tree}<div>${list(['`index.html` — главная.','`about.html` — о проекте.','`contacts.html` — контакты.','`css/style.css` — стили.','`js/script.js` — поведение сайта.'])}${p('Дальше добавим клики, формы, события, воронки и Google Tag Manager.')}</div></div>`;
C[25]=p('Каждому студенту нужен собственный GitHub-репозиторий.')+flow(['Use this template|на странице шаблона','Create a new repository|создать свою копию'])+callout('Изменения отправляем в свою копию, а не в репозиторий преподавателя.');
C[26]=p('Укажите владельца — ваш GitHub-аккаунт — и название проекта.')+code('ga4-analytics-lab\nили\nga4-analytics-lab-ivanov','REPOSITORY NAME')+p('Нажмите **Create repository**.');
C[27]=p('Проверьте владельца в адресе нового репозитория.')+code('github.com/ВАШ-ЛОГИН/ga4-analytics-lab','ВАША КОПИЯ')+callout('Именно эту копию подключим к Vercel.');
C[28]=p('В Visual Studio Code откройте **Source Control → Clone Repository**. Другой путь — команда **Git: Clone** в палитре команд.')+list(['Выберите **Clone from GitHub**, если предлагается.','При необходимости войдите в GitHub.','Найдите свой репозиторий.'])+callout('Работаем через интерфейс VS Code. Терминал для клонирования не нужен.');
C[29]=p('В списке GitHub repositories выберите свою копию `ga4-analytics-lab`.')+list(['Укажите папку на компьютере.','Дождитесь клонирования.','Нажмите **Open**, чтобы открыть проект.']);
C[30]=p('В Explorer должны появиться все файлы проекта.')+code('index.html\nabout.html\ncontacts.html\ncss/\njs/\nREADME.md','EXPLORER')+p('Откройте `index.html`. Пока ничего не изменяем.');
C[31]=p('Сначала проверьте сайт на локальном веб-сервере. Например, с расширением Live Server: правый клик по `index.html` → **Open with Live Server**.')+code('http://127.0.0.1:5500/\nили http://localhost:5500/','ЛОКАЛЬНЫЙ АДРЕС')+callout('Порт может отличаться. Проверьте главную страницу, стили и переходы.');
C[32]=p('Localhost доступен на вашем компьютере. Для совместной проверки и UTM-ссылок опубликуем сайт в интернете.')+cards([['РАЗРАБОТКА','localhost','Адрес локального сервера на компьютере студента.'],['ПУБЛИКАЦИЯ','Vercel','Публичный HTTPS-адрес, который можно открыть с другого устройства.']])+callout('GA4 может получать события и с localhost при установленном теге. В этой практике проверяем публичный сайт.');
C[33]=p('Откройте Vercel. Он публикует сайт из GitHub-репозитория.')+'<a class="lab-link" href="https://vercel.com" target="_blank" rel="noopener noreferrer">vercel.com ↗</a>'+p('Нажмите **Sign Up** или **Log In**.');
C[34]=p('Выберите вход через **GitHub** и подключите нужный репозиторий.')+list(['Используйте аккаунт, которому принадлежит учебная копия.','Предоставьте Vercel доступ к этому репозиторию.'])+callout('Вход через GitHub и доступ к репозиториям могут запрашиваться отдельными шагами.');
C[35]=p('GitHub хранит исходный код и его историю. Vercel публикует выбранную версию проекта.')+flow(['VS Code|редактирование','GitHub|история изменений','Vercel|развёртывание','Internet|готовый сайт'])+callout('Push в production-ветку запускает обновление сайта. В этой практике используем main.');
C[36]=p('В Dashboard откройте **Add New → Project**.')+code('Add New → Project','VERCEL DASHBOARD')+p('В другой версии интерфейса кнопка может называться **New Project**.');
C[37]=p('В разделе **Import Git Repository** найдите свою копию `ga4-analytics-lab` и нажмите **Import**.')+callout('Если копии нет в списке, проверьте аккаунт GitHub и доступ Vercel к этому репозиторию.');
C[38]=p('В **Configure Project** проверьте **Project Name**.')+code('ga4-analytics-lab-ivanov','ПРИМЕР ИМЕНИ')+p('Можно оставить `ga4-analytics-lab` или добавить фамилию. Имя участвует в формировании адреса; точный домен проверим после публикации.');
C[39]=p('Проект состоит из HTML, CSS и JavaScript. Фреймворк здесь не используется.')+code('Framework Preset → Other','CONFIGURE PROJECT')+callout('Выберите Other в раскрывающемся списке.');
C[40]=p('HTML-файлы уже готовы к публикации. У проекта нет сборки React, Next.js или Vite.')+code('Framework Preset: Other\nBuild Command: пусто\nOutput Directory: .','BUILD AND OUTPUT SETTINGS')+callout('Чтобы явно пропустить сборку, включите Override у Build Command и оставьте поле пустым. Папки public в этом шаблоне нет.');
C[41]=p('`index.html` находится в корне репозитория. Оставьте корневой **Root Directory**.')+code('/\n├── index.html\n├── about.html\n├── contacts.html\n├── css/\n└── js/','ROOT DIRECTORY: ./')+callout('Не выбирайте css или js: в них нет главной страницы сайта.');
C[42]=p('Настройки готовы. Нажмите **Deploy** и дождитесь завершения публикации.')+flow(['GitHub|готовые файлы','Deploy|публикация','Vercel|первая версия'])+callout('Первая версия пока не содержит Google Tag.');
C[43]=p('После успешного Deployment откройте назначенный публичный адрес.')+code('https://ga4-analytics-lab-ivanov.vercel.app','ПРИМЕР, ВАШ АДРЕС БУДЕТ ДРУГИМ')+callout('Сохраните production-домен проекта. Не подменяйте его адресом отдельного Preview Deployment.');
C[44]=p('Нажмите **Visit** и проверьте сайт на домене `.vercel.app`.')+list(['Главная страница загружается.','Стили применились.','Ссылки открывают About и Contacts.','Публичный адрес доступен с другого устройства.']);
C[45]=p('В учебном Web Data Stream пока указан `bytecamp.ru`. Теперь у нас есть собственный публичный сайт.')+flow(['bytecamp.ru|старый учебный адрес','Заменяем URL|в существующем потоке','…vercel.app|публичный адрес студента'])+callout('Сначала убедитесь, что открыт именно учебный ресурс GA4.');
C[46]=p('Продолжаем работать с существующим учебным Web Data Stream: обновляем URL и название.')+'<div class="identity"><div><small>СОХРАНЯЕТСЯ</small><strong>G-XXXXXXXXXX</strong><span>Measurement ID того же потока</span></div><div><small>ИЗМЕНЯЕТСЯ</small><strong>Website URL</strong><span>bytecamp.ru → ваш-проект.vercel.app</span></div></div>'+callout('Новый поток не создаём, старый не удаляем. URL в настройках сам по себе не устанавливает тег и не ограничивает домены сбора.');
C[47]=p('В учебном ресурсе Google Analytics откройте:')+flow(['Admin|администрирование','Data collection and modification|сбор и изменение данных','Data streams|потоки данных']);
C[48]=p('Найдите Web Data Stream, который создали на прошлом занятии. В Website URL пока указан `bytecamp.ru`.')+callout('Откройте поток внутри своего учебного ресурса.');
C[49]=p('В **Web stream details** найдите значок карандаша в верхней части сведений о потоке.')+code('Web stream details → Edit','РЕДАКТИРОВАНИЕ')+p('Нажмите значок, чтобы изменить URL и название.');
C[50]=p('Выберите протокол **https://** и замените домен сайта.')+code('ga4-analytics-lab-ivanov.vercel.app','WEBSITE URL — ТОЛЬКО ДОМЕН')+list(['Не повторяйте `https://` в поле домена.','Не добавляйте UTM-параметры.','Не указывайте `/about.html` или другую страницу.']);
C[51]=p('Обновите **Stream name**, чтобы название соответствовало вашему сайту.')+code('GA4 Analytics Lab — Ivanov\nили Student Analytics Website','НАЗВАНИЕ ПОТОКА')+callout('Название помогает отличать потоки внутри GA4.');
C[52]=p('Проверьте новый домен, протокол и название. Нажмите **Update stream**.')+callout('После сохранения откройте сведения о потоке и сравните URL и Measurement ID.');
C[53]=p('URL и название обновились. **Measurement ID остался прежним**, потому что мы редактировали тот же поток.')+code('G-XXXXXXXXXX','ТОТ ЖЕ ИДЕНТИФИКАТОР')+p('Его будем использовать при подключении сайта.');
C[54]=p('Замена URL относится только к учебному GA4-ресурсу.')+cards([['РАБОЧАЯ АНАЛИТИКА','Production ByteCamp','URL настоящего рабочего потока bytecamp.ru не изменяем.'],['УЧЕБНАЯ АНАЛИТИКА','Поток студента','Обновляем адрес в потоке, который создали на прошлом занятии.']])+callout('Если открыт рабочий ресурс, переключитесь на учебный. Для другого реального проекта настройка выбирается отдельно.');
C[55]=p('Опубликованный сайт, ресурс, поток и Measurement ID готовы. Осталось добавить на сайт код передачи данных.')+'<div class="gap-link"><b>VERCEL SITE</b><span>× × ×<small>тег ещё не установлен</small></span><b>GA4</b></div>'+callout('Google Tag свяжет браузер посетителя с нужным потоком GA4.');
C[56]=p('В сведениях о потоке найдите раздел **Google tag**.')+code('Google tag → View tag instructions','WEB STREAM DETAILS')+p('Откройте инструкции установки.');
C[57]=p('У нас есть доступ к HTML, поэтому выберите **Install manually**.')+callout('Google покажет код тега для выбранного Measurement ID.');
C[58]=p('Нажмите **Copy** и скопируйте весь блок Google Tag.')+code('<!-- Google tag (gtag.js) -->\n… полный код из вашего GA4 …','НАЧАЛО БЛОКА')+callout('Используйте код из своего GA4. G-XXXXXXXXXX в презентации — условный образец.');
C[59]=p('Вернитесь в VS Code, откройте `index.html` и найдите начало секции `<head>`.')+code('<html lang="ru">\n<head>\n    <!-- сюда добавим Google Tag -->','INDEX.HTML')+p('Тег разместим сразу после открывающего `<head>`.');
C[60]=p('Вставьте полный код Google Tag из GA4 в указанное место.')+code('<!DOCTYPE html>\n<html lang="ru">\n<head>\n    <!-- Google Tag из вашего GA4 -->\n    <meta charset="UTF-8">\n    <title>GA4 Analytics Lab</title>\n</head>','СХЕМА РАЗМЕЩЕНИЯ — НЕ КОД ТЕГА')+callout('Комментарий заменяется настоящим блоком Google Tag.');
C[61]=p('Добавьте **тот же тег** сразу после `<head>` во все три страницы.')+list(['`index.html`','`about.html`','`contacts.html`'])+callout('По одному экземпляру тега на страницу. Иначе часть страниц останется без измерения или события могут дублироваться.');
C[62]=p('Сохраните все изменённые HTML-файлы. Локальная версия содержит тег, опубликованная ещё не обновлена.')+flow(['VS Code|новая версия + tag ✓','GitHub|предыдущая версия','Vercel|предыдущая версия'])+callout('Дальше создаём commit и отправляем его в GitHub.');
C[63]=p('Откройте **Source Control** и проверьте изменения в каждом HTML-файле.')+list(['`index.html`','`about.html`','`contacts.html`'])+callout('В diff должен появиться Google Tag. Добавьте файлы в Staged Changes кнопкой + перед коммитом.');
C[64]=p('Введите сообщение коммита и нажмите **Commit**.')+code('Add GA4 Google tag','COMMIT MESSAGE')+p('После этого выполните **Sync Changes** или **Push**, чтобы отправить commit в GitHub.')+callout('Commit сохраняет версию локально. Push передаёт её на GitHub.');
C[65]=p('После Push в production-ветку Vercel запускает новый Deployment.')+flow(['VS Code|Commit → Push','GitHub|новая версия main','Vercel|автоматический Deploy','Production|сайт с Google Tag'])+callout('Публикация закончится после успешного Deployment. Сам Push ещё не означает, что сайт обновился.');
C[66]=p('Откройте свой Vercel Project → **Deployments**.')+list(['Последний Deployment связан с нужным commit.','Сообщение: `Add GA4 Google tag`.','Дождитесь успешного состояния **Ready**.'])+callout('Проверьте production-ветку и назначение Production.');
C[67]=p('Откройте постоянный **Production URL** своего проекта.')+code('https://ваш-проект.vercel.app','ОПУБЛИКОВАННЫЙ САЙТ')+p('Обновите страницу. Эта версия теперь должна содержать Google Tag. Итоговую проверку проводим на публичном сайте.');
C[68]=p('В **View tag instructions** найдите **Test your website**. Укажите полный адрес и нажмите **Test**.')+code('https://ga4-analytics-lab-ivanov.vercel.app','ЗДЕСЬ НУЖЕН ПОЛНЫЙ HTTPS-АДРЕС')+callout('Название и расположение проверки могут отличаться. Следующий шаг в любом случае — проверка данных в Realtime.');
C[69]=p('Обнаружение тега подтверждает установку кода. Теперь проверим, что события действительно поступают.')+flow(['Google Tag|обнаружен ✓','Данные|нужна проверка','Realtime|смотрим события']);
C[70]=p('Откройте опубликованный сайт и выполните несколько переходов.')+flow(['Home|главная','About|о проекте','Contacts|контакты','Home|вернуться'])+callout('Обновите одну страницу. Так мы создаём реальные просмотры.');
C[71]=p('При открытии страницы браузер получает HTML с Vercel, загружает Google Tag и отправляет событие в GA4.')+flow(['Browser|открывает страницу','Vercel|отдаёт HTML','Google Tag|передаёт событие','GA4|получает page_view']);
C[72]=p('В Google Analytics откройте **Reports → Realtime**.')+code('Reports → Realtime','ОТЧЁТ В РЕАЛЬНОМ ВРЕМЕНИ')+callout('Оставьте учебный сайт открытым в соседней вкладке. Поступление данных может начаться не сразу.');
C[73]=p('Проверьте **Active users**. На учебном сайте посетителей мало, поэтому ваше посещение, вероятно, окажется среди них.')+callout('Одного счётчика недостаточно для точной идентификации человека. Сопоставьте время и просмотренные страницы.');
C[74]=p('Найдите карточку просмотренных страниц. Сравните её с тем, что только что открывали.')+list(['Home — главная.','About — о проекте.','Contacts — контакты.'])+callout('Названия в отчёте зависят от title страниц. Сравнивайте также путь страницы, если он доступен.');
C[75]=p('В списке событий найдите **page_view** — просмотр страницы.')+code('page_view','EVENT NAME')+callout('Событийную модель и параметры подробно разберём в следующей теме.');
C[76]=p('Вернёмся к UTM: теперь размеченная ссылка ведёт на сайт с подключённым GA4.')+code('https://ВАШ-ПРОЕКТ.vercel.app/?utm_source=telegram&utm_medium=social&utm_campaign=ga4_lab','ССЫЛКУ КОПИРУЕМ ОДНОЙ СТРОКОЙ')+cards([['UTM_SOURCE','telegram','Источник перехода.'],['UTM_MEDIUM','social','Тип канала.'],['UTM_CAMPAIGN','ga4_lab','Учебная кампания.']]);
C[77]=p('Подставьте свой домен, скопируйте полную UTM-ссылку и откройте её в браузере.')+list(['Откройте несколько страниц.','Вернитесь на главную.','Оставьте сайт открытым.'])+callout('Для отдельной проверки источника начните новую сессию, например в приватном окне. Новая вкладка сама по себе не создаёт новую сессию GA4.');
C[78]=p('Теперь GA4 получает события с сайта, код и публикацию которого мы контролируем сами.')+flow(['UTM LINK|источник в ссылке','VERCEL WEBSITE|публичный сайт','GOOGLE TAG|отправка','WEB STREAM|нужный поток','GA4|обработка','REALTIME|наблюдение'],'wide-flow');
C[79]=cards([['КОД','VS Code','Редактируем исходные файлы.'],['ВЕРСИИ','GitHub','Храним проект и историю изменений.'],['ПУБЛИКАЦИЯ','Vercel','Размещаем сайт в интернете.'],['СБОР','Google Tag','Передаёт события из браузера.'],['АНАЛИЗ','GA4','Принимает и обрабатывает события.'],['ИСТОЧНИК','UTM','Описывает источник перехода в ссылке.']]);
C[80]=p('Сайт обновляется через версию кода в GitHub. Редактирование выполняем локально в VS Code.')+flow(['index.html|изменили код','Commit|зафиксировали','GitHub|отправили Push','Vercel Deployment|развёртывание','Production|новая версия']);
C[81]=p('Измените заголовок в `index.html` и опубликуйте новую версию.')+code('<h1>GA4 работает</h1>','ПРИМЕР ИЗМЕНЕНИЯ')+'<div class="deploy-demo"><button class="lab-action" id="deploy-demo" type="button">Показать путь обновления →</button><output id="deploy-state" aria-live="polite">Демонстрация: код ещё не сохранён</output></div>'+flow(['Save|файл сохранён','Commit|версия зафиксирована','Push|GitHub обновлён','Deploy|сайт обновлён'])+callout('Это учебная анимация. При обычном изменении текста перенастраивать GA4 не требуется.');
C[82]=p('HTML, CSS и JavaScript меняются, Vercel создаёт новые Deployment. Подключение к тому же потоку сохраняется.')+'<div class="stable-id"><span>Версия 1</span><span>Версия 2</span><span>Версия 3</span><strong>G-XXXXXXXXXX</strong><p>Один Measurement ID во всех версиях сайта</p></div>';
const checks=['Сайт опубликован на Vercel.','Открывается правильный production-домен .vercel.app.','В учебном Web Stream указан этот URL.','В теге указан правильный Measurement ID.','Google Tag вставлен целиком.','Тег стоит после <head> на каждой странице.','HTML-файлы сохранены.','Создан commit с изменениями.','Commit отправлен в GitHub.','Vercel завершил новый Deployment.','Открыта новая Production-версия.','Расширение или браузер не блокирует Analytics.'];
C[83]='<div class="diagnostics">'+checks.map((t,i)=>`<label><input type="checkbox"><span><b>${String(i+1).padStart(2,'0')}</b>${esc(t)}</span></label>`).join('')+'</div>'+callout('После проверки снова откройте сайт и Realtime. Учтите согласие на аналитику, если на сайте есть consent-баннер, и задержку появления данных.');
C[84]=cards([['01','GitHub Repository','github.com/user/ga4-analytics-lab'],['02','Vercel Project','ga4-analytics-lab-user.vercel.app'],['03','Web Data Stream','URL соответствует учебному сайту.'],['04','Google Tag','Установлен во всех трёх HTML-файлах.'],['05','Realtime','Есть реальное посещение и page_view.']])+callout('Галочка в результате ставится после проверки, а не после выполнения клика.');
C[85]=list(['Свой GitHub-репозиторий.','Клонированный проект в VS Code.','Успешный Deployment в Vercel.','Сайт на .vercel.app.','Web Data Stream с новым URL.','Measurement ID.','Google Tag внутри <head>.','Commit Add GA4 Google tag.','Realtime с активным пользователем.','Realtime с page_view.','Браузер с тестовой UTM-ссылкой.'])+callout('Эти материалы пригодятся для отчёта .md.');
C[86]=flow(['VS CODE|исходный код','GITHUB|история и main','VERCEL|публикация','PUBLIC WEBSITE|сайт студента','GOOGLE TAG|события из браузера','WEB DATA STREAM|адресат событий','EVENTS|page_view и другие','REPORTS / REALTIME|данные для анализа'],'architecture')+'<div class="utm-input"><b>UTM</b><span>Источник посетителя передаётся в ссылке на публичный сайт.</span></div>';
C[87]=p('Просмотры показывают посещённые страницы. Для анализа результата нужно определить, какие действия считать значимыми.')+cards([['BUTTON','Клик → ?','Какую кнопку нажали?'],['FORM','Форма → ?','Заявка успешно принята?'],['DOWNLOAD','Файл → ?','Какой материал скачали?']])+callout('Enhanced Measurement уже может собирать часть кликов, скачиваний и действий с формами. Их нужно проверить; регистрацию и целевые действия настроим отдельно.');
C[88]=p('Дальше разберём автоматические события, Enhanced Measurement, имена и параметры, собственные события, проверку и **Key Events**.')+flow(['CLICK|кнопки','FORM|формы','DOWNLOAD|файлы','SIGN UP|регистрация','GA4 EVENTS|действия и параметры'])+callout('Продолжим на том же Vercel-сайте: начнём измерять значимые действия.');

// Дополнительные слайды вне авторской нумерации 20–88: почему источник из UTM
// не появляется в отчётах сразу. Вставляются после исходного слайда 78 и имеют
// собственные id, поэтому ссылки вида index.html#60 продолжают работать.
const EXTRA=[
 {after:24,id:'slide-24a',stage:'GitHub → VS Code',badge:'ДОПОЛНЕНИЕ · АККАУНТ 1 / 2',title:'Шаг 0. Выйти из чужого аккаунта GitHub',
  body:p('На учебном компьютере в браузере часто остаётся аккаунт предыдущего студента. Если не выйти, копия шаблона появится у чужого пользователя, а вы не сможете её изменить.')
   +flow(['Аватар справа вверху|открыть меню','Sign out|выйти из аккаунта','github.com|проверить результат'])
   +callout('После выхода `github.com` показывает страницу входа, а не чужой профиль. Это и есть проверка.')},
 {after:24,id:'slide-24b',stage:'GitHub → VS Code',badge:'ДОПОЛНЕНИЕ · АККАУНТ 2 / 2',title:'Шаг 0.1. Войти в свой аккаунт',
  body:p('Войдите под своей учётной записью и убедитесь, что дальше работаете именно в ней.')
   +list(['**Sign in** — логин и пароль своего аккаунта.','Аватар справа вверху → в меню виден ваш логин.','Адрес профиля: `github.com/ВАШ-ЛОГИН`.'])
   +cards([['БРАУЗЕР','GitHub','Выйти из чужого аккаунта и войти в свой.'],['РЕДАКТОР','VS Code','Accounts → Sign out, если сохранён чужой вход.'],['ПУБЛИКАЦИЯ','Vercel','Войти тем же GitHub-аккаунтом.']])
   +callout('VS Code и Vercel помнят вход отдельно от браузера. Проверьте все три места до создания копии.')},
 {after:58,id:'slide-58a',stage:'Установка Google Tag',badge:'ДОПОЛНЕНИЕ · РАЗБОР КОДА 1 / 3',title:'Как устроен код Google Tag',
  body:p('Скопированный тег состоит из двух частей: сначала подключается библиотека, затем она настраивается на ваш поток. Обе части нужны и работают вместе.')
   +flow(['script src|загружает gtag.js','dataLayer|очередь для данных','gtag()|функция для вызовов','config|включает сбор'])
   +callout('Порядок важен: сначала подключение библиотеки, затем настройка потока.')},
 {after:58,id:'slide-58b',stage:'Установка Google Tag',badge:'ДОПОЛНЕНИЕ · РАЗБОР КОДА 2 / 3',title:'Первая строка: загрузка библиотеки',
  body:code('<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>','ЗАГРУЗКА БИБЛИОТЕКИ')
   +list(['`src` — адрес библиотеки `gtag.js` на серверах Google.','`?id=G-XXXXXXXXXX` — ваш Measurement ID: он указывает, в какой поток отправлять данные.','`async` — браузер загружает скрипт параллельно и не задерживает отрисовку страницы.'])
   +callout('Measurement ID здесь не секрет, но он адресует поток. С чужим идентификатором события уйдут в чужой ресурс.')},
 {after:58,id:'slide-58c',stage:'Установка Google Tag',badge:'ДОПОЛНЕНИЕ · РАЗБОР КОДА 3 / 3',title:'Вторая часть: очередь, функция и config',
  body:code("window.dataLayer = window.dataLayer || [];\nfunction gtag(){dataLayer.push(arguments);}\ngtag('js', new Date());\ngtag('config', 'G-XXXXXXXXXX');",'НАСТРОЙКА ПОТОКА')
   +list(['`window.dataLayer = window.dataLayer || []` — создаёт массив-очередь, если его ещё нет на странице.','`function gtag(){dataLayer.push(arguments);}` — складывает любой вызов в эту очередь.','`gtag(\'js\', new Date())` — отмечает момент инициализации.','`gtag(\'config\', \'G-XXXXXXXXXX\')` — включает сбор для потока и отправляет первый `page_view`.'])
   +callout('Очередь нужна потому, что вызовы могут произойти раньше, чем загрузится `gtag.js`. Библиотека разберёт накопленное, когда будет готова.')},
 {after:77,id:'slide-77a',stage:'UTM-переход',badge:'ДОПОЛНЕНИЕ · UTM-ССЫЛКИ 1 / 2',title:'Ссылки под разные каналы',
  body:p('Сайт один, а ссылок несколько. `utm_source` — площадка, `utm_medium` — тип канала, `utm_campaign` — общее имя кампании.')
   +code('https://ваш-проект.vercel.app/?utm_source=telegram&utm_medium=social&utm_campaign=ga4_lab\nhttps://ваш-проект.vercel.app/?utm_source=vk&utm_medium=social&utm_campaign=ga4_lab\nhttps://ваш-проект.vercel.app/?utm_source=youtube&utm_medium=video&utm_campaign=ga4_lab\nhttps://ваш-проект.vercel.app/?utm_source=email&utm_medium=letter&utm_campaign=ga4_lab\nhttps://ваш-проект.vercel.app/?utm_source=qr&utm_medium=offline&utm_campaign=ga4_lab','ПЯТЬ ССЫЛОК ОДНОЙ КАМПАНИИ')
   +callout('Домен подставьте свой. Кампанию оставьте одинаковой: в отчёте переходы соберутся в одну строку, а источники разойдутся по разным.')},
 {after:77,id:'slide-77b',stage:'UTM-переход',badge:'ДОПОЛНЕНИЕ · UTM-ССЫЛКИ 2 / 2',dense:true,title:'Разошлите и проверьте',
  body:p('Отправьте каждую ссылку в своё место и откройте её. Чем больше разных источников, тем нагляднее будет отчёт.')
   +cards([['SOCIAL','telegram · vk','Пост или сообщение в чате.'],['VIDEO','youtube','Описание под роликом.'],['LETTER','email','Письмо себе или однокурснику.'],['OFFLINE','qr','QR-код на бумаге.']])
   +list(['Каждый переход открывайте в новой сессии, например в приватном окне.','Новая вкладка сама по себе новую сессию GA4 не создаёт.','Запишите, какую ссылку куда отправили: потом сверите с отчётом.'])
   +callout('В отчёте **Привлечение → Привлечение трафика** источники разойдутся: `telegram`, `vk`, `youtube`, `email`, `qr` — при одной кампании `ga4_lab`.')},
 {after:78,id:'slide-78a',stage:'UTM-переход',badge:'ДОПОЛНЕНИЕ · ОБРАБОТКА 1 / 3',title:'Почему источник перехода не виден сразу',
  body:p('Событие и его источник попадают в отчёты по-разному. `page_view` появляется в Realtime за секунды, а источник, канал и кампания вычисляются позже — на этапе обработки данных.')
   +cards([['СРАЗУ','Realtime','Факт события: `page_view`, посещённые страницы, активные пользователи.'],['ПОЗЖЕ','Атрибуция','Источник, канал и кампания — после обработки на стороне GA4.']])
   +callout('Пустая карточка источника в Realtime не означает ошибку в метках. Realtime отвечает на вопрос «дошло ли событие», а не «откуда пришёл переход».')},
 {after:78,id:'slide-78b',stage:'UTM-переход',badge:'ДОПОЛНЕНИЕ · ОБРАБОТКА 2 / 3',title:'Что на самом деле уходит в GA4',
  body:p('Google Tag не отправляет `utm_source`, `utm_medium` и `utm_campaign` отдельными полями. Он передаёт адрес страницы целиком, а метки из него разбирает уже GA4.')
   +code('POST https://www.google-analytics.com/g/collect\n  tid  G-XXXXXXXXXX\n  en   page_view\n  dl   https://ваш-проект.vercel.app/?utm_source=telegram&utm_medium=social&utm_campaign=ga4_lab','ЗАПРОС ОТ ТЕГА')
   +list(['`tid` — Measurement ID вашего потока.','`en` — имя события, здесь `page_view`.','`dl` — адрес страницы вместе с UTM-метками.'])
   +callout('Метки доставлены в тот момент, когда запрос ушёл. Разбор и атрибуция происходят позже и уже без участия браузера.')},
 {after:78,id:'slide-78c',stage:'UTM-переход',badge:'ДОПОЛНЕНИЕ · ОБРАБОТКА 3 / 3',title:'Когда и где искать источники',
  body:p('На занятии проверяем факт сбора. Источник и кампанию смотрим в стандартном отчёте, когда обработка завершится.')
   +flow(['Переход по ссылке|метки в адресе','Google Tag|запрос с полем dl','Realtime|page_view сразу','Обработка|обычно часы','Привлечение трафика|источник · канал · кампания'])
   +callout('Путь в отчётах: **Отчёты → Привлечение → Привлечение трафика**. У только что созданного потока первые данные могут появиться в течение 24–48 часов.')},
];

const source=fs.readFileSync(path.join(dir,'SOURCE.md'),'utf8');
const slides=[...source.matchAll(/^# Слайд (\d+)\. (.+)\n([\s\S]*?)(?=^# Слайд \d+\.|$(?![\s\S]))/gm)].map(m=>{
 const body=m[3];const title=body.match(/## Заголовок\s+([\s\S]*?)(?=\n## )/)[1].trim();
 return {n:Number(m[1]),title,shot:body.includes('## Скриншот'),instructions:body.split('## Скриншот')[1]?.replace(/\n---\s*$/,'').trim()};
});
if(slides.length!==69||slides.some(s=>!C[s.n]))throw new Error('Expected all 69 authored slides');
const stage=n=>n<=22?'Маршрут практики':n<=30?'GitHub → VS Code':n<=32?'Локальная проверка':n<=44?'Публикация на Vercel':n<=54?'Обновление Web Stream':n<=61?'Установка Google Tag':n<=67?'Commit → Production':n<=75?'Проверка Realtime':n<=78?'UTM-переход':n<=85?'Контроль результата':'Архитектура и продолжение';
const labels={23:['GitHub','Шаблон репозитория','Название · файлы · README'],25:['GitHub','Use this template','Create a new repository'],26:['GitHub','Create repository','Owner · Repository name · Create'],27:['GitHub','Своя копия проекта','Владелец в адресе репозитория'],28:['VS Code','Clone Repository','Source Control · Clone Repository'],29:['VS Code','GitHub repositories','Свой репозиторий · Open'],30:['VS Code','Explorer','Дерево файлов · index.html'],31:['Браузер','Локальный сайт','Адресная строка: localhost'],33:['Vercel','Главная страница','Sign Up / Log In'],34:['Vercel','Авторизация','Вход через GitHub'],36:['Vercel','Dashboard','Add New → Project'],37:['Vercel','Import Git Repository','Свой репозиторий · Import'],38:['Vercel','Configure Project','Project Name'],39:['Vercel','Framework Preset','Раскрытый список · Other'],40:['Vercel','Build and Output Settings','Пустая Build Command'],41:['Vercel','Root Directory','Корень репозитория'],42:['Vercel','Первая публикация','Кнопка Deploy'],43:['Vercel','Успешный Deployment','Ready · production-домен'],44:['Браузер','Опубликованный сайт','Адресная строка: .vercel.app'],47:['GA4','Admin','Data streams'],48:['GA4','Data streams','Учебный поток с bytecamp.ru'],49:['GA4','Web stream details','Значок Edit / карандаш'],50:['GA4','Edit Web Stream','Новый Website URL · HTTPS'],51:['GA4','Edit Web Stream','Обновлённый Stream name'],52:['GA4','Edit Web Stream','Кнопка Update stream'],53:['GA4','Web stream details','Новый URL · прежний Measurement ID'],56:['GA4','Google tag','View tag instructions'],57:['GA4','Installation instructions','Install manually'],58:['GA4','Код Google Tag','Весь код · кнопка Copy'],59:['VS Code','index.html','Открывающий <head>'],60:['VS Code','Google Tag вставлен','Весь блок после <head>'],61:['VS Code','Три HTML-страницы','index · about · contacts'],63:['VS Code','Source Control','Три изменённых HTML-файла'],64:['VS Code','Commit','Add GA4 Google tag · Sync / Push'],66:['Vercel','Deployments','Новый commit · Ready · Production'],67:['Браузер','Новая Production-версия','Постоянный .vercel.app URL'],68:['GA4','Test your website','Полный URL · Test'],70:['Браузер','Посещение учебного сайта','Навигация Home / About / Contacts'],72:['GA4','Reports','Realtime'],73:['GA4','Realtime','Active users'],74:['GA4','Realtime: страницы','Home · About · Contacts'],75:['GA4','Realtime: события','page_view'],77:['Браузер','Тестовый UTM-переход','Полная ссылка в адресной строке']};
fs.mkdirSync(path.join(dir,'shots/placeholders'),{recursive:true});
const captures=slides.filter(s=>s.shot).map(s=>{
 if(!labels[s.n])throw new Error('Missing shot label '+s.n);
 return {sourceSlide:s.n,lessonSlide:s.n-19,file:`${s.n}-shot.png`,placeholder:`placeholders/${s.n}.svg`,screen:labels[s.n][1],application:labels[s.n][0],focus:labels[s.n][2],instructions:s.instructions,status:'placeholder'};
});
for(const s of captures){
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><rect width="1600" height="900" fill="#E5EDE8"/><path d="M0 90H1600M80 0V900M1520 0V900M0 810H1600" stroke="#CCDAD2" stroke-width="2"/><rect x="88" y="88" width="1424" height="724" rx="16" fill="#F7F9F6" stroke="#0C2733" stroke-width="4" stroke-dasharray="14 12"/><text x="140" y="162" font-family="Arial,sans-serif" font-size="25" font-weight="700" fill="#0E9384">${esc(s.application.toUpperCase())} / СКРИНШОТ ${s.sourceSlide}</text><g transform="translate(692 245)" fill="none" stroke="#0E9384" stroke-width="9"><rect width="216" height="154" rx="16"/><path d="M56 0L76 -26H141L161 0"/><circle cx="108" cy="77" r="38"/></g><text x="800" y="505" text-anchor="middle" font-family="Arial,sans-serif" font-size="49" font-weight="700" fill="#0C2733">${esc(s.screen)}</text><text x="800" y="579" text-anchor="middle" font-family="Arial,sans-serif" font-size="31" fill="#526771">${esc(s.focus)}</text><rect x="535" y="633" width="530" height="59" rx="6" fill="#D7EAE2"/><text x="800" y="673" text-anchor="middle" font-family="monospace" font-size="27" fill="#0C2733">shots/${s.file}</text><text x="140" y="765" font-family="Arial,sans-serif" font-size="22" fill="#647970">МЕСТО ДЛЯ РЕАЛЬНОГО КАДРА · ТЕМА 05 / СЛАЙД ${String(s.lessonSlide).padStart(2,'0')}</text></svg>`;
 fs.writeFileSync(path.join(dir,'shots',s.placeholder),svg);
}
const shot=s=>{const c=captures.find(x=>x.sourceSlide===s.n);return `<figure class="lab-shot"><button class="shot-open" data-shot="${s.n}" aria-label="Увеличить изображение: ${esc(c.screen)}"><img src="shots/${c.placeholder}" data-real-src="shots/${c.file}" alt="Заглушка: ${esc(c.application+' — '+c.screen+'. '+c.focus)}" width="1600" height="900"><span class="zoom-mark">↗</span></button><figcaption><b>${esc(c.application)}</b><span>${esc(c.focus)}</span></figcaption></figure>`;};
// Порядок показа: авторские слайды 20–88 плюс дополнительные экраны после 78.
const deck=[];
for(const s of slides){
 deck.push({id:`slide-${s.n}`,key:String(s.n),title:s.title,stage:stage(s.n),badge:`ИСХОДНИК ${s.n} · ТЕМА 05 / ${String(s.n-19).padStart(2,'0')}`,dark:[20,55,78,86,88].includes(s.n),dense:[83,85].includes(s.n),body:C[s.n],shot:s.shot?s:null,h:s.n===20?'1':'2'});
 for(const e of EXTRA.filter(e=>e.after===s.n))deck.push({...e,key:e.id.replace('slide-',''),dense:!!e.dense,shot:null,h:'2'});
}
const total=deck.length;
const fonts='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Roboto+Mono:wght@400;500;700&family=Space+Grotesk:wght@500;600;700&display=swap';
const head=`<!doctype html>\n<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0C2733"><title>Тема 5 · Свой сайт, Vercel и Google Tag · ОП.03</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="${fonts}" rel="stylesheet"><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"><script src="script.js" defer></script></head><body class="lab5"><a class="skip" href="#lesson-slides">К слайду</a><div class="lesson-deck"><header class="lesson-header"><a class="lesson-brand" href="../../index.html"><span>И/Т</span><b>ОП.03 · ТЕМА 05<small>Свой сайт → Google Tag → GA4</small></b></a><nav aria-label="Управление"><button data-dialog="contents">Содержание</button><a href="screenshots.html" title="Список скриншотов">Кадры</a><button data-dialog="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="lesson-counter"><b id="current">01</b> / ${total}</span></nav></header><main id="lesson-slides" tabindex="-1">`;
let html=head;
for(const s of deck){html+=`\n<section class="lesson-slide ${s.dark?'dark':''} ${s.shot?'has-shot':''} ${s.dense?'dense':''}" id="${s.id}" data-title="${esc(s.title.replaceAll('`',''))}" data-stage="${s.stage}" aria-labelledby="title-${s.key}"><div class="lesson-inner"><p class="lesson-kicker">${s.stage}<span>${s.badge}</span></p><h${s.h} id="title-${s.key}">${inline(s.title)}</h${s.h}>${s.shot?`<div class="lab-workbench"><div class="lab-copy">${s.body}</div>${shot(s.shot)}</div>`:`<div class="lab-content">${s.body}</div>`}</div></section>`;}
html+=`</main><footer class="lesson-footer"><span id="chapter">Маршрут практики</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Далее →</button><div class="lesson-progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${total}" aria-valuenow="1"><i id="progress"></i></div></footer></div><div class="sr-only" id="announcement" aria-live="polite"></div><dialog id="contents"><div class="dialog-top"><h2>Содержание · ${total} слайдов</h2><button data-close aria-label="Закрыть">✕</button></div><p class="dialog-note">Слева — номер в теме 5. Справа — исходная нумерация 20–88.</p><div class="contents-list">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${String(i+1).padStart(2,'0')}</b><span>${inline(s.title)}</span><small>${s.key}</small></button>`).join('')}</div></dialog><dialog id="visual"><div class="dialog-top"><h2 id="visual-title">Изображение</h2><button data-close aria-label="Закрыть изображение">✕</button></div><img id="visual-img" alt=""><p id="visual-caption"></p></dialog><dialog id="sources"><div class="dialog-top"><h2>Источники и материалы</h2><button data-close aria-label="Закрыть">✕</button></div><p>${total} слайдов: 69 в порядке авторского текста с исходными номерами 20–88 и три дополнительных экрана об обработке данных в GA4.</p><a href="screenshots.html">Какие скриншоты снять и куда поставить →</a><a href="https://vercel.com/docs/builds/configure-a-build" target="_blank" rel="noopener noreferrer">Vercel: статический сайт и параметры публикации ↗</a><a href="https://code.visualstudio.com/docs/sourcecontrol/quickstart" target="_blank" rel="noopener noreferrer">VS Code: клонирование, commit и синхронизация ↗</a><a href="https://support.google.com/analytics/answer/9304153?hl=ru" target="_blank" rel="noopener noreferrer">GA4: установка тега на каждую страницу ↗</a><a href="https://support.google.com/analytics/answer/9216061?hl=ru" target="_blank" rel="noopener noreferrer">Enhanced Measurement ↗</a><a href="https://support.google.com/analytics/answer/11242841?hl=ru" target="_blank" rel="noopener noreferrer">Кампании, источники и сессии ↗</a><button class="lab-action" id="print">Печать / сохранить в PDF</button></dialog><noscript><p class="nojs">JavaScript выключен: все слайды доступны последовательно.</p></noscript></body></html>`;
fs.writeFileSync(path.join(dir,'index.html'),html);
fs.writeFileSync(path.join(dir,'shots/manifest.json'),JSON.stringify({status:'placeholders_requested',numbering:'sourceSlide = 20–88; lessonSlide = 1–69',captures},null,2)+'\n');
const intro=`# Скриншоты для темы 5\n\n${captures.length} кадра. Номера файлов соответствуют исходному тексту (20–88), а не номеру шага.\n\nПапка: op03-informacionnye-tehnologii/lessons/05-vercel-google-tag/shots/\n\nСнимать PNG, желательно 1600×900 или больше, масштаб браузера 100%. Оставлять нужные поля и кнопки читаемыми. Для кадров сайта обязательно показать адресную строку. Для VS Code использовать графический интерфейс, как в исходнике. Не показывать пароли, email, аватар и посторонние проекты. Measurement ID не является секретом. Снимать только учебный поток; рабочий ByteCamp не изменять.\n\nНе рисовать интерфейс и не подменять реальные результаты. Если экран недоступен, записать причину. Кадры 38–42, 50–52, 56–58 и 72–75 удобно снимать подряд. Для разных раскрытых списков и состояний нужны отдельные кадры.\n\nПосле сохранения PNG под указанными именами презентация автоматически попробует загрузить их вместо SVG-заглушек при открытии. Заглушки сохраняются для отсутствующих PNG. Проверить кадры через HTTP-сервер; подписи и увеличение уже предусмотрены.\n\n| В теме 5 | В исходнике | Файл | Экран | Что видно / акцент |\n|---|---|---|---|---|\n`;
const rows=captures.map(c=>`| ${c.lessonSlide} | ${c.sourceSlide} | ${c.file} | ${c.application}: ${c.screen} | ${c.focus} |`).join('\n');
fs.writeFileSync(path.join(dir,'SCREENSHOTS.md'),intro+rows+'\n\n## Подробные указания из исходника\n\n'+captures.map(c=>`### ${c.sourceSlide} — ${c.file}\n\n${c.instructions}\n`).join('\n'));
const table=captures.map(c=>`<tr><td><a href="index.html#${c.sourceSlide}">${String(c.lessonSlide).padStart(2,'0')}</a></td><td>${c.sourceSlide}</td><td><code>${c.file}</code></td><td>${esc(c.application)}<br><b>${esc(c.screen)}</b></td><td>${esc(c.focus)}</td></tr>`).join('');
fs.writeFileSync(path.join(dir,'screenshots.html'),`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Кадры для темы 5 · ОП.03</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head><body class="lab5 shot-guide"><main><a href="index.html">← К презентации</a><p class="lesson-kicker">ОП.03 · ТЕМА 05</p><h1>Какие скриншоты снять</h1><p>${captures.length} кадра для 69 слайдов. «В теме» — номер экрана презентации. «Исходник» — номер 20–88 из авторского текста.</p><p>Сохраняйте PNG в <code>05-vercel-google-tag/shots/</code> под указанными именами. После обновления страницы кадры автоматически заменят заглушки. Для сайта оставьте адресную строку; для VS Code снимайте графический интерфейс.</p><p>Снимайте только учебные проекты. Личные данные скройте; Measurement ID можно оставить. Показатели Realtime и статусы Deployment должны быть настоящими.</p><div class="table-scroll"><table><thead><tr><th>В теме</th><th>Исходник</th><th>Файл</th><th>Экран</th><th>Акцент</th></tr></thead><tbody>${table}</tbody></table></div><p>Схемы на остальных слайдах уже сделаны в HTML/CSS и не требуют скриншотов.</p></main></body></html>`);
console.log(`Built ${total} slides (${slides.length} authored + ${EXTRA.length} extra); ${captures.length} image placeholders and capture instructions.`);
