import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||''};});
if(originals.length!==105||originals.some((s,i)=>+s.id!==354+i))throw Error('Нарушен порядок 354–458');
const extras={
359:[{id:'359a',title:'Скачайте и распакуйте комплект',body:dl('power-query-combine-lab.zip','Скачать все файлы практики')+bullets(['Распакуйте lesson_power_query_02 в постоянную папку.','В incoming должны быть только три CSV за 23, 24 и 25 сентября.','Справочники лежат в lookup, будущие файлы — в later, резервная копия — в backup.'])+result('На старте: 3 файла × 3 заявки = 9 строк. Папки later и backup находятся рядом с incoming, не внутри неё.'),shot:'Проводник: распакованная папка практики; incoming с тремя CSV, рядом lookup, later, backup и result.'}],
364:[{id:'364a',title:'Проверьте доступность From Folder',body:cards([['Рабочий маршрут','Настольный Excel для Windows с Power Query: Data → Get Data → From File → From Folder.'],['Если команды нет','Доступность источников зависит от платформы и версии. Используйте учебный компьютер, где есть From Folder и Power Query Editor.']])+note('Не заменяйте этот маршрут импортом отдельных CSV: цель занятия — обновление папки как одного источника. Готовую книгу из темы 8 не меняем.'),shot:'Excel: меню Data → Get Data с командой From Folder. Записать ОС и версию Excel в evidence.json.'}],
374:[{id:'374a',title:'Подпапки тоже могут попасть в источник',body:bullets(['Folder Source может читать файлы из вложенных папок. Один фильтр .csv не исключает архивные CSV.','В Folder Path оставьте точный путь к incoming, без вложенных директорий.','Проверьте Name: только leads_…csv. При необходимости Text Filters → Begins With → leads_.'])+result('После фильтров видны именно три нужных имени. Не выбирайте имена по одному: такой фильтр может исключить будущие файлы.'),shot:'Фильтры Folder Path и Name: путь incoming, имена начинаются с leads_; три нужных CSV.'}],
381:[{id:'381a',title:'Проверяем заголовки и типы после Combine',body:bullets(['Выберите основной leads_combined, последний Applied Step.','Ожидаем Source.Name и 8 полей заявок; созданные заголовки не должны повторяться как строки.','created_at → Date/Time; остальные поля и Source.Name → Text.'])+note('Если видны Column1… или заголовки внутри данных, проверьте Transform Sample File → Use First Row as Headers. Изменение там применяется ко всем файлам; затем проверьте шаги основного запроса.'),shot:'leads_combined: Source.Name и восемь заголовков с типами; данные из трёх файлов.'}],
385:[{id:'385a',title:'Загрузите первые 9 строк в Excel',body:click(['Home','Close & Load To…','Table','New worksheet'])+bullets(['Загрузите leads_combined таблицей на новый лист.','Назовите лист leads_combined, сохраните result/power_query_combined.xlsx.','Дождитесь окончания загрузки. Только затем добавляйте четвёртый CSV.'])+result('На листе 9 строк заявок. Книга содержит запрос и его подключение.'),shot:'Close & Load To: Table и New worksheet; затем таблица leads_combined на 9 строк.'}],
388:[{id:'388a',title:'Вернитесь в редактор для Merge',body:click(['Data','Queries & Connections','leads_combined','Правой кнопкой → Edit'])+bullets(['Откройте существующий запрос; новый Folder Source не создаём.','Убедитесь, что показаны 12 записей и четыре значения Source.Name.','Для следующих CSV-справочников можно вернуться в Excel через Close & Load.'])+result('Мы продолжаем тот же запрос. Его исходник остаётся папкой incoming.'),shot:'Queries & Connections: leads_combined → Edit; запрос после обновления.'}],
397:[{id:'397a',title:'Совпадение ключей должно быть точным',body:bullets(['В leads_combined выделите utm_source: Text → Trim → lowercase.','В sources_lookup выделите source: Text → Trim → lowercase.','Проверьте, что ни в одном ключе нет пустых значений. Fuzzy matching в Merge оставляем выключенным.'])+note('У столбцов могут быть разные имена. Для сопоставления важны одинаковый тип и согласованные значения. Отображаемый source_name в lowercase не переводим.'),shot:'Оба ключевых столбца: utm_source и source имеют Text, шаги Trim и lowercase.'},
{id:'397b',title:'В справочнике один ключ — одна строка',body:bullets(['Проверьте четыре строки sources_lookup: telegram, vk, email, direct. Каждый ключ встречается один раз.','Если справа два telegram, раскрытие Merge создаст по две строки для каждой Telegram-заявки.','Конфликт справочника разбирают до Merge; случайно удалять одну из разных записей нельзя.'])+result('Перед соединением: 12 заявок и 4 уникальных ключа источников.'),shot:'sources_lookup целиком: четыре уникальных непустых source, у каждого заполнены source_name и channel_group.'}],
410:[{id:'410a',title:'После Expand пересчитайте строки',body:bullets(['Нажмите OK в Expand после выбора source_name и channel_group.','Сравните число строк до и после раскрытия: должно остаться 12.','Если строк больше — проверьте повторяющиеся ключи в sources_lookup. Если меньше — Join Kind или фильтры.'])+result('12 заявок, 11 столбцов: Source.Name + 8 исходных + 2 поля справочника.'),shot:'leads_combined после Expand: 12 записей, два новых поля и сохранённый Source.Name.'}],
414:[{id:'414a',title:'Обязательно отмените пробный фильтр',body:bullets(['Мы применили фильтр null только для демонстрации. В Applied Steps найдите последний Filtered Rows.','Удалите именно этот последний шаг крестиком слева. Другие шаги не трогайте.','Убедитесь, что снова видны все 12 заявок; затем переходите к Merge Queries as New.'])+result('Основной leads_combined снова содержит весь набор. Иначе Left Anti будет построен на уже обрезанной таблице.'),shot:'Applied Steps: удаляется только демонстрационный Filtered Rows; восстановлен полный набор из 12 заявок.'}],
419:[{id:'419a',title:'Загрузите отчёт, не раскрывая пустую таблицу',body:bullets(['В unmatched_sources уже находятся строки слева без совпадения.','Если остался вложенный столбец правой таблицы, удалите только этот столбец: раскрывать в нём нечего.','Close & Load To → Table → New worksheet. Назовите лист unmatched_sources.'])+result('Основная таблица: 12 строк. Отчёт: одна — REQ-108 / tiktok. Оба результата доступны на отдельных листах.'),shot:'Excel: два листа leads_combined и unmatched_sources; в отчёте только REQ-108.'}],
421:[{id:'421a',title:'Допишите справочник в исходном CSV',body:code('tiktok,TikTok,social','ДОБАВИТЬ ОДНУ СТРОКУ В lookup/sources_lookup.csv')+bullets(['Откройте CSV в текстовом редакторе. Заголовок повторно не вставляйте.','Добавьте строку после direct; сохраните UTF-8 и то же имя файла.','Не редактируйте загруженную таблицу Excel: Refresh перезапишет такой результат.'])+result('В справочнике теперь 5 уникальных ключей. Входная заявка REQ-108 не менялась.'),shot:'lookup/sources_lookup.csv после сохранения: заголовок, пять строк, tiktok добавлен один раз.'}],
427:[{id:'427a',title:'Назначьте типы полям статуса',body:cards([['status','Text. Trim и lowercase перед соединением.'],['status_order','Whole Number / Целое число.'],['is_final','True/False / Логический, не текст.']])+bullets(['Проверьте четыре уникальных status. В leads_combined.status также примените Text, Trim и lowercase.','Справочник можно загрузить через Close & Load To → Only Create Connection. Затем откройте leads_combined через Edit.']),shot:'statuses_lookup: четыре строки; ABC у status, 123 у status_order, логический тип у is_final.'}],
429:[{id:'429a',title:'Сохраните оба результата после второго Merge',body:bullets(['После Expand должны остаться 12 строк. Новых полей два: status_order и is_final.','Close & Load, дождитесь обновления. В Excel выполните Refresh All для результатов и сохраните книгу.','Перед новыми файлами unmatched_sources должен быть пуст: tiktok уже добавлен.'])+result('Основной набор: 12 строк × 13 столбцов. В отчёте нет неизвестных источников на этом этапе.'),shot:'Excel: leads_combined после двух Merge, поля статуса и 12 записей; отдельный лист отчёта.'}],
439:[{id:'439a',title:'Следующий опыт: отдельный файл с YouTube',body:bullets(['После проверки REQ-120 в incoming четыре старых CSV и файл за 27 сентября: всего 13 заявок.','Для следующего опыта скопируйте later/leads_2026-09-28.csv в incoming.','Он содержит одну новую заявку REQ-121, utm_source=youtube, status=new. Справочник источников не меняйте.'])+result('Следующий Refresh должен дать 14 основных строк и 1 несовпавшую.'),shot:'incoming: добавлен leads_2026-09-28.csv; в редакторе его строка REQ-121 / youtube.'}],
450:[{id:'450a',title:'Сохраните папку целиком и проверьте пути',body:bullets(['Сохраните result/power_query_combined.xlsx после последнего Refresh.','Сдайте всю папку практики: incoming, lookup, later, backup, result и контрольные кадры.','На другом компьютере проверьте Data Source Settings: путь к incoming и к обоим CSV-справочникам.'])+note('Книга сохраняет запросы и последний результат, но локальные пути источников не становятся переносимыми автоматически.'),shot:'Сохранённая книга в result и структура всей папки для сдачи.'}]
};
const custom={
354:`<p class="lead">В теме 8 мы описали правила для одного CSV. Теперь применим общий процесс к ежедневным файлам и добавим справочники.</p>${flow(['Один CSV','Applied Steps','Refresh','Новые строки'])}${note('Навыки Trim, типов и проверки результата сохраняются. Входные файлы этой практики подготовлены отдельно: без email, с отдельными UTM-полями.')}`,
355:flow(['23 сентября','24 сентября','25 сентября','Общий набор'])+`<p>Все файлы описывают одну сущность — <strong>заявку</strong>. Объединяем записи, сохраняя происхождение каждой строки.</p>`,
356:cards([['Ручной способ','Открыть каждый CSV, скопировать строки и собрать общую таблицу.'],['Завтра','Новый файл — и все ручные действия приходится повторять.']])+note('Ручное копирование не сохраняет воспроизводимый способ сборки.'),
357:flow(['Папка incoming','Power Query','Единый набор'])+note('В тему 8 приходила новая версия одного файла. Здесь приходит новый файл с новыми заявками.'),
358:flow(['From Folder','Проверка файлов','Combine','Source.Name','Lookup','Left Outer','Expand','Left Anti']),
359:code('lesson_power_query_02/\n├── incoming/   ← 3 CSV на старте\n├── lookup/     ← sources_lookup.csv, statuses_lookup.csv\n├── later/      ← новые CSV для опытов Refresh\n├── backup/     ← исходная версия справочника\n├── result/     ← здесь будет книга Excel\n└── README.md','ПАПКА ПРАКТИКИ'),
363:code('request_id · created_at · name · direction\nutm_source · utm_medium · utm_campaign · status','ОДИНАКОВЫЕ 8 ЗАГОЛОВКОВ')+note('Файлы могут содержать разное число строк. Названия полей, разделитель и правила типов должны быть согласованы.'),
364:cards([['Совместимо','request_id | created_at | status в каждом CSV.'],['Требует разбора','id | date | lead_status — уже другие имена полей.']])+note('Для этой практики имена и порядок восьми столбцов одинаковы. Power Query не угадывает, что traffic_source — это utm_source.'),
365:click(['Excel','Blank workbook','Сохранить как'])+code('lesson_power_query_02/result/power_query_combined.xlsx','НОВАЯ КНИГА')+result('Откройте Data / Данные. Книгу темы 8 оставьте отдельно.'),
366:click(['Data','Get Data','From File','From Folder'])+`<p>Выбираем источник <strong>папка</strong>, а не отдельный текстовый файл.</p>`,
367:code('lesson_power_query_02/incoming','ВЫБРАТЬ ЭТУ ПАПКУ')+note('Не выбирайте корень lesson_power_query_02: иначе вместе с заявками могут попасть справочники и будущие файлы.'),
368:code('Content · Name · Extension\nDate accessed · Date modified · Date created\nFolder Path','ПОКА ЭТО МЕТАДАННЫЕ')+result('Одна строка в этом окне — один файл. Это ещё не одна заявка.'),
369:cards([['Name','Имя CSV, например leads_2026-09-23.csv.'],['Content = Binary','Содержимое файла ещё предстоит прочитать как таблицу.']]),
370:bullets(['Проверьте три имени: 23, 24 и 25 сентября.','У каждого расширение .csv; лишних файлов не должно быть.','README, архивы и резервные копии хранятся вне incoming.'])+result('3 файла до объединения. Это будущие 9 заявок.'),
371:cards([['incoming','Только актуальные дневные файлы заявок.'],['lookup / later / backup','Справочники, будущие файлы и копии — отдельно.']])+note('Папка Downloads непредсказуема: её не используем как источник.'),
372:click(['Folder Preview','Transform Data'])+`<p>Сначала откроем список файлов в редакторе и настроим отбор. После этого выполним Combine Files.</p>`,
373:click(['Extension','Фильтр','.csv','OK'])+result('Остались только CSV. Проверка пути и имён остаётся необходимой: не каждый CSV является заявками.'),
374:bullets(['Прокрутите таблицу вправо до Folder Path.','У всех трёх файлов должен быть путь к нужной incoming.','Сравните путь с папкой, которую подготовили для занятия.']),
375:click(['Content','Значок Combine Files'])+`<p>Кнопка в заголовке Content запускает объединение содержимого. Следующее окно — выбор файла-образца и настроек CSV.</p>`,
376:flow(['Один образец','Правила чтения','Каждый CSV','Общая таблица'])+note('Образец помогает настроить кодировку, разделитель и ожидаемые поля. Остальные файлы должны соответствовать этому контракту.'),
377:bullets(['Sample File: leads_2026-09-23.csv, если доступен явный выбор.','File Origin: 65001 / UTF-8. Delimiter: Comma / Запятая.','Data Type Detection: не определять типы, если настройка доступна; типы проверим в основном запросе.','Skip files with errors, если показан, оставьте выключенным.'])+result('В образце читаются русские имена и 8 полей. Ошибочные файлы не будут незаметно пропускаться.'),
378:click(['Combine Files','OK'])+result('В Queries появились основной запрос и вспомогательные запросы. Не удаляйте их.'),
379:cards([['Sample File / Parameter','Выбор примера и передача содержимого файла.'],['Transform Sample File','Шаги обработки на одном образце.'],['Transform File','Функция, применяемая к каждому выбранному файлу.']])+note('Названия и группировка зависят от языка и версии Excel. Эти запросы связаны между собой.'),
380:flow(['Каждый CSV','Одинаковые преобразования','Результаты друг под другом'])+note('Если изменяете Transform Sample File, проверяйте затем основной запрос: его поздние шаги могут ожидать старую структуру.'),
381:click(['Основной запрос','Query Settings','Name: leads_combined'])+result('Переименован итоговый запрос, содержащий заявки, а не helper query с одним образцом.'),
382:cards([['Вход','3 CSV × 3 записи.'],['Ожидаемый выход','9 заявок, без строк заголовков внутри данных.']])+note('Для маленького набора можно просмотреть все строки. Счётчик preview на больших объёмах может показывать только ограниченный просмотр.'),
383:code('Source.Name                    request_id\nleads_2026-09-24.csv           REQ-105','ПРОИСХОЖДЕНИЕ ЗАПИСИ')+note('Сохраните имя файла. Если поле названо иначе, найдите его по содержимому и переименуйте в Source.Name.'),
384:flow(['REQ-105','Source.Name','leads_2026-09-24.csv'])+`<p><strong>Data lineage</strong> — возможность проследить происхождение данных.</p>`,
385:cards([['Две одинаковые заявки','Сначала выясняем, из какого файла пришла каждая.'],['Source.Name','Помогает отличить повторную выгрузку от повторной записи в одном файле.']]),
386:click(['later/leads_2026-09-26.csv','Скопировать','incoming'])+bullets(['В файле три новые заявки: REQ-110, REQ-111, REQ-112.','Копируем файл целиком; заголовок и структура те же.','Проверьте: в incoming теперь четыре CSV.'])+result('Не создавайте копию с суффиксом «(1)»: один и тот же файл не должен попасть в папку дважды.'),
387:click(['Excel','Data','Refresh All'])+bullets(['Дождитесь завершения обновления.','From Text/CSV повторно не запускаем.','Если строки не добавились, проверьте сохранение файла, путь и фильтры источника.']),
388:cards([['Было','9 строк из трёх файлов.'],['Добавили','3 строки из файла за 26 сентября.'],['Стало','12 строк. REQ-110…REQ-112 появились.']]),
389:flow(['Новый CSV','incoming','Refresh','Общий набор'])+note('Это чтение текущего содержимого папки заново, а не журнал накопления. Если убрать CSV из источника, при следующем обновлении его строки могут исчезнуть.'),
390:cards([['Таблица A','REQ-101, REQ-102, REQ-103.'],['Таблица B','REQ-104, REQ-105, REQ-106.'],['Append','Обе группы строк в одной таблице.']])+note('Combine Files сначала читает и преобразует каждый файл, затем складывает результаты по логике Append.'),
391:code('3 заявки + 3 заявки = 6 заявок','APPEND → ЕЩЁ СТРОКИ')+`<p>Вопрос: <strong>где взять ещё записи того же типа?</strong></p>`,
392:cards([['Ключ заявки','utm_source = telegram.'],['Нужный контекст','source_name = Telegram, channel_group = social.']])+note('Описания источников храним в отдельном справочнике, а не вручную в каждой заявке.'),
393:code('source     source_name   channel_group\ntelegram   Telegram      social\nvk         VK            social\nemail      Email         email\ndirect     Direct        direct','СПРАВОЧНИК СООТВЕТСТВИЙ'),
395:cards([['В заявке','REQ-108: utm_source = tiktok.'],['В справочнике','Такого ключа пока нет.']])+note('Специально оставляем одно несовпадение, чтобы проверить поведение Join.'),
396:click(['Excel: Data','Get Data','From File','From Text/CSV'])+code('lookup/sources_lookup.csv','ИМПОРТ СПРАВОЧНИКА')+note('Если открыт редактор, сначала Close & Load. В окне импорта справочника проверьте UTF-8 и Comma.'),
397:click(['Transform Data','Query Settings','Name: sources_lookup'])+bullets(['Убедитесь, что первая строка — заголовки source, source_name, channel_group.','Все три поля имеют тип Text. Должны быть 4 строки данных.','Справочник можно оставить подключением: Close & Load To → Only Create Connection. Для дальнейших действий снова откройте редактор.']),
398:cards([['Слева · leads_combined','Ключ utm_source: telegram.'],['Справа · sources_lookup','Ключ source: telegram.']])+note('Столбцы называются по-разному — это нормально. Соединение задаётся выбором столбцов, а не сходством их имён.'),
399:cards([['Append','Добавить ещё записи.'],['Merge','Сопоставить записи по ключу и получить связанные данные.']]),
400:cards([['Append ↓','Дневные CSV → больше строк заявок.'],['Merge →','Заявки + справочник → дополнительные поля.']])+note('После раскрытия Merge число строк сохранится только при подходящей связи: здесь справа один ключ должен встречаться один раз.'),
401:click(['leads_combined','Последний Applied Step','Home','Merge Queries'])+note('Первый Merge выполняем в текущем запросе. Основной набор остаётся leads_combined.'),
402:bullets(['Верхняя таблица: leads_combined → щёлкните заголовок utm_source.','Нижняя таблица: выберите sources_lookup → щёлкните source.','Оба выбранных заголовка должны быть подсвечены. Fuzzy matching выключен.'])+result('Слева заявки, справа справочник. Следующим шагом задаём Join Kind.'),
403:click(['Join Kind','Left Outer'])+`<p>Тип соединения определяет, какие строки сохраняются. Для основной таблицы нужны <strong>все заявки слева</strong>.</p>`,
404:cards([['Левая таблица','Все заявки остаются.'],['Правая таблица','Связанные поля добавляются, если найден ключ.']])+note('Уникальность ключа справа нужна, чтобы Expand не размножал заявки.'),
405:flow(['REQ-108 / tiktok','В справочнике нет','Inner','Строки нет в результате'])+note('Inner не удаляет исходный CSV, но исключает несовпавшую запись из результата соединения.'),
406:code('REQ-108 | tiktok | null | null','СОХРАНИЛИ ЗАЯВКУ И УВИДЕЛИ ПРОБЛЕМУ')+note('Отсутствие соответствия диагностируем отдельно от основного набора.'),
407:click(['Проверить ключи','Left Outer','OK'])+result('В конце таблицы появился вложенный столбец sources_lookup со значениями Table.'),
408:cards([['Совпадение','Во вложенной таблице есть связанная строка.'],['Нет совпадения','Вложенная таблица пустая. После Expand поля будут null.'],['Несколько совпадений','Внутри несколько строк; раскрытие размножит левую запись.']]),
409:click(['sources_lookup','Значок Expand'])+bullets(['Снимите «Выбрать все». Оставьте source_name и channel_group.','Поле source повторно не добавляем: технический utm_source уже есть.','Пока не подтверждайте: на следующем экране настроим префикс.']),
410:bullets(['В том же диалоге Expand снимите Use original column name as prefix.','Ожидаемые имена: source_name и channel_group.','Проверьте, что в основном наборе ещё нет полей с такими именами.'])+result('Список двух полей и настройка префикса готовы; нажимаем OK на следующем шаге.'),
411:cards([['Было','utm_source = telegram.'],['Стало','utm_source = telegram; source_name = Telegram; channel_group = social.']]),
412:code('REQ-108\nutm_source     tiktok\nsource_name    null\nchannel_group  null','НЕТ СОВПАДЕНИЯ СПРАВА')+result('Запись сохранилась среди 12 заявок.'),
413:`<p>В нашем учебном справочнике описательные поля заполнены. Поэтому у REQ-108 значения <code>null</code> после Merge показывают отсутствие соответствия.</p>`+note('В общем случае поле справочника само может быть пустым. Фильтр null не всегда доказывает отсутствие ключа; Left Anti проверяет именно отсутствие совпадения.'),
414:click(['source_name','Фильтр','Только null','OK'])+result('Временно видна одна строка REQ-108. Сразу после снимка отменим этот фильтр отдельным шагом.'),
415:cards([['leads_combined','Все 12 заявок остаются в основном наборе.'],['unmatched_sources','Отдельный запрос только для несовпавших ключей.']])+note('Перед созданием отчёта проверьте: пробный Filtered Rows удалён.'),
416:click(['Home','Merge Queries ▼','Merge Queries as New'])+note('В новом диалоге обе таблицы нужно проверить и при необходимости выбрать заново. Не полагайтесь на текущую выделенную таблицу.'),
417:flow(['Все заявки слева','Сравнить ключи','Оставить только без совпадений'])+`<p><strong>Left Anti</strong> ищет заявки, чьего utm_source нет в sources_lookup.source.</p>`,
418:cards([['Верхняя таблица','leads_combined → utm_source.'],['Нижняя таблица','sources_lookup → source.']])+click(['Join Kind','Left Anti','OK'])+result('Правые поля раскрывать не нужно: цель — получить несовпавшие левые строки.'),
419:click(['Новый запрос','Query Settings','Name: unmatched_sources'])+code('REQ-108 | tiktok','ОЖИДАЕТСЯ ОДНА ЗАЯВКА')+note('Это отдельный запрос; исходный leads_combined остаётся полным.'),
420:cards([['Основной набор','leads_combined — все заявки.'],['Отчёт','unmatched_sources — подмножество без соответствий.']])+note('Не складывайте число строк этих таблиц: одна проблемная заявка присутствует и в основной, и в отчёте.'),
421:`<p>В рамках упражнения считаем <code>tiktok</code> допустимым источником. Добавляем его в справочник, сохраняя исходную заявку.</p>`+code('tiktok,TikTok,social','НОВОЕ ПРАВИЛО СООТВЕТСТВИЯ')+note('В рабочей системе сначала выясняют, допустимый ли это новый источник или опечатка. Не каждый неизвестный ключ автоматически становится допустимым.'),
422:click(['Сохранить CSV','Excel: Data','Refresh All','Дождаться окончания'])+code('REQ-108 | tiktok | TikTok | social','РЕЗУЛЬТАТ В leads_combined')+result('Количество основных строк всё ещё 12.'),
423:code('unmatched_sources: 0 строк','ПОСЛЕ ОБНОВЛЕНИЯ СПРАВОЧНИКА')+note('Это означает отсутствие неизвестных источников в текущем загруженном наборе. Проверка не доказывает отсутствие дублей, ошибок даты или других проблем качества.'),
425:cards([['Порядок отображения','new = 1, in_progress = 2, done = 3, rejected = 4.'],['Переходы процесса','new → in_progress → done; rejected — отдельный исход, а не обязательная стадия после done.']])+note('status_order задаёт сортировку отчёта. Сам по себе он не описывает все допустимые переходы статусов.'),
426:code('new          false\nin_progress  false\ndone         true\nrejected     true','СТАТУС → is_final')+note('Это правило нашего справочника: закрытые состояния описаны в одном месте.'),
427:click(['Excel: Data','Get Data','From Text/CSV','lookup/statuses_lookup.csv'])+bullets(['UTF-8, Comma → Transform Data.','Проверьте заголовки status, status_order, is_final.','Назовите запрос statuses_lookup. Типы назначим на следующем экране.']),
428:click(['leads_combined','Home','Merge Queries'])+cards([['Слева','leads_combined.status.'],['Справа','statuses_lookup.status.']])+result('Join Kind = Left Outer; оба ключа Text; fuzzy matching выключен. Нажмите OK.'),
429:click(['statuses_lookup','Expand'])+bullets(['Оставьте только status_order и is_final.','Снимите Use original column name as prefix.','Нажмите OK. Не добавляйте status повторно.'])+result('Каждая заявка получила числовой порядок статуса и логический признак завершения.'),
430:code('Source.Name\nrequest_id · created_at · name · direction\nutm_source · utm_medium · utm_campaign · status\nsource_name · channel_group\nstatus_order · is_final','ИТОГО: 13 СТОЛБЦОВ')+note('8 исходных полей + имя файла + 2 поля источника + 2 поля статуса. Исходные поля сохранены.'),
431:cards([['Технический ключ','utm_source = telegram; пригоден для связи и автоматизации.'],['Подпись для человека','source_name = Telegram; хранится отдельно.']]),
432:cards([['Left Outer','Все слева; для неизвестного ключа связанные поля null.'],['Inner','Только строки с найденным совпадением.'],['Left Anti','Только строки слева без совпадения.']])+note('Для наглядности предполагаем уникальный ключ в справочнике. Иначе при Expand совпадения могут размножать строки.'),
433:flow(['Все заявки слева','Left Outer','Контекст справа, если найден'])+note('Основной набор должен сохранять неизвестные источники для дальнейшего разбора.'),
434:`<p class="lead">Inner оставляет только совпавшие ключи.</p>`+note('Используйте его, когда исключение несовпавших записей — явное требование. Для основной таблицы этой практики это не подходит.'),
435:bullets(['Какие источники неизвестны справочнику?','Какие ID отсутствуют во второй системе?','Какие левые записи не нашли пару?'])+flow(['Левая таблица','Left Anti','Отчёт несовпадений']),
436:cards([['Append / Combine ↓','Ещё строки: дневные файлы заявок.'],['Merge →','Связанные сведения: описание источника и свойства статуса.']]),
437:click(['later/leads_2026-09-27.csv','Скопировать в incoming','Refresh All'])+note('Файл уже содержит одну полную строку REQ-120. Не добавляйте ещё одну копию этой заявки вручную.'),
438:flow(['Combine','Merge sources','Expand sources','Merge statuses','Expand statuses'])+note('Каждая новая строка после чтения папки проходит сохранённые Applied Steps. Настройки Merge вручную повторять не нужно.'),
439:code('REQ-120 | email | in_progress\nsource_name    Email\nchannel_group  email\nstatus_order   2\nis_final       false','КОНТРОЛЬ НОВОЙ СТРОКИ')+result('Всего 13 заявок; unmatched_sources остаётся пустым.'),
440:code('REQ-121 | youtube | new','ФАЙЛ ЗА 28 СЕНТЯБРЯ')+bullets(['Файл скопирован из later на предыдущем дополнительном шаге.','Не добавляйте youtube в sources_lookup.','Выполните Refresh All и дождитесь завершения.'])+note('Это контролируемое неизвестное значение, а не порча структуры справочника.'),
441:cards([['leads_combined · 14 строк','REQ-121 / youtube остаётся; source_name и channel_group — null.'],['unmatched_sources · 1 строка','Та же REQ-121 / youtube присутствует в отчёте.']])+result('Статус new известен: status_order = 1, is_final = false.'),
442:cards([['Заявка сохранена','В основном наборе остаются все 14 записей.'],['Проблема видна','Отдельный отчёт содержит одну неизвестную категорию источника.']]),
443:cards([['Ожидаем','request_id, created_at, utm_source.'],['Получили','lead_id, date, traffic_source.']])+note('Сейчас это разбор сценария. Рабочие CSV не переименовываем и не ломаем ради демонстрации.'),
444:bullets(['Изменилось имя или тип поля.','Появился другой формат или разделитель.','Добавился либо исчез столбец.'])+note('Schema drift — изменение структуры источника. Последствие зависит от шагов: ошибка, null, проигнорированное поле или иной результат. Поэтому сверяем и схему, и строки.'),
445:flow(['Sample File','Ожидаемая схема','Все дневные CSV'])+note('Образец не является гарантией качества остальных файлов. Совместимость подтверждают проверками источников и результата.'),
446:bullets(['Определите файл по Source.Name или списку файлов.','Найдите первый ошибочный шаг и сравните схему с предыдущим шагом.','Зафиксируйте нарушение и согласуйте исправление источника либо запроса.'])+note('Не включайте пропуск файлов с ошибками ради успешного Refresh: так можно незаметно потерять заявки.'),
447:code('incoming → helper queries → leads_combined\nsources_lookup ───────────→ leads_combined\nstatuses_lookup ──────────→ leads_combined\nleads_combined + sources_lookup → unmatched_sources','НАПРАВЛЕНИЕ: ИСТОЧНИК → ПОТРЕБИТЕЛЬ')+note('Справочники питают основной запрос. unmatched_sources зависит от основного запроса и справочника источников.'),
448:click(['Power Query Editor','View','Query Dependencies'])+bullets(['Найдите leads_combined, helper queries и два справочника.','Проследите зависимости unmatched_sources.','Проверьте направление связей; названия helpers могут отличаться.']),
449:flow(['Дневные CSV','Folder Source','Combine','Merge справочников','Основной набор','Отчёт несовпадений'])+note('Отчёт — отдельная ветка, а не замена основной таблицы.'),
450:code('result/power_query_combined.xlsx\nQueries: leads_combined, sources_lookup,\n         statuses_lookup, unmatched_sources\n+ автоматически созданные helper queries\nincoming/: 6 дневных CSV к концу практики','ЧТО СДАЁМ')+note('Финальное состояние: 14 основных строк, одна youtube-заявка в отчёте; tiktok уже известен.'),
451:checklist(['Три CSV дали 9 строк','Четвёртый CSV дал 12 после Refresh','Source.Name сохранён','Source lookup добавил два поля','Status lookup добавил два поля','После tiktok справочник содержит 5 ключей','После tiktok unmatched стал пустым','REQ-120 обогатилась автоматически','REQ-121 сохранилась в основных 14 строках','REQ-121 попала в unmatched_sources','Ключи справа уникальны','Число строк после Merge не выросло']),
452:checklist(['Папка incoming','Одинаковые заголовки CSV','Команда From Folder','Folder Preview','Список файлов в редакторе','Фильтр .csv','Команда Combine Files','Sample File dialog','Helper Queries','leads_combined','Source.Name','Новые строки после Refresh','sources_lookup','Выбор ключей Merge','Left Outer','Expand lookup','tiktok с null','Left Anti','unmatched_sources','tiktok после исправления','statuses_lookup','Query Dependencies']),
453:checklist(['Что такое Folder Source?','Зачем единая схема файлов?','Что делает Combine Files?','Зачем нужен Sample File?','Чем Append отличается от Merge?','Как устроен lookup?','Что такое ключ соединения?','Почему нужен уникальный ключ справа?','Что сохраняет Left Outer?','Что исключает Inner?','Что ищет Left Anti?','Что означает unmatched record?','Что такое schema drift?']),
454:flow(['Понедельник','+ вторник','+ среда','Заявки за три дня'])+`<p class="lead">Append: где взять ещё строки того же типа?</p>`,
455:flow(['utm_source = telegram','Справочник','channel_group = social'])+`<p class="lead">Merge: какие данные связаны с этой строкой?</p>`,
456:flow(['Новый файл','Папка','Refresh','Combine','Merge','Результат'])+note('Правила остаются прежними. Меняется содержимое источников.'),
457:cards([['Объединено','Файлы собраны, справочники подключены.'],['Ещё не доказано','Уникальность request_id, обязательные поля, даты, известные статусы и сохранность всех строк.']]),
458:flow(['Общий набор','Контроль качества','Корректные / проблемные'])+bullets(['Column Quality, дубли и обязательные поля.','Ошибки дат, неизвестные статусы, quality flags.','Сверка количества строк и контроль обновления.'])
};
const hints={360:'Полный CSV доступен в комплекте. Первую строку с заголовками сохраняем в каждом файле.',361:'REQ-104…REQ-106 — новые заявки, а не повтор предыдущего дня.',362:'tiktok оставлен специально. До слайда 421 его не добавляем в справочник.',394:'Справочник хранится в lookup вне incoming, чтобы не попасть в Combine заявок.',424:'Файл уже есть в комплекте. Заголовки: status, status_order, is_final.'};
const extraShots={363:'Несколько CSV рядом: одинаковые восемь заголовков.',382:'Основной запрос после Combine: девять заявок, заголовки не попали в строки.',411:'Строка telegram после Expand: исходный ключ и две подписи справа.'};
const stage=id=>{const n=parseInt(id);return n<365?'01 / От файла к папке':n<378?'02 / From Folder и Combine':n<390?'03 / Происхождение и Refresh':n<401?'04 / Справочник и ключи':n<416?'05 / Left Outer и Expand':n<424?'06 / Left Anti и исправление':n<432?'07 / Справочник статусов':n<443?'08 / Проверка на новых файлах':n<450?'09 / Схема и зависимости':'10 / Практика и итог';};
const deck=[];for(const s of originals){if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
const dark=new Set(['354','357','358','376','380','389','400','404','406','417','420','432','436','442','449','454','455','456','458']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>`<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${s.body||custom[s.id]||md(s.text)}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`).join('\n');
const sources=[['Объединение CSV','https://learn.microsoft.com/en-us/power-query/combine-files-csv'],['Источник Folder','https://learn.microsoft.com/en-us/power-query/connectors/folder'],['Соединения Merge','https://learn.microsoft.com/en-us/power-query/merge-queries-overview'],['Left Outer','https://learn.microsoft.com/en-us/power-query/merge-queries-left-outer'],['Left Anti','https://learn.microsoft.com/en-us/power-query/merge-queries-left-anti'],['Типы данных','https://learn.microsoft.com/en-us/power-query/data-types']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 9 · Power Query: Combine и Merge</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads pq combine"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 09<small>Папка → Combine → Merge</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(354)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>105 исходных слайдов 354–458 + ${deck.length-105} поясняющих экранов. Буква — дополнение после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика выполняется в интерфейсе Excel. Все CSV вымышленные. Список кадров и комплект файлов — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const table=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads pq combine materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 09 / МАТЕРИАЛЫ</p><h1>Из дневных CSV — в общий набор</h1><p>Combine Files собирает заявки. Merge добавляет свойства. Left Anti сохраняет отдельный отчёт несовпадений.</p>${dl('power-query-combine-lab.zip','Скачать комплект практики')}<div class="cards">${[['incoming','3 CSV на старте','9 заявок за 23–25 сентября.'],['lookup','2 справочника','Источники и статусы; tiktok пока отсутствует.'],['later','3 следующих опыта','26 сентября: +3 строки; 27: REQ-120; 28: REQ-121 / youtube.']].map(([f,t,d])=>`<article><h3>${t}</h3><p><code>${f}/</code> — ${d}</p></article>`).join('')}</div><p><a href="files/lesson_power_query_02/README.md">Порядок работы и контрольные числа</a> · <a href="SCREENSHOTS.md">Инструкция для съёмки</a> · <a href="LESSON.md">Структура и уточнения</a></p><h2>Контроль по этапам</h2><div class="table-scroll"><table><thead><tr><th>Этап</th><th>Основные строки</th><th>unmatched_sources</th></tr></thead><tbody><tr><td>3 исходных CSV</td><td>9</td><td>Ещё не создан</td></tr><tr><td>Добавлен файл 26 сентября; выполнен Anti</td><td>12</td><td>1 · REQ-108 / tiktok</td></tr><tr><td>tiktok добавлен в lookup</td><td>12</td><td>0</td></tr><tr><td>Добавлен файл 27 сентября</td><td>13</td><td>0</td></tr><tr><td>Добавлен файл 28 сентября</td><td>14</td><td>1 · REQ-121 / youtube</td></tr></tbody></table></div><p>При уникальных ключах справа оба Merge сохраняют число заявок. Финальная таблица содержит 13 столбцов. Пустой отчёт источников не доказывает качество остальных полей.</p><h2>Скриншоты · ${shots.length}</h2><p>PNG сохранять в shots/ по точному имени, затем выполнить node build.mjs. Пока вместо кадров показаны подписанные заглушки.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>Файл</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${table}</tbody></table></div><h2>Официальные источники</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}</main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# ОП.03 · Тема 9 · ${shots.length} кадров\n\nПапка: op03-informacionnye-tehnologii/lessons/09-power-query-combine-merge/shots/\n\nСнимать настоящие Excel / Power Query, Проводник и текстовый редактор. Согласовать ОС и версию Excel между кадрами, записать их в shots/evidence.json. Не заменять интерфейс рисованными картинками. Все данные в комплекте вымышленные.\n\nРаспаковать files/power-query-combine-lab.zip. Начать с трёх CSV в incoming (9 заявок). На шаге 386 скопировать из later файл за 26 сентября (12 строк). После создания Left Anti снять tiktok в отчёте; на шаге 421 дописать tiktok в исходный справочник (отчёт 0). На шаге 437 добавить файл за 27 сентября (13 строк), на шаге 439a — за 28 сентября (14 строк, youtube в отчёте). Будущие файлы и резервные копии нельзя держать внутри incoming.\n\nСохранять PNG по именам ниже. Буквенный суффикс — промежуточный шаг, нумерация исходника не меняется. После съёмки выполнить node build.mjs из папки темы, обновить evidence.json и проверить кадры в увеличении.\n\n| Экран | Исходник | Файл | Что снять | Статус |\n|---|---|---|---|---|\n`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/power-query-combine-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X','-r',zip,'lesson_power_query_02'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
