import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const code=(s,label='ПРИМЕР')=>`<figure class="code"><figcaption>${esc(label)}<button data-copy>Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const result=s=>`<aside class="result"><b>ПРОВЕРЬТЕ РЕЗУЛЬТАТ</b><span>${inline(s)}</span></aside>`;
const cards=a=>`<div class="cards">${a.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=a=>`<ol class="flow">${a.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const bullets=a=>`<ul class="bullets">${a.map(x=>`<li>${inline(x)}</li>`).join('')}</ul>`;
const checklist=a=>`<div class="checklist">${a.map(x=>`<label><input type="checkbox">${inline(x)}</label>`).join('')}</div>`;
const dl=(f,t)=>`<a class="download" href="files/${f}" download>${inline(t)} ↓</a>`;
const click=a=>`<div class="path" aria-label="Путь по меню">${a.map(x=>`<b>${inline(x)}</b>`).join('<i aria-hidden="true">→</i>')}</div>`;
function prose(text){
 const parts=text.trim().split(/\n\s*\n/).filter(Boolean),out=[];let list=[];
 const flush=()=>{if(list.length)out.push(bullets(list));list=[];};
 for(const p of parts){if(!p.includes('\n')&&p.length<145&&(/;$/.test(p)||(list.length&&/\.$/.test(p)))){list.push(p.replace(/[;.]$/,''));continue;}flush();
 if(/^\d+\. /m.test(p)){out.push(`<ol class="list">${p.split(/\n(?=\d+\. )/).map(x=>`<li>${inline(x.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`);}else out.push(`<p>${inline(p.replace(/^> /gm,'')).replace(/\n/g,'<br>')}</p>`);}
 flush();return out.join('');
}
const md=s=>s.split(/(```[\s\S]*?```)/g).map(p=>{if(!p.startsWith('```'))return prose(p);const m=p.match(/^```([^\n]*)\n([\s\S]*?)```$/);return m[2].includes('↓')&&!m[2].includes('├')?flow(m[2].trim().split(/\n?↓\n?/).map(x=>x.trim())):code(m[2],m[1]||'ПРИМЕР');}).join('');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const originals=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const p={};for(const x of m[3].split(/^## /m).slice(1)){const n=x.indexOf('\n');p[x.slice(0,n).trim()]=x.slice(n).replace(/\n---\s*$/,'').trim();}return {id:m[1],title:p['Заголовок'],text:p['Текст'],shot:p['Скриншот'],accent:p['Акцент']||'',remark:p['Примечание']||''};});
if(originals.length!==129||originals.some((s,i)=>+s.id!==606+i))throw Error('Нарушен порядок 606–734');
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${inline(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const extra=(id,title,steps,shot,check)=>({id,title,body:bullets(steps)+(check?result(check):''),shot});
const extras={
614:[extra('614a','Подготовьте источники и контрольные числа',['Откройте ресурс GA4 предыдущей темы и Google Sheets с листом leads. Выберите завершённый период.','Запишите период, часовой пояс, Sessions, события generate_lead и число уникальных непустых request_id.','Скачайте dashboard-spec.md в материалах. Внесите имена источников и контрольные числа до построения графиков.'],'GA4 и Sheets: один период, исходные показатели; заполненная шапка спецификации.','Примеры на слайдах условные. Они не заменяют значения вашего ресурса.')],
620:[extra('620a','Проверьте подключённый ресурс',['Resource → Manage added data sources → Edit у Google Analytics.','Назовите источник «GA4 · Funnel». Проверьте Property и поля Sessions, Active users, Event name.','Вернитесь в отчёт. В настройках каждой новой диаграммы сверяйте Data source.'],'Список источников отчёта и GA4 fields с названием GA4 · Funnel.')],
625:[{id:'625a',title:'Разместите блоки до настройки графиков',body:`<div class="wireframe"><div class="wf-controls">Период · Source · Campaign</div><div class="wf-kpis"><span>Sessions</span><span>Active users</span><span>GA4 Lead Events</span></div><div class="wf-trend">Динамика Sessions и Active users</div><div class="wf-bottom"><span>Sources</span><span>Campaigns</span><span>Content / Devices</span></div></div>`+note('Это схема расположения, не скриншот Data Studio. Оставьте единые отступы, выровняйте заголовки и подпишите период.')}],
630:[extra('630a','Сохраните фильтр только на нужной карточке',['В редакторе фильтра задайте имя «GA4 · generate_lead» → Save.','Убедитесь, что фильтр появился у карточки Key events. Карточка Sessions остаётся без Event name-фильтра.','Сверьте результат с выбранным событием в GA4 за тот же период. Если событие не отмечено Key event, используйте Event count и подпишите это.'],'Карточка generate_lead с фильтром; рядом Sessions без него.')],
632:[extra('632a','Проверьте область периода',['Задайте диапазон с датами ваших тестов. У диаграмм оставьте Default date range = Auto.','Перейдите в View и смените период на другой завершённый интервал.','Вернитесь к основному периоду и запишите, какие карточки изменились. Фиксированный период диаграммы может перекрывать control.'],'Date range control и настройки Auto у карточки; два состояния периода.')],
647:[extra('647a','Сбросьте выбор после cross-filter',['Повторно нажмите выбранную категорию или используйте доступную команду сброса.','Очистите Source и Campaign controls. Верните исходный период.','Проверьте исходные контрольные значения. Скрытое выделение не должно оставаться при переходе к следующему опыту.'],'Page 1 после сброса: controls без выбранных категорий и исходные KPI.')],
651:[extra('651a','Проверьте качество листа leads',['Одна строка — одно текущее состояние заявки. request_id непустой; дубли и конфликтующие статусы разберите до подключения.','created_at должен быть датой, а не смесью строк разных форматов. Ключи utm_source и utm_campaign — согласованные значения.','Не подключайте демонстрационные CSV темы 8 вместо текущих заявок. При необходимости примените освоенные правила очистки к отдельной копии.'],'Лист leads: девять заголовков, даты, идентификаторы и статусы; скрыть имя/email.','COUNT_DISTINCT скрывает повтор ID в общем количестве, но не исправляет разные статусы или кампании одного ID.')],
657:[extra('657a','Если created_at распознан как Text',['Посмотрите фактическое значение и формат в исходной таблице. Для настоящих дат Sheets задайте Date & Time в источнике.','Если это текст, создайте отдельное поле разбора под один известный формат; пример формулы — в files/formulas.md.','Проверьте несколько дат, начало и конец дня. Для ISO-строк со смещением сначала согласуйте часовой пояс и формат источника.'],'Редактор поля даты: исходное значение, выбранный тип либо формула разбора и результат.')],
659:[extra('659a','Сохраните Lead Count и проверьте результат',['Resource → Manage added data sources → Sheets → Edit → Add a field.','Имя Lead Count; формула COUNT_DISTINCT(request_id). Сохраните, вернитесь в отчёт.','Сравните с уникальными непустыми ID исходного листа. Пустые ID исключите до расчёта; Record Count здесь не равно числу уникальных заявок.'],'Редактор вычисляемого Lead Count и поле после сохранения.')],
661:[extra('661a','Добавьте период на страницу Leads',['Для карточек и таблиц Sheets укажите Date range dimension = created_at, Default date range = Auto.','Добавьте Date range control на Page 2. Выберите тот же диапазон, что на Page 1.','Сверьте Actual Leads с отбором created_at в Sheets. Не оставляйте «всё время» при сравнении с неделей GA4.'],'Page 2: control периода и created_at в Date range dimension карточки.')],
664:[extra('664a','Проверьте фильтры скопированных карточек',['При копировании Done фильтр status=done копируется тоже. У New удалите его и задайте status=new.','Для In Progress оставьте только status=in_progress. У Actual Leads не должно быть status-фильтра.','Если есть rejected, добавьте пятую карточку либо покажите его в Status chart. Сумма трёх статусов может быть меньше всех заявок.'],'Четыре карточки и их разные status-фильтры; Actual Leads без фильтра статуса.')],
672:[extra('672a','Добавьте фильтр кампании на Page 2',['Add a control → Drop-down list. Источник — Sheets · Leads. Поле — utm_campaign.','Выберите instagram в utm_source и backend_guide в utm_campaign. Проверьте таблицы и карточки.','Очистите controls перед общим сравнением. Page 2 использует собственные поля Sheets.'],'Page 2: source и campaign controls с двумя выбранными условиями.')],
678:[extra('678a','Согласуйте значения ключей',['Сравните Session source с utm_source, Session campaign с utm_campaign на реальных строках.','Для основного опыта используем instagram + backend_guide. Уберите случайные пробелы; регистр значений должен совпадать.','(direct), direct, (not set) и not_set не равны автоматически. Переименовывайте только по документированному правилу, не превращайте пропуски в известную кампанию.'],'Две контрольные таблицы с source/campaign; совпадающие и несовпадающие пары видны.')],
682:[extra('682a','Задайте одинаковый период до JOIN',['В таблице GA4 настройте Date range dimension = Date, в Sheets — created_at. Обе таблицы: Date range = Auto.','В диаграмме и control Page 3 установите общий период. Сверьте обе части отдельно.','Dimensions обеих таблиц пока только Source + Campaign. Не добавляйте request_id, status, отдельный день или Device: они меняют детализацию.'],'Blend editor: Date / created_at как поля диапазона; Auto; по два измерения на сторону.','Если интерфейс требует добавить Date в Dimensions, добавьте дату с обеих сторон и третье условие равенства дат; сверяйте уже дневной набор отдельно.')],
685:[extra('685a','Примените соединение и проверьте NULL',['В Join configuration выберите Left Outer → Save. GA4 остаётся слева.','Пара без строки Sheets останется, но Lead Count будет NULL/прочерк, а не доказанный ноль.','Проверьте ключи и даты. Только подтверждённое отсутствие заявок можно отображать как 0.'],'Join configuration: Left Outer и два ключа; результат с отсутствующим совпадением.')],
688:[extra('688a','Отделите generate_lead от всех Key events',['Базовая таблица показывает Sessions, All Key Events и Actual Leads. Для отдельного generate_lead откройте Blend → Join another table.','Выберите тот же GA4-источник: Dimensions source/campaign; Metric Event count, имя «GA4 Lead Events»; фильтр Event name = generate_lead только внутри этой третьей таблицы.','Соедините её Left Outer по source/campaign с полями первой GA4-таблицы. Период Auto, поле Date. Save; добавьте метрику в итоговую таблицу.'],'Третья таблица Blend: GA4 с фильтром generate_lead, Event count, два ключа и Left Outer.','Источник данных по-прежнему один GA4, но таблиц в Blend теперь три. Трафик первой таблицы не фильтруется событием.'),extra('688b','Сверьте итог после Blend',['Сравните Sessions каждой пары с отдельной таблицей GA4. Значение не должно увеличиться после JOIN.','Сравните Lead Count с отдельной таблицей Sheets на той же паре и датах.','Проверьте пару без заявки и заявку без пары GA4. Правые записи без совпадения Left Outer не показывает.'],'Три таблицы рядом: GA4 отдельно, Sheets отдельно, Blend для одинаковых ключей и дат.')],
692:[{id:'692a',title:'Посчитайте Done без добавления status в ключи',body:click(['Sheets data source','Add a field','Done Count'])+code('COUNT_DISTINCT(\n  CASE WHEN status = "done" THEN request_id\n  ELSE NULL END\n)','DONE COUNT')+bullets(['Сохраните поле в Sheets-источнике.','В Blend добавьте Done Count как метрику второй таблицы; Dimensions не меняйте.','В итоговой таблице выведите Done Count рядом с Lead Count.'])+result('status не включён в Dimensions, значит одна пара source/campaign не разделилась на несколько строк.'),shot:'Done Count в источнике Sheets, затем среди метрик Sheets-таблицы Blend.'}],
695:[{id:'695a',title:'Создайте отношение после проверки соединения',body:click(['Blended table','Add metric','Create field'])+code('CASE\n  WHEN SUM(Sessions) > 0\n  THEN SUM(Lead Count) / SUM(Sessions)\n  ELSE NULL\nEND','ACTUAL LEADS / SESSION')+bullets(['Выбирайте поля Blend из подсказок редактора. Сохраните поле с типом Percent.','Формула относится к агрегированному Blend, а не к исходному GA4-источнику.','Проверьте строку вручную и общий итог как отношение сумм, не среднее процентов.'])+note('Если Lead Count отсутствует из-за несовпадения, не заменяйте NULL нулём до сверки. При Sessions = 0 показатель не определён.'),shot:'Вычисляемое поле диаграммы Blend, тип Percent и ручная сверка одной строки.'}],
697:[{id:'697a',title:'Проверьте, как ключи умножают строки',body:`<div class="join-lab"><p>Условный набор: три кампании Instagram; слева 180 Sessions. Выберите ключи и детализацию справа.</p><div class="lab-controls"><label>Ключи<select id="join-keys"><option value="both">Source + Campaign</option><option value="source">Только Source</option></select></label><label>Правая таблица<select id="join-grain"><option value="grouped">По Source + Campaign</option><option value="raw">Отдельные заявки</option></select></label></div><div id="join-result" aria-live="polite"></div></div>`+note('Это локальная модель JOIN, не скриншот Data Studio. Правильная формула не исправляет умножение строк.') }],
700:[extra('700a','Добавьте controls именно для Blend',['На Page 3 добавьте Source и Campaign drop-down, выбрав Blend как Data source и ключевые поля первой таблицы.','Добавьте отдельный Date range control. На Page 1/2 оставьте свои controls на уровне страницы.','Проверьте каждую страницу в View. Одинаковая подпись поля не гарантирует одинаковый внутренний ID.'],'Page 3: controls используют Blend; переключение страниц не переносит чужой source-фильтр.')],
702:[extra('702a','Проверьте обновление и часовой пояс',['Согласуйте дату GA4 и created_at по часовому поясу, особенно около полуночи. Запишите выбранное правило.','Обновите данные отчёта доступной командой Refresh data и учтите cache / data freshness источников.','Если GA4 показывает ошибку quota, сократите запросы и дождитесь восстановления. Не трактуйте ошибку или устаревший кеш как ноль.'],'Период, сведения об обновлении и дата на обеих сторонах; фактическая ошибка при её наличии.')],
714:[extra('714a','Проверьте заявки, которые Left Outer скрыл',['На Page 2 посмотрите пары source/campaign с заявками. Сопоставьте их со списком Page 3.','Записи, у которых нет ключа GA4 за период, занесите в отдельный список сверки.','Не называйте сумму Lead Count на Page 3 всеми заявками компании, пока правые несовпадения не учтены.'],'Page 2 и Page 3 для одного периода; список пар Sheets без соответствия в GA4.')],
718:[extra('718a','Сначала проверьте доступ, затем приглашайте',['В Share проверьте текущий доступ и роль Viewer/Editor. Для демонстрации достаточно снять настройки без отправки приглашения.','До предоставления ссылки проверьте Data credentials обоих источников.','Для реальной передачи отчёта выберите конкретного согласованного получателя и минимально нужную роль. Не включайте публичный доступ к данным заявок.'],'Share dialog: текущий ограниченный доступ и роли; без лишних персональных данных.')],
723:[extra('723a','Найдите Data credentials у каждого источника',['Resource → Manage added data sources → Edit. Вверху редактора откройте Data credentials.','Проверьте доступные варианты для GA4 и Sheets отдельно; подпишите, чьи права используются.','Проверку View выполняйте с разрешённым тестовым зрителем. Успешное открытие отчёта автором не подтверждает доступ зрителя.'],'Редакторы GA4 и Sheets: фактическая модель credentials без секретов.')],
725:[extra('725a','Уберите лишние поля до передачи отчёта',['В charts не выводите name и email: для этой задачи нужны дата, источник, кампания, статус и идентификатор.','Скрытие колонок диаграммы не является защитой всего источника. Для внешнего отчёта подготовьте отдельный ограниченный набор и соответствующий доступ.','Проверьте таблицы, экспорт и сведения об источниках с учётом разрешённой роли.'],'Страница Leads без name/email; настройки ограниченного набора и проверка экспорта.')],
729:[extra('729a','Сдайте воспроизводимый результат',['В dashboard-spec.md запишите ссылку с ограниченным доступом, имена источников, период, ключи и формулы.','Приложите кадры трёх страниц и настройки Blend. Заполните reconciliation.csv фактическими числами.','Добавьте наблюдение, возможную причину расхождения и следующий проверяемый шаг. Если данных нет, сохраните настройки и ограничение вместо выдуманного результата.'],'Заполненная спецификация отчёта и сверка исходных/объединённых показателей.')]
};
const custom={
606:cards([['GA4 · тема 10','Исследовали источники, события, воронку и пути пользователей.'],['Google Sheets · темы 7–8','Сохраняем заявки и готовим данные к анализу.']])+result('Соберём показатели двух источников в отчёт с тремя страницами.'),
607:flow(['Looker Studio','Data Studio'])+`<p>В апреле 2026 Google вернул название <strong>Data Studio</strong>. Актуальный адрес — <a href="https://datastudio.google.com/" target="_blank" rel="noopener noreferrer">datastudio.google.com</a>.</p>`+note('Старый домен перенаправляет на новый. Переименование подтверждено официальной документацией Google; ссылки — в материалах.'),
608:cards([['GA4','Источники, кампании и события.'],['Sheets · leads','Заявки и текущие статусы.'],['Sheets · подготовка данных','Правила очистки из актуальной темы 8.']])+`<p class="lead">Общий dashboard показывает согласованные показатели рядом.</p>`,
609:`<p class="lead">Dashboard — представление ключевых показателей для конкретной задачи.</p>`+cards([['Состояние','Сколько сеансов и заявок за период?'],['Изменение','Что выросло или снизилось?'],['Детализация','Какие источники, кампании и статусы требуют проверки?']]),
610:cards([['01 · Web Analytics','GA4: трафик, события, кампании и устройства.'],['02 · Leads','Sheets: уникальные заявки и статусы.'],['03 · Marketing → Business','Blend: агрегаты по source + campaign за общий период.']]),
611:flow(['GA4 + Google Sheets','Connectors','Data sources','Report'])+note('В этой практике Data Studio читает существующие наборы. Сбор событий и запись формы остаются в ранее настроенных системах.'),
615:`<p>Откройте <a href="https://datastudio.google.com/" target="_blank" rel="noopener noreferrer">datastudio.google.com</a> под аккаунтом с доступом к нужному ресурсу GA4 и таблице заявок.</p>`+result('Проверьте выбранный Google-аккаунт. Не создавайте новый ресурс аналитики вместо существующего.'),
616:click(['Create','Report'])+result('Открылся новый отчёт и предложение добавить данные. При первом входе завершите начальную настройку продукта.'),
617:click(['Add data to report','Google Analytics'])+note('Выбираем встроенный connector Google. Не подключаем сторонний платный коннектор для этой задачи.'),
619:click(['Account','Нужный GA4 Property'])+result('Имя и ID ресурса совпадают с темой 10.'),
620:click(['Add','Add to report'])+result('На canvas появилась первая диаграмма, источник доступен в панели Data.'),
624:click(['Page','Manage pages','Меню первой страницы','Rename'])+code('01 — Web Analytics','ИМЯ СТРАНИЦЫ'),
625:cards([['Верх','Период, фильтры и три KPI.'],['Середина','Динамика Sessions и Active users.'],['Низ','Источники, кампании, контент и устройства.']]),
626:cards([['Sessions · 428','Scorecard показывает один показатель за выбранный период.']])+note('Число условное. У карточки должны быть понятная подпись, единица и период.'),
627:click(['Add a chart','Scorecard','Поставить на canvas'])+code('Data source: GA4 · Funnel\nMetric: Sessions','SETUP')+result('Выделите карточку и проверьте настройки справа.'),
628:click(['Карточка Sessions','Копировать / вставить','Metric → Active users'])+note('Меняем метрику и подпись копии. Sessions и Active users измеряют разные сущности.'),
631:code('GA4 Lead Events','ПОДПИСЬ КАРТОЧКИ')+note('Метрика здесь — Key events с фильтром generate_lead. Событие текущего сайта означает submit, а не подтверждённую запись в таблицу.'),
632:click(['Add a control','Date range control'])+result('Разместите рядом с KPI. Исходный диапазон должен включать данные проекта.'),
638:cards([['Таблица трафика','Sessions, Active users, All Key Events — без общего Event name-фильтра.'],['Отдельная карточка','generate_lead можно выделить фильтром только её компонента.']])+note('Фильтр Event name на всей таблице меняет и набор данных для Sessions. Нельзя считать такой столбец всем трафиком.'),
640:click(['Add a chart','Table'])+code('Data source: GA4 · Funnel\nDimension: Session manual ad content\nMetrics: Sessions, Active users','CONTENT')+note('reel01 появляется только при соответствующих UTM-переходах. (not set) — отсутствие значения, а не название ролика.'),
643:click(['Add a control','Drop-down list'])+code('Data source: GA4 · Funnel\nControl field: Session source','SOURCE CONTROL')+result('Проверьте значения instagram, (direct), google — по фактическим данным.'),
646:click(['Выбрать поддерживаемый chart','Properties → Setup','Chart interactions','Cross-filtering'])+note('Для опыта включите взаимодействие у таблицы или диаграммы источников. Проверка выполняется в View.'),
651:code('request_id · created_at · name · email\ndirection · utm_source · utm_medium\nutm_campaign · status','ДЕВЯТЬ ПОЛЕЙ LEADS')+note('Это лист заявок из темы 7. В графиках не нужны name/email. В этой схеме нет utm_content: сравнение конкретного Reel остаётся на странице GA4.'),
654:click(['Edit report','Add data','Google Sheets'])+result('Выберите GA4 Analytics Lab — Leads или свою таблицу того же проекта.'),
656:click(['Worksheet → leads','Use first row as headers','Add','Add to report'])+result('Источник назовите Sheets · Leads. Проверьте поля перед добавлением графиков.'),
659:code('COUNT_DISTINCT(request_id)','LEAD COUNT')+note('Вычисляемое поле создаём в источнике Sheets, чтобы использовать его в разных компонентах и Blend. Следующий экран показывает путь сохранения.'),
660:cards([['11 строк','Одна заявка случайно повторилась.'],['10 разных ID','COUNT_DISTINCT считает десять идентификаторов.']])+note('Условный пример. Если одинаковый ID имеет разные status или campaign, разрезы останутся противоречивыми — источник нужно исправить.'),
662:click(['Копия Actual Leads','Add a filter','Include → status → Equal to → done'])+result('Подпись Done. Это текущий статус заявки, а не дата её завершения и не выручка.'),
666:table(['Status','Количество · условный пример'],[['new','42'],['in_progress','15'],['done','9'],['rejected','4']])+note('Сравнение длины столбцов помогает увидеть размеры категорий. Для реальных данных показываем все имеющиеся статусы.'),
669:click(['Add a chart','Time series'])+code('Data source: Sheets · Leads\nDimension: created_at · Day\nMetric: Lead Count\nDate range dimension: created_at','ДИНАМИКА СОЗДАНИЯ ЗАЯВОК')+note('На оси — день создания. Для динамики завершения нужен отдельный completed_at, которого сейчас нет.'),
674:table(['Источник','Sessions','GA4 Lead Events','Actual Leads','Done'],[['Instagram · пример','100','8','7','3']])+note('Это условное сопоставление агрегатов. Оно не доказывает соответствие каждого события каждой записи.'),
677:table(['GA4','Sheets'],[['Session source','utm_source'],['Session campaign','utm_campaign']])+result('Две пары полей задают ключ соединения. Значения и период должны быть согласованы.'),
680:click(['Resource','Manage blended data','Add a blend'])+result('Настраиваем таблицы и их соединение внутри отчёта.'),
681:code('Dimensions:\n  Session source\n  Session campaign\nMetrics:\n  Sessions\n  Active users\n  Key events','TABLE 1 · GA4 TRAFFIC')+note('Key events подпишите All Key Events. Для основного трафика Event name-фильтр не устанавливаем.'),
682:code('Dimensions:\n  utm_source\n  utm_campaign\nMetric:\n  Lead Count','TABLE 2 · SHEETS LEADS')+result('Одна строка после агрегации — одна пара source/campaign. request_id в Dimensions не добавляем.'),
685:cards([['Слева · GA4','Сохраняем все пары источника и кампании за выбранный период.'],['Справа · Sheets','Добавляем агрегат заявок при совпадении обоих ключей.']])+note('Отсутствие совпадения даёт NULL. Заявки справа без пары GA4 в этот результат не попадут.'),
686:table(['Campaign','Sessions','Lead Count'],[['backend_guide','100','8'],['frontend_guide','50','4'],['test_campaign','30','NULL']])+note('Условный пример Left Outer. У test_campaign есть трафик, но нет совпавшей строки справа. Ноль можно показать после проверки причины отсутствия.'),
688:click(['Add a chart','Table','Data source → сохранённый Blend'])+code('Dimensions: Session source, Session campaign\nMetrics: Sessions, Key events, Lead Count','БАЗОВАЯ ТАБЛИЦА')+result('Подписи: Sessions, All Key Events, Actual Leads. Следующий шаг добавит отдельное generate_lead.'),
689:table(['Campaign','Sessions','GA4 Lead Events','Actual Leads'],[['backend_guide','100','9','8'],['frontend_guide','70','6','6'],['analytics_guide','40','4','3']])+note('Условные числа. GA4 Lead Events — Event count только generate_lead из третьей таблицы, а не сумма всех Key events.'),
692:flow(['Sessions','GA4 Lead Events','Actual Leads','Done'])+note('Это сопоставление разных показателей. Для Done добавляем условный подсчёт ID, сохраняя прежнюю детализацию source/campaign.'),
693:table(['Sessions','generate_lead · события','Заявки · уникальные ID','Из них сейчас done'],[['100','9','8','3']])+note('Условный пример. Это не пользовательская Funnel Exploration: единицы на этапах различаются.'),
695:code('8 уникальных заявок / 100 сеансов = 0,08','ACTUAL LEADS / SESSION')+note('Отображение 8% удобно, но это отношение агрегатов двух систем, а не доказанная вероятность конверсии одного сеанса. Оно может превысить 100%.'),
696:flow(['100 Sessions','JOIN к 3 строкам справа','100 + 100 + 100','Ошибочные 300'])+note('Перед вычислением отношений сначала проверяем ключи и число строк после соединения.'),
697:cards([['До агрегации Sheets','Одна строка — заявка.'],['Перед JOIN','Одна строка — source + campaign с подсчитанными метриками.'],['После JOIN','Та же детализация должна сохраниться на обеих сторонах.']])+note('Если добавить status справа, одна кампания может получить несколько строк и повторить Sessions.'),
701:table(['Страница / таблица','Date range dimension'],[['GA4','Date'],['Sheets','created_at'],['Blend','Date слева; created_at справа; общий диапазон']])+result('Control работает только с настроенным полем даты и компонентами, которые принимают его диапазон.'),
704:cards([['Page 1','Sessions · Active users · GA4 Lead Events.'],['Page 2','Actual Leads · New · In Progress · Done.'],['Page 3','Таблица агрегатов по source/campaign, подписи периода и показателей.']])+note('Не суммируйте Active users по кампаниям: один пользователь может входить в несколько групп.'),
709:cards([['Нейтральный','Основные значения и подписи.'],['Синий','Выбранная группа или основной показатель.'],['Предупреждение','Ошибка данных, несовпадение или ограничение.']])+note('Цвет дополняется текстом. Одинаковый статус или показатель обозначайте последовательно.'),
714:code('Source: instagram\nCampaign: backend_guide\nОдин период на обеих сторонах','ПРОВЕРКА PAGE 3')+bullets(['Сравните Sessions с GA4, Actual Leads с Sheets.','All Key Events и GA4 Lead Events смотрите отдельно.','При несовпадении сначала проверьте ключи, даты и детализацию.']),
716:table(['Кампания','Sessions','Actual Leads','Done'],[['A','1000','40','2'],['B','300','25','10']])+note('Условный пример: A даёт больше заявок, B — больше заявок со статусом done. Для вывода об экономической эффективности ещё нужны затраты, ценность результата и сопоставимые сроки.'),
718:click(['Share','Проверить текущий доступ','Выбрать роль'])+result('Viewer — для просмотра, Editor — для изменения отчёта. Перед приглашением проверяем права на данные.'),
722:flow(['Зритель отчёта','Credentials владельца источника','Разрешённые данные'])+note('Отсутствие у зрителя прямого доступа к Sheets не гарантирует, что он не увидит данные через отчёт. Проверяйте состав источника и доступ к самому отчёту.'),
729:cards([['Три страницы','Web Analytics, Leads, Marketing → Business.'],['Два источника','GA4 и Google Sheets. Один GA4-источник используется в двух таблицах Blend.'],['Один Blend','Трафик + заявки + отдельно generate_lead. Done Count добавлен метрикой Sheets.']]),
730:checklist(['Home, connector и GA4 Property','Page 1: KPI, event filter, период, динамика','Sources, Campaigns, Content, устройства','Controls и cross-filter в View','Sheets connector, worksheet и типы полей','Lead Count, статусы, дата и controls Page 2','Blend: таблицы, ключи, Left Outer и периоды','GA4 Lead Events и Done Count','Сверка исходников с Blend и правых несовпадений','Три страницы в View, Share и Data credentials'])+`<p><a href="materials.html">Все кадры по шагам и комплект практики →</a></p>`,
731:cards([['Модель отчёта','Connector, Data Source, Report, страницы и компоненты.'],['Показатели','Scorecard, COUNT_DISTINCT, Calculated Field, события и заявки.'],['Интерактивность','Date range, Filter, Control, Cross-filtering и область действия.'],['Соединение','Source + Campaign, Left Outer, NULL, детализация и умножение строк.'],['Доступ','Viewer/Editor, Data credentials, минимизация данных и проверка зрителем.']]),
732:flow(['Instagram → ManyChat','Сайт с UTM'])+cards([['GA4 → Data Studio','Трафик, кампании, события.'],['Форма → Sheets → Data Studio','Заявки, даты и текущие статусы.']])+result('Сопоставляем агрегаты по согласованным ключам и периоду. Автоматического соединения по личности пользователя здесь нет.'),
733:bullets(['Как источники отличаются по сеансам и заявкам?','Почему число событий отличается от сохранённых ID?','Какая доля созданных заявок сейчас имеет статус done?','Какие данные нужны, чтобы проверить гипотезу о расхождении?'])
};
const hints={618:'Экран может не появиться, если разрешение уже предоставлено. Не создавайте искусственный повтор авторизации ради кадра.',628:'После копирования проверьте источник, метрику, подпись и унаследованные фильтры.',634:'Dimension Date; metric Sessions; источник GA4. Для временного ряда используем дату, а не текст.',635:'Две линии обозначают разные метрики; проверьте легенду и масштаб.',637:'Столбец Key events содержит все отмеченные ключевые события. В этой таблице не называем его Leads.',648:'Снимите страницу целиком в View с видимым периодом и выбранными фильтрами.',662:'Статус done означает принятое в процессе завершение. Без определения результата нельзя автоматически назвать его продажей.',663:'У копии удалите прежний status-фильтр, иначе done AND new даст пустой результат.',668:'Показывайте фактические кампании; отсутствие frontend_guide не является ошибкой настройки.',670:'Смена типа не превращает произвольный текст в правильную дату. При ошибке разбирайте формат источника.',673:'Сверьте Actual Leads с исходным листом за тот же период. Имя и email на странице не нужны.',687:'После Save проверьте порядок таблиц и пары ключей ещё раз.',690:'Дополнительно возможны блокировка аналитики, различие правил атрибуции, часовых поясов и свежести источников.',698:'ID должен быть непустым и стабильным. COUNT_DISTINCT не восстанавливает отсутствующий ID.',702:'Период created_at выбирает созданные заявки с их текущими статусами. Это не число завершений за тот же период.',710:'Проверьте также сброс всех controls и возвращение контрольных чисел.',721:'Модель credentials проверяется отдельно у каждого источника, не только в Share отчёта.',728:'В CRM понадобится сопоставление полей и правила обновления, чтобы не создать дубли заявок.'};
const extraShots={625:'Макет Page 1 в редакторе: верхние KPI, controls, место для динамики и таблиц.',631:'Подпись GA4 Lead Events на карточке и её выбранная метрика.',648:'Page 1 целиком в View с периодом и фильтрами.',651:'Google Sheets leads: структура из девяти полей; name/email скрыты.',673:'Page 2 целиком в View: Actual Leads, статусы, динамика и controls.',685:'Join configuration: Left Outer, GA4 слева.',692:'Итоговая таблица с Lead Count и Done Count.',695:'Отношение Actual Leads / Sessions в Blend и контроль ручного расчёта.',701:'created_at как Date range dimension у компонента Sheets.',721:'Report permissions и Data credentials как отдельные настройки.',729:'Три страницы отчёта и список двух источников плюс Blend.'};
const titles={607:'Актуальное название — Data Studio',608:'Показатели находятся в разных системах',609:'Назначение dashboard',611:'Подключаем уже собранные данные',625:'Структура первой страницы',631:'Подпишите, что считает карточка',638:'Все Key events и событие generate_lead',660:'Уникальные заявки и количество строк',662:'Шаг 29. Заявки со статусом done',674:'Сопоставляем два источника',685:'Шаг 42. Сохраняем строки GA4',689:'События и заявки в общей таблице',693:'От трафика к обработке заявок',695:'Заявки на сеанс: отношение агрегатов',696:'Проверка результата соединения',697:'Детализация перед JOIN',700:'Отдельные controls для каждой страницы',707:'Выбираем визуализацию под вопрос',721:'Доступ к отчёту и доступ к данным',727:'Когда таблице не хватает функций',733:'Вопросы к общему отчёту'};
const stage=id=>{const n=parseInt(id);return n<615?'01 / Задача и источники':n<625?'02 / Первый отчёт':n<638?'03 / KPI и динамика':n<649?'04 / Разрезы и controls':n<661?'05 / Google Sheets':n<674?'06 / Заявки и статусы':n<689?'07 / Blend и ключи':n<699?'08 / Расчёты и детализация':n<710?'09 / Фильтры и оформление':n<718?'10 / Проверка результата':n<729?'11 / Доступ и следующий процесс':'12 / Сдача и итог';};
const deck=[];for(const s of originals){if(titles[s.id])s.title=titles[s.id];if(extraShots[s.id])s.shot=extraShots[s.id];deck.push(s,...(extras[s.id]||[]));}
const dark=new Set(['606','610','614','622','625','633','641','648','649','658','674','676','678','689','693','697','699','703','707','715','717','721','726','729','732','734']);
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=deck.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:deck.indexOf(s)+1,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent||'',status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
const shot=s=>{const f=`${s.id}-shot.png`;return `<figure class="shot">${fs.existsSync(path.join(root,'shots',f))?`<button data-zoom aria-label="Увеличить скриншот"><img src="shots/${f}" alt="${esc(s.shot)}" loading="lazy"></button>`:`<div class="shot-placeholder"><small>МЕСТО ДЛЯ КАДРА ${s.id}</small><span class="camera" aria-hidden="true">▣</span><strong>${inline(s.shot)}</strong><code>shots/${f}</code><small>Настоящий скриншот будет добавлен после съёмки</small></div>`}<figcaption>${esc(f)}${s.accent?' · '+inline(s.accent):''}</figcaption></figure>`;};
const html=deck.map((s,i)=>`<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>${/\D/.test(s.id)?'ДОПОЛНЕНИЕ':'ИСХОДНИК'} ${s.id} · ${i+1} / ${deck.length}</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${s.body||custom[s.id]||md(s.text)}${hints[s.id]?note(hints[s.id]):''}</div>${s.shot?shot(s):''}</div></div></section>`).join('\n');
const sources=[
['Название Data Studio','https://docs.cloud.google.com/data-studio/welcome'],
['Подключение GA4','https://docs.cloud.google.com/data-studio/connect-to-google-analytics'],
['Подключение Google Sheets','https://docs.cloud.google.com/data-studio/connect-to-google-sheets'],
['Создание Blend','https://docs.cloud.google.com/data-studio/create-edit-and-manage-blends'],
['Агрегация и порядок обработки Blend','https://docs.cloud.google.com/data-studio/blending-tips-and-advanced-concepts'],
['COUNT_DISTINCT','https://docs.cloud.google.com/data-studio/countdistinct'],
['Разбор текстовой даты','https://docs.cloud.google.com/data-studio/parsedatetime'],
['Условное выражение CASE','https://docs.cloud.google.com/data-studio/case-searched'],
['Агрегация','https://docs.cloud.google.com/data-studio/aggregation-article'],
['Controls и внутренние ID полей','https://docs.cloud.google.com/data-studio/about-controls'],
['Data credentials','https://docs.cloud.google.com/data-studio/data-credentials'],
['Ошибки и квоты','https://docs.cloud.google.com/data-studio/troubleshooting-guide']];
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 11 · Data Studio: GA4 и заявки</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads dashboard"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 11<small>GA4 + Sheets → dashboard</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / ${deck.length}</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(606)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="${deck.length}"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>129 исходных слайдов 606–734 + ${deck.length-129} поясняющих экранов. Буква — дополнение после соответствующего слайда.</p><div class="contents">${deck.map((s,i)=>`<button data-go="${s.id}"><b>${i+1}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Практика продолжает ресурс предыдущих тем. Числа примеров условные. Проверено по официальной документации 08.10.2026. Реальные кадры добавляются после съёмки. Список кадров и комплект — в материалах.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const shotTable=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen)} ${inline(s.accent)}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads dashboard materials"><main><a href="index.html">← К презентации</a><p class="kicker">ОП.03 / ТЕМА 11 / МАТЕРИАЛЫ</p><h1>Data Studio: GA4 и заявки</h1><p>${deck.length} экранов: 129 исходных слайдов 606–734 и ${deck.length-129} промежуточных шагов.</p>${dl('data-studio-lab.zip','Скачать комплект практики')}<p><a href="files/dashboard-spec.md">Спецификация для заполнения</a> · <a href="files/formulas.md">Формулы и условия</a> · <a href="files/README.md">Порядок работы</a> · <a href="SCREENSHOTS.md">Кадры / инструкция Claude</a></p>${cards([['Page 1 · GA4','KPI, временной ряд, source/campaign/content, устройства и controls.'],['Page 2 · Leads','Уникальные ID, текущие статусы, дата создания и фильтры Sheets.'],['Page 3 · Blend','Две пары ключей, общий период, проверка строк, события и Done Count.']])}<h2>Контракт соединения</h2>${table(['Часть','Детализация','Показатели'],[['GA4 Traffic','Source + Campaign за период','Sessions, Active users, All Key Events'],['Sheets Leads','Source + Campaign за период','Lead Count, Done Count'],['GA4 Lead Events','Source + Campaign за период; фильтр generate_lead','Event count']])}<p>GA4 слева; обе следующие таблицы присоединяются Left Outer по ключам первой. Дата используется для отбора периода, а не добавляется случайно в детализацию. Это сопоставление агрегатов, не соединение пользователей по ID.</p><h2>Модель JOIN</h2><p>На <a href="index.html#697a">слайде 697a</a> можно сравнить ключ Source с Source + Campaign и отдельные заявки с агрегатами. Числа модели вымышлены. Она не отправляет запросы в аккаунты.</p><h2>Скриншоты · ${shots.length}</h2><p>Поместите реальные PNG в shots/ и выполните node build.mjs. Номера с буквами — промежуточные шаги; все позиции сохранены в deck.json.</p><div class="table-scroll"><table><thead><tr><th>Экран / исходник</th><th>PNG</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${shotTable}</tbody></table></div><h2>Официальные источники</h2>${sources.map(([t,u])=>`<p><a href="${u}">${t}</a></p>`).join('')}<p>Документация проверена 08.10.2026. Формулы и интерфейсные настройки требуют проверки на фактических полях вашего отчёта.</p></main></body></html>`);
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2)+'\n');
fs.writeFileSync(path.join(root,'deck.json'),JSON.stringify(deck.map((s,i)=>({position:i+1,id:s.id,title:s.title,stage:stage(s.id),screenshot:s.shot?`shots/${s.id}-shot.png`:null})),null,2)+'\n');
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# Тема 11 · Data Studio · ${shots.length} кадров

## Инструкция для Claude

Сними настоящие экраны Data Studio, GA4 и Google Sheets по порядку презентации. Папка: op03-informacionnye-tehnologii/lessons/11-data-studio/shots/. PNG — по точным именам таблицы. «Экран» — позиция в колоде; «исходник» — постоянный номер. Прямая ссылка: index.html#606, index.html#688a и т. д.

Сначала прочитай files/README.md, formulas.md и dashboard-spec.md. Используй существующие GA4 Property и leads из предыдущих тем. Перед началом зафиксируй период, часовой пояс и исходные числа. Не заменяй реальные показатели числами примеров. Если нет данных/прав — сними фактическое состояние и укажи причину.

Построй три страницы по презентации: GA4, Sheets, затем Blend. У каждого компонента сверяй источник, поле даты и фильтры. Event name=generate_lead относится к отдельной карточке либо третьей таблице Blend, не ко всему трафику. После копирования status-карточек удаляй старый фильтр. Все периоды согласованы.

Blend: таблица GA4 Traffic слева; Sheets Leads справа; позднее третья таблица того же GA4 с Event count и фильтром generate_lead. Два ключа source/campaign, Left Outer. Date и created_at — для отбора периода. Не добавляй request_id/status/device в Dimensions агрегатов. Проверяй NULL, несовпавшие правые записи и отсутствие умножения Sessions. Done Count — условный подсчёт ID, а не status в ключах.

На кадрах не показывай чужие name/email, пароли или токены. Съёмка Share не требует отправлять приглашения; не открывай публичный доступ. Изменения источников и прав делай только в согласованном ресурсе. Для проверки зрителем используй разрешённый тестовый аккаунт. Wireframe и модель JOIN в презентации — схемы, не скриншоты.

Снимай читаемые PNG, желательно от 1600×1000. Если шаг требует два состояния, допустим составной PNG без изменения данных. В shots/evidence.json запиши время, интерфейс, URL/объект без секретов, имя файла и фактический результат. После съёмки выполни node build.mjs, проверь каждый кадр в увеличении и статус manifest.

| Экран | Исходник | PNG | Что снять | Статус |
|---|---|---|---|---|
`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ').replace(/\|/g,'\\|')} | ${s.status} |`).join('\n')+'\n');
const zip=path.join(root,'files/data-studio-lab.zip');fs.rmSync(zip,{force:true});execFileSync('zip',['-q','-X',zip,'README.md','dashboard-spec.md','formulas.md','reconciliation.csv','CHECKLIST.md'],{cwd:path.join(root,'files')});
console.log(JSON.stringify({slides:deck.length,originals:originals.length,extras:deck.length-originals.length,screenshots:shots.length,captured:shots.filter(s=>s.status==='captured').length}));
