# Что делает каждая команда урока целиком. Показывается первой строкой в разборе команды.

SUMMARY = {
'bash ~/Downloads/perms-lab-setup.sh': 'Выполняет скрипт набора: создаёт ~/perm-lab с файлами для опытов и пользователей anna и boris в группе devteam.',
'cd ~/perm-lab': 'Переходит в учебный каталог занятия.',
'ls -l': 'Выводит подробные строки файлов текущего каталога: тип, права, владельца, группу, размер и дату.',
"stat -c '%A %a %U %G %n' report.txt docs /etc/shadow": 'Выводит для трёх объектов права буквами и числом, владельца, группу и имя.',
'ls -ld /tmp ~': 'Выводит строки самих каталогов /tmp и домашнего каталога, не заходя внутрь.',
'chmod u-r report.txt': 'Снимает у владельца право чтения файла report.txt.',
'cat report.txt': 'Пытается вывести содержимое report.txt; без права r получает отказ.',
'chmod u+r report.txt': 'Возвращает владельцу право чтения report.txt.',
'./backup.sh': 'Запускает скрипт backup.sh по пути; для этого нужно право x.',
'bash backup.sh': 'Запускает bash, который читает скрипт как текст и выполняет его; хватает права r.',
'chmod u+x backup.sh': 'Добавляет владельцу право выполнения backup.sh.',
'ls -l report.txt backup.sh': 'Выводит строки двух файлов, чтобы сравнить их права.',
'chmod u-x docs': 'Снимает у владельца право прохода в каталог docs.',
'ls docs': 'Выводит имена файлов каталога docs.',
'cat docs/notes.txt': 'Пытается прочитать файл внутри каталога docs.',
'cd docs': 'Пытается войти в каталог docs.',
'chmod u+x docs': 'Возвращает владельцу право прохода в docs.',
'chmod u-r docs': 'Снимает у владельца право читать список имён docs.',
'chmod u+r docs': 'Возвращает владельцу право читать список имён docs.',
'ls -ld docs': 'Выводит строку самого каталога docs, чтобы убедиться, что права восстановлены.',
'chmod u-w docs': 'Снимает у владельца право менять список каталога docs.',
'touch docs/new.txt': 'Пытается создать файл в каталоге docs.',
'rm docs/notes.txt': 'Пытается удалить файл из каталога docs.',
'chmod u+w docs': 'Возвращает владельцу право менять список каталога docs.',
'chmod a-w report.txt': 'Снимает право записи у всех трёх троек файла report.txt.',
'ls -l report.txt': 'Выводит строку файла report.txt с правами.',
'rm report.txt': 'Удаляет report.txt; у файла без права записи rm сначала спрашивает подтверждение.',
'chmod u+w report.txt': 'Возвращает владельцу право записи report.txt.',
'chmod -v go-r db.env': 'Снимает право чтения у группы и остальных и печатает права до и после.',
'chmod -v u=rwx,g=rx,o= backup.sh': 'Задаёт три тройки сразу: владельцу rwx, группе r-x, остальным ничего; печатает права до и после.',
'chmod -v g+w report.txt': 'Добавляет группе право записи report.txt.',
'chmod -v a+r docs/notes.txt': 'Добавляет всем право чтения; права уже такие, поэтому chmod пишет retained.',
'chmod -v 640 report.txt': 'Устанавливает права rw-r-----: группа читает, остальным ничего.',
'chmod -v 700 private': 'Устанавливает каталогу private права rwx------: только владельцу.',
'chmod -v 755 backup.sh': 'Устанавливает скрипту права rwxr-xr-x: запускать могут все.',
'chmod -v 600 db.env': 'Устанавливает файлу с паролем права rw-------; права уже такие.',
"stat -c '%a %A %n' report.txt private backup.sh db.env": 'Выводит права четырёх объектов числом и буквами рядом.',
'chown anna report.txt': 'Пытается сменить владельца report.txt без sudo; обычному пользователю это запрещено.',
'sudo chown anna report.txt': 'С правами root делает anna владельцем report.txt.',
'sudo chown anna:devteam db.env': 'С правами root делает anna владельцем db.env, а devteam — его группой.',
'ls -l report.txt db.env': 'Выводит строки двух файлов с новыми владельцами.',
'chgrp devteam backup.sh': 'Пытается отдать backup.sh группе devteam, в которой ubuntu не состоит.',
'chgrp adm backup.sh': 'Отдаёт backup.sh группе adm, в которой ubuntu состоит.',
'ls -l backup.sh': 'Выводит строку backup.sh с новой группой.',
'sudo chown -R ubuntu:ubuntu ~/perm-lab': 'Возвращает владельца и группу ubuntu каталогу ~/perm-lab и всему его содержимому.',
'umask': 'Выводит текущую маску прав новых файлов.',
'touch new-file.txt': 'Создаёт пустой файл; его права определит маска.',
'mkdir new-dir': 'Создаёт каталог; его права определит маска.',
'ls -ld new-file.txt new-dir': 'Выводит права нового файла и самого нового каталога.',
'(umask 077; touch secret.txt; mkdir secret-dir; ls -ld secret.txt secret-dir)': 'В подоболочке ставит маску 077, создаёт файл и каталог и показывает их права; маска основной оболочки не меняется.',
'(umask 027; touch team.txt; ls -l team.txt)': 'В подоболочке ставит маску 027, создаёт файл и показывает его права.',
'ls -l /usr/bin/passwd /etc/shadow': 'Выводит строки программы passwd и файла паролей.',
"stat -c '%a %A %n' /usr/bin/passwd /usr/bin/sudo /tmp": 'Выводит права числом и буквами для passwd, sudo и /tmp; четвёртая цифра — специальные биты.',
'find /usr/bin -perm -4000 | head -6': 'Ищет в /usr/bin программы с битом setuid и выводит первые шесть.',
'sudo mkdir /srv/shared': 'С правами root создаёт каталог /srv/shared.',
'sudo chgrp devteam /srv/shared': 'Отдаёт каталог /srv/shared группе devteam.',
'sudo chmod 3770 /srv/shared': 'Ставит каталогу setgid и sticky и права rwx владельцу и группе.',
'ls -ld /srv/shared': 'Выводит строку каталога /srv/shared со специальными битами.',
'sudo -u anna touch /srv/shared/anna.txt': 'От имени anna создаёт файл в общем каталоге.',
'sudo -u boris touch /srv/shared/boris.txt': 'От имени boris создаёт файл в общем каталоге.',
'sudo ls -l /srv/shared': 'С правами root выводит файлы общего каталога с владельцами и группами.',
'sudo -u boris rm /srv/shared/anna.txt': 'От имени boris пытается удалить файл anna.',
'sudo -u anna rm /srv/shared/anna.txt': 'От имени anna удаляет свой файл.',
'sudo ls /srv/shared': 'С правами root выводит имена файлов общего каталога.',
'mkdir /tmp/acl-demo': 'Создаёт каталог для опыта с ACL.',
'chmod 700 /tmp/acl-demo': 'Закрывает каталог для всех, кроме владельца.',
'sudo -u anna ls /tmp/acl-demo': 'От имени anna пытается открыть каталог.',
'setfacl -m u:anna:rx /tmp/acl-demo': 'Добавляет запись ACL: пользователю anna — чтение и проход.',
'ls -ld /tmp/acl-demo': 'Выводит строку каталога; знак + после прав означает ACL.',
'getfacl /tmp/acl-demo': 'Выводит все записи ACL каталога.',
'sudo -u boris ls /tmp/acl-demo': 'От имени boris пытается открыть каталог; записи для boris нет.',
'setfacl -b /tmp/acl-demo': 'Удаляет все записи ACL каталога.',
'sudo groupadd shop-dev': 'Создаёт группу разработчиков shop-dev.',
'for u in alex bella chris; do sudo useradd -m -s /bin/bash $u; done': 'Создаёт три учётные записи с домашними каталогами и оболочкой bash.',
'sudo usermod -aG shop-dev alex': 'Добавляет alex в группу shop-dev, сохраняя остальные группы.',
'sudo usermod -aG shop-dev bella': 'Добавляет bella в группу shop-dev.',
'sudo mkdir -p /srv/shop/{src,releases,uploads}': 'Создаёт каталог проекта и три подкаталога.',
'sudo chgrp shop-dev /srv/shop/{src,releases,uploads}': 'Отдаёт три подкаталога группе shop-dev.',
'sudo chmod 2770 /srv/shop/src': 'Ставит каталогу кода setgid и права rwx владельцу и группе.',
'sudo chmod 2775 /srv/shop/releases': 'Ставит каталогу сборок setgid: группа пишет, остальные читают.',
'sudo chmod 3770 /srv/shop/uploads': 'Ставит каталогу загрузок setgid и sticky: удалять файл может только его владелец.',
'ls -l /srv/shop': 'Выводит строки трёх каталогов проекта.',
'id alex; id bella; id chris': 'Выводит номера и группы трёх участников по очереди.',
"sudo -u alex bash -c 'echo \"print(1)\" > /srv/shop/src/app.py'": 'От имени alex создаёт файл app.py с одной строкой.',
"echo 'print(2)' | sudo -u bella tee -a /srv/shop/src/app.py": 'От имени bella дописывает вторую строку в файл alex.',
"sudo -u alex bash -c 'echo TOKEN=lab > /srv/shop/src/config.env; chmod 600 /srv/shop/src/config.env'": 'От имени alex создаёт файл с секретом и закрывает его правами 600.',
'sudo -u bella cat /srv/shop/src/config.env': 'От имени bella пытается прочитать секрет alex.',
"sudo -u alex bash -c 'echo release-1 > /srv/shop/releases/v1.txt'": 'От имени alex публикует файл сборки v1.txt.',
'sudo chown bella /srv/shop/releases/v1.txt': 'С правами root передаёт v1.txt во владение bella.',
'sudo -u chris cat /srv/shop/releases/v1.txt': 'От имени chris читает опубликованную сборку.',
'sudo -u chris ls /srv/shop/src': 'От имени chris пытается открыть каталог кода.',
'sudo -u bella touch /srv/shop/uploads/photo.jpg': 'От имени bella кладёт файл в общий каталог загрузок.',
'sudo -u alex rm /srv/shop/uploads/photo.jpg': 'От имени alex пытается удалить файл bella.',
'sudo ls -l /srv/shop/src /srv/shop/releases': 'С правами root выводит файлы кода и сборок с владельцами и правами.',
'sudo bash ~/Downloads/perms-lab-check.sh': 'Запускает скрипт проверки с правами root: он проверяет каталоги, файлы и доступ каждого пользователя.',
}
