import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>');
const source=fs.readFileSync(path.join(root,'SOURCE.md'),'utf8');
const slides=[...source.matchAll(/^# Слайд (\d+)\.([^\n]*)\n([\s\S]*?)(?=^# Слайд |$(?![\s\S]))/gm)].map(m=>{const parts={};for(const p of m[3].split(/^## /m).slice(1)){const at=p.indexOf('\n');parts[p.slice(0,at).trim()]=p.slice(at).replace(/\n---\s*$/,'').trim();}return {id:+m[1],title:parts['Заголовок'],text:parts['Текст'],shot:parts['Скриншот'],accent:parts['Акцент']||'',visual:parts['Визуал']};});
if(slides.length!==93||slides.some((s,i)=>s.id!==171+i))throw Error('Expected slides 171–263');
const code=(s,lang='text')=>`<figure class="code"><figcaption>${esc(lang)}<button data-copy aria-label="Скопировать код">Копировать</button></figcaption><pre><code>${esc(s.trim())}</code></pre></figure>`;
const note=s=>`<aside class="note">${inline(s)}</aside>`;
const cards=(items)=>`<div class="cards">${items.map(([t,c])=>`<article><h3>${inline(t)}</h3><p>${inline(c)}</p></article>`).join('')}</div>`;
const flow=(items)=>`<ol class="flow">${items.map((x,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><b>${inline(x)}</b></li>`).join('')}</ol>`;
const branch=()=>`<div class="branch"><div class="origin"><small>ОДНО ДЕЙСТВИЕ</small><strong>FORM SUBMIT</strong><span>Пользователь отправляет форму</span></div><div class="branches"><article><small>АНАЛИТИКА ПОВЕДЕНИЯ</small><h3>GA4</h3><code>generate_lead</code><p>Событие попытки отправки.<br>Без имени и email.</p></article><article><small>ОБРАБОТКА ЗАЯВКИ</small><h3>Apps Script → Sheets</h3><code>request_id · status · UTM</code><p>Запись после проверки.<br>Имя и email — только здесь.</p></article></div></div>`;
const download=(file,label)=>`<a class="download" href="files/${file}" download>${label} ↓</a>`;
const custom={
220:`<p>Продолжаем существующий сайт <strong>ga4-analytics-lab-ivanov.vercel.app</strong> и его GitHub-репозиторий.</p>${cards([['contacts.html','Расширяем уже существующую lead-form.'],['js/script.js','Заменяем только прежний submit-обработчик.']])}${note('Google Tag, CTA и js/metrics.js сохраняем. Новый репозиторий и новый Vercel-проект не создаём.')}`,
227:`<p>В js/metrics.js уже есть переменная params. Код новой формы помещаем в отдельную функцию, чтобы имена не конфликтовали.</p>${code("(() => {\n  const leadForm = document.querySelector('#lead-form');\n  if (!leadForm) return;\n  const params = new URLSearchParams(location.search);\n  // Заполнение UTM и обработчик submit — внутри.\n})();",'js/script.js')}`,

171:`<p class="lead">UTM, сайт на Vercel и Google Tag уже дают события. Теперь найдём место для самой заявки.</p>${branch()}${note('Событие generate_lead само по себе не доказывает, что заявка сохранена.')}`,
172:cards([['GA4 · что сделал посетитель','generate_lead · страница · источник · кампания'],['Таблица · что обработать','request_id · created_at · name · email · status']])+note('Имя и email не передаём в параметры GA4.'),
173:branch(),
174:flow(['Модель заявки','Таблица leads','Правила качества','Apps Script','Форма + UTM','POST + GA4','Проверка записи','Ошибки и дубли'])+note('Восемь этапов объединяют все 13 задач исходника. В конце — две записи: direct и telegram.'),
175:cards([['Идентичность','request_id · created_at'],['Содержание','name · email · direction'],['Источник','utm_source · utm_medium · utm_campaign'],['Состояние','status']])+note('Девять столбцов. У каждого поля есть назначение.'),
177:cards([['Человек','name · email · direction'],['Адрес страницы','utm_source · utm_medium · utm_campaign'],['Код','request_id — браузер; created_at и status — сервер']]),
178:cards([['В форме','Имя, email и направление.'],['В коде браузера','request_id и UTM можно изменить через DevTools: сервер проверяет их.'],['Только на сервере','created_at и status создаёт Apps Script.']]),
183:`<p>Вставьте заголовки в <strong>A1:I1</strong>, закрепите строку 1. Для даты в B выберите формат даты и времени.</p>${code('request_id\tcreated_at\tname\temail\tdirection\tutm_source\tutm_medium\tutm_campaign\tstatus','TSV · копировать в A1')}`,
189:`<p>Выделите <code>I2:I</code> → <strong>Данные → Проверка данных</strong>. Заголовок не включаем.</p>${code('new\nin_progress\ndone\nrejected','DROPDOWN')}${note('Дополнительные параметры → неверные данные → Отклонять ввод.')}`,
193:`<p>Для диапазона <code>A2:I</code> выберите «Ваша формула». Подсвечиваем только начатые строки с пропущенным обязательным полем.</p>${code('=AND(COUNTA($A2:$I2)>0,OR($A2="",$B2="",$C2="",$D2="",$E2="",$I2=""))','GOOGLE SHEETS')}${note('В локали с разделителем ; замените запятые на ;. Включите английские имена функций в настройках таблицы.')}`,
194:`<p>Диапазон <code>A2:A</code> → Условное форматирование → Ваша формула.</p>${code('=AND($A2<>"",COUNTIF($A$2:$A,$A2)>1)','GOOGLE SHEETS')}${note('Номер строки в формуле совпадает с началом диапазона. Пустые ID не считаем дублями.')}`,
196:flow(['Структура ✓','Статусы ✓','Обязательные поля ✓','Дубли ✓'])+note('Таблица подготовлена. Следующий этап — приём настоящего POST.'),
197:flow(['Форма на Vercel','POST','Apps Script','Лист leads'])+note('Доступ к таблице остаётся у скрипта. Браузер знает только URL приёмника.'),
202:`<p>Скопируйте ID таблицы из адреса между <code>/d/</code> и <code>/edit</code>. Web App открывает её явно.</p>${code("const SPREADSHEET_ID = 'ВАШ_ID_ТАБЛИЦЫ';\nconst sheet = SpreadsheetApp\n  .openById(SPREADSHEET_ID)\n  .getSheetByName('leads');",'Code.gs')}${note('getActiveSpreadsheet() не используем: в контексте Web App активной таблицы нет.')}`,
206:`<p>Проверяем ID и записываем строку под одной блокировкой.</p>${code("const lock = LockService.getScriptLock();\nlock.waitLock(10000);\ntry {\n  // Найти ID → отклонить дубль → appendRow\n  SpreadsheetApp.flush();\n} finally {\n  lock.releaseLock();\n}",'ФРАГМЕНТ · полный файл на слайде 212')}${note('Без блокировки два одновременных запроса могут оба пройти проверку до первой записи.')}`,
210:`<p>Порядок значений совпадает с A–I. Пользовательский текст записываем через <code>textCell()</code>.</p>${code("sheet.appendRow([\n  id, createdAt,\n  textCell(clean('name')),\n  textCell(clean('email')), clean('direction'),\n  textCell(source), textCell(medium),\n  textCell(campaign), status\n]);",'Code.gs')}${note('textCell() не даёт строке, начинающейся с =, превратиться в формулу. Функция есть в полном файле.')}`,
212:`<p class="lead">Скачайте готовый <code>Code.gs</code>, вставьте целиком и укажите ID своей таблицы.</p>${download('Code.gs','Скачать Code.gs')}${cards([['Вход','Обязательные поля, email, direction, формат ID.'],['Запись','Блокировка, поиск дубля, timestamp и status=new.'],['Ответ','JSON: ok, request_id или код ошибки.']])}${note('Полный файл дополнен проверкой заголовков и длины полей. Это учебный приёмник, не production API.')}`,
216:`<p>Описание: <code>GA4 Leads Receiver v1</code>.</p>${cards([['Execute as','Me / Я — скрипт пишет в вашу таблицу.'],['Who has access','Anyone / Все — для посетителя без входа в Google.']])}${note('Публикуем только учебный приёмник с тестовыми данными. Если политика Workspace запрещает доступ «Все», не обходите её: используйте разрешённый учебный аккаунт.')}`,
224:flow(['Форма','POST в named iframe','Apps Script'])+code('<iframe name="submission-frame"\n  id="submission-frame"\n  title="Ответ приёмника" hidden></iframe>','contacts.html')+note('Имя iframe совпадает с target формы. Скрытый ответ с другого origin нельзя прочитать из страницы: сохранение проверяем в Sheets.'),
228:`<p>Этот код выполняется внутри <code>if (leadForm)</code>: на Home и About формы нет.</p>${code("const defaults = {\n  utm_source: 'direct',\n  utm_medium: 'none',\n  utm_campaign: 'not_set'\n};\nfor (const [key, fallback] of Object.entries(defaults)) {\n  leadForm.elements.namedItem(key).value =\n    params.get(key)?.trim() || fallback;\n}",'js/script.js')}`,
230:`<p>Создаём полный UUID перед первой отправкой. Для повторной доставки сохраняем тот же ID.</p>${code("if (!requestId.value) {\n  requestId.value = 'REQ-' +\n    crypto.randomUUID().toUpperCase();\n}",'js/script.js')}${note('Не обрезаем UUID до 8 символов. Новая заявка — кнопка «Новая заявка» / reset. Сервер всё равно проверяет формат и дубль.')}`,
232:`<p>Событие остаётся в обработчике <code>submit</code>. Имя и email в параметры не передаём.</p>${code("if (typeof window.gtag === 'function') {\n  window.gtag('event', 'generate_lead', {\n    lead_source: 'contact_form'\n  });\n}",'js/script.js')}${note('В этой версии событие означает попытку отправки. Доказательство сохранения — строка в Sheets, а не событие GA4.')}`,
233:`<p>Замените старый submit-обработчик из темы 6. Остальные события оставьте.</p>${download('script.js','Скачать script.js с сохранённым CTA')}${code("leadForm.addEventListener('submit', () => {\n  if (!requestId.value) {\n    requestId.value = 'REQ-' + crypto.randomUUID().toUpperCase();\n  }\n  if (typeof window.gtag === 'function') {\n    window.gtag('event', 'generate_lead', {\n      lead_source: 'contact_form'\n    });\n  }\n  // Браузер выполняет обычный POST.\n});",'КЛЮЧЕВОЙ ФРАГМЕНТ')}${note('Старый preventDefault() остановит POST, даже если новый обработчик правильный. Не оставляйте два обработчика формы.')}`,
234:`<p>Одна существующая форма; три видимых поля, четыре hidden-поля и iframe после формы.</p>${download('form.html','Скачать HTML формы')}${code('<form id="lead-form"\n  action="ВАШ_APPS_SCRIPT_URL"\n  method="POST" target="submission-frame">\n  <!-- name, email, direction -->\n  <!-- request_id, utm_source, utm_medium, utm_campaign -->\n  <button type="submit">Отправить заявку</button>\n  <button type="reset">Новая заявка</button>\n</form>\n<iframe name="submission-frame" hidden></iframe>','СТРУКТУРА · полный код в файле')}${note('Hidden не означает защищённый. Timestamp и status отсутствуют в форме и создаются сервером.')}`,
239:`<p>Найдите новую строку на листе <code>leads</code>. Сверьте ID из сообщения под формой.</p>${code('REQ-…  |  дата и время  |  Иван Тестов\nstudent@example.com  |  backend\ndirect  |  none  |  not_set  |  new','ОЖИДАЕМЫЕ ЗНАЧЕНИЯ')}${note('Сообщение «POST отправляется» не подтверждает результат. Если строки нет — проверьте Executions в Apps Script, URL /exec и права Web App.')}`,
243:`<p>Откройте Realtime или DebugView и найдите <code>generate_lead</code> после теста формы.</p>${cards([['GA4','Есть событие попытки отправки.'],['Google Sheets','Есть строка с тем же учебным сценарием и нужными UTM.']])}${note('Эти проверки независимы. Блокировщик может остановить GA4, а ошибка приёмника — запись в таблицу.')}`,
248:`<p>Повторный POST с тем же ID не должен добавлять строку. Это отдельная проверка от ручного копирования строки.</p>${code("{\n  \"ok\": false,\n  \"error\": \"duplicate_request_id\"\n}",'ОЖИДАЕМЫЙ JSON')}${note('Отправьте повторно без «Новая заявка», сравните число строк. Для просмотра JSON временно задайте target="_blank". Проверка и запись защищены ScriptLock.')}`,
250:`<p>Откройте dropdown одной тестовой заявки. Пройдите допустимые состояния.</p>${flow(['new','in_progress','done'])}${note('После демонстрации дубля удалите только добавленную тестовую копию строки. Оригинал оставьте.')}`,
254:branch()+flow(['UTM-ссылка','Форма','Проверки на сервере','Запись в leads']),
256:`<p>POST отправляется в скрытый iframe. Страница пока не обрабатывает JSON-ответ.</p>${cards([['Уже есть','В ответе Apps Script — ok и error.'],['Пока нет','Подтверждения успешного сохранения в интерфейсе формы.']])}${note('ContentService в этом примере не выставляет произвольные HTTP 400/409/500. JSON-ошибка и HTTP-статус — разные вещи. Контракт и подтверждение разберём в теме API/Webhook.')}`,
262:branch()+note('Результат: контролируемая таблица заявок v1. Проверены direct, UTM, обязательные поля, дубли и словарь статусов.'),
263:flow(['Google Sheets','CSV','Power Query','Applied Steps','Refresh'])+`<p class="lead">Следующая тема: повторяемая очистка вместо ручного исправления.</p>`
};
function markdown(text){const chunks=text.split(/(```[\s\S]*?```)/g);return chunks.map(part=>{if(part.startsWith('```')){const m=part.match(/^```([^\n]*)\n([\s\S]*?)```$/);return code(m[2],m[1]||'text');}let paras=part.trim().split(/\n\s*\n/).filter(Boolean);return paras.map(p=>{if(/^\d+\. /m.test(p))return `<ol class="list">${p.split(/\n(?=\d+\. )/).map(v=>`<li>${inline(v.replace(/^\d+\. /,''))}</li>`).join('')}</ol>`;return `<p>${inline(p).replace(/\n/g,'<br>')}</p>`;}).join('');}).join('');}
const stage=id=>id<180?'01 / Событие и заявка':id<197?'02 / Контролируемая таблица':id<213?'03 / Приёмник Apps Script':id<220?'04 / Публикация Web App':id<235?'05 / Форма и UTM':id<244?'06 / Сквозная проверка':id<251?'07 / Качество данных':'08 / Итог и Power Query';
const dark=new Set([171,173,196,197,219,251,254,262,263]);
const corrections={179:'Используйте только вымышленные значения. В событие GA4 не отправляйте содержимое полей.',187:'В этой практике UTM читаем с текущей страницы Contacts. Для перехода с Home метки нужно сохранять отдельно — здесь это ещё не реализовано.',209:'direct / none / not_set — наш учебный словарь. Это не гарантия совпадения с атрибуцией сессии GA4.',218:'Нужен /exec, не /dev. После правки кода: Управление развёртываниями → Изменить → Новая версия.',225:'Скрытые поля доступны в DevTools. Сервер не доверяет их значениям без проверки.',229:'Для этой проверки открывайте contacts.html сразу с UTM. Перенос между страницами автоматически не происходит.',231:'В полном примере UUID длиннее показанных в схеме коротких ID. Положение строки и ID не связаны.',247:'Это ручная демонстрация подсветки. Она не проверяет защиту от повторного POST: этот тест — следующий.',249:'Dropdown защищает ручной ввод. Сервер отдельно игнорирует присланный status и назначает new.'};
fs.mkdirSync(path.join(root,'shots'),{recursive:true});
const shots=slides.filter(s=>s.shot).map(s=>({sourceSlide:s.id,lessonSlide:s.id-170,file:`${s.id}-shot.png`,screen:s.shot,accent:s.accent,status:fs.existsSync(path.join(root,'shots',`${s.id}-shot.png`))?'captured':'pending'}));
fs.writeFileSync(path.join(root,'shots/manifest.json'),JSON.stringify(shots,null,2));
const captureNotes={225:'VS Code: фрагмент формы для существующего contacts.html, четыре hidden-поля.',234:'VS Code: полный фрагмент form.html для замены формы. URL /exec ещё нужно подставить.',227:'VS Code: подготовленный script.js, URLSearchParams внутри отдельной функции.',228:'VS Code: заполнение UTM в hidden-полях, проверка наличия формы.',233:'VS Code: подготовленный submit-обработчик; ниже сохранён существующий CTA.'};
const shot=s=>{const file=`${s.id}-shot.png`;const exists=fs.existsSync(path.join(root,'shots',file));return `<figure class="shot">${exists?`<button data-zoom><img src="shots/${file}" alt="${esc(s.shot)}"></button>`:`<div class="shot-placeholder"><small>КАДР ${s.id}</small><span class="camera">▣</span><strong>${inline(s.shot).replace(/\n/g,' ')}</strong><span>${inline(s.accent).replace(/\n/g,' ')}</span><code>shots/${file}</code><small>Скриншот ещё не снят</small></div>`}<figcaption>${esc(file)} · ${inline(captureNotes[s.id]||s.accent||s.shot).replace(/\n/g,' ')}</figcaption></figure>`;};
const simulation=`<div class="sim"><p><b>Локальная модель</b> — в Google ничего не отправляется.</p><div class="sim-actions"><button data-sim="valid">Корректная заявка</button><button data-sim="missing">Пустое имя</button><button data-sim="duplicate">Тот же ID</button><button data-sim="status">status=done из формы</button></div><output id="sim-output" aria-live="polite">Выберите сценарий: увидим решение приёмника.</output></div>`;
const html=slides.map((s,i)=>{let body=custom[s.id]||markdown(s.text);if(corrections[s.id])body+=note(corrections[s.id]);if(s.id===246)body=simulation+flow(['HTML required','Серверная проверка','Запись или отказ']);if([260,261].includes(s.id))body=`<div class="checklist">${s.text.split(/\n\s*\n/).filter(p=>p&&p!=='Сделайте скриншоты:'&&p!=='После занятия студент должен объяснить:').map(p=>p.split(/\n/).map(t=>`<label><input type="checkbox">${inline(t.replace(/^\d+\. /,''))}</label>`).join('')).join('')}</div>`;return `<section class="lesson-slide ${dark.has(s.id)?'dark':''} ${s.shot?'with-shot':''}" id="slide-${s.id}" data-stage="${stage(s.id)}"><div class="inner"><div class="kicker">${stage(s.id)}<span>ИСХОДНИК ${s.id} · ${i+1} / 93</span></div><h${i===0?1:2}>${inline(s.title)}</h${i===0?1:2}><div class="${s.shot?'workbench':'content'}"><div class="copy">${body}</div>${s.shot?shot(s):''}</div></div></section>`;}).join('\n');
const head=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0c2733"><title>ОП.03 · Тема 7 · Контролируемая таблица заявок</title><link rel="stylesheet" href="../../styles.css"><link rel="stylesheet" href="styles.css"></head>`;
const sources=[['Apps Script Web Apps','https://developers.google.com/apps-script/guides/web'],['Доступ к связанным файлам из Web App','https://developers.google.com/apps-script/guides/bound'],['ScriptLock','https://developers.google.com/apps-script/reference/lock/lock-service'],['appendRow и формулы','https://developers.google.com/apps-script/reference/spreadsheet/sheet'],['Content Service','https://developers.google.com/apps-script/guides/content']];
fs.writeFileSync(path.join(root,'index.html'),head+`<body class="leads"><a class="skip" href="#slides">К слайдам</a><div class="presentation"><header><a class="brand" href="../../index.html"><b>И/Т</b><span>ОП.03 · ТЕМА 07<small>Форма → заявка → качество данных</small></span></a><nav><button data-open="contents">Содержание</button><a href="materials.html">Материалы</a><button data-open="sources" aria-label="Источники">S</button><button id="fullscreen" aria-label="Полный экран">⛶</button><span class="counter"><b id="current">01</b> / 93</span></nav></header><main id="slides" tabindex="-1">${html}</main><footer><span id="chapter">${stage(171)}</span><small>← → листать · M содержание · F полный экран</small><button id="prev" aria-label="Предыдущий слайд">←</button><button id="next">Дальше →</button><div class="progress" role="progressbar" aria-label="Прогресс" aria-valuemin="1" aria-valuemax="93"><i id="progress"></i></div></footer></div><dialog id="contents"><div class="dialog-head"><h2>Содержание</h2><button data-close>Закрыть ×</button></div><p>93 экрана · исходные номера 171–263.</p><div class="contents">${slides.map((s,i)=>`<button data-go="${s.id}"><b>${String(i+1).padStart(2,'0')}</b>${inline(s.title)}<small>${s.id}</small></button>`).join('')}</div></dialog><dialog id="sources"><div class="dialog-head"><h2>Источники и материалы</h2><button data-close>Закрыть ×</button></div>${sources.map(([t,u])=>`<p><a href="${u}" target="_blank" rel="noopener noreferrer">${t} ↗</a></p>`).join('')}<p>Официальные источники проверены 23.09.2026. Сценарий сохранён; технические уточнения — в LESSON.md.</p><button id="print">Печать / PDF</button></dialog><dialog id="visual"><div class="dialog-head"><h2>Скриншот</h2><button data-close>Закрыть ×</button></div><img alt=""></dialog><script src="script.js"></script></body></html>`);
const table=shots.map(s=>`<tr><td><a href="index.html#${s.sourceSlide}">${s.lessonSlide} / ${s.sourceSlide}</a></td><td><code>${s.file}</code></td><td>${inline(s.screen).replace(/\n/g,' ')} ${inline(s.accent).replace(/\n/g,' ')}</td><td>${s.status==='captured'?'Снят':'Ожидает съёмки'}</td></tr>`).join('');
fs.writeFileSync(path.join(root,'materials.html'),head+`<body class="leads materials"><main><a href="index.html">← К презентации</a><p class="kicker">ТЕМА 07 / МАТЕРИАЛЫ</p><h1>Из события — в заявку</h1><p>Готовые фрагменты для существующего проекта темы 6. Перед публикацией подставьте ID таблицы и URL Web App.</p><div class="cards">${['Code.gs','script.js','lead-form.js','form.html'].map(f=>`<article><h3>${f}</h3>${download(f,'Скачать')}<details><summary>Посмотреть код</summary>${code(fs.readFileSync(path.join(root,'files',f),'utf8'),f)}</details></article>`).join('')}</div><h2>Скриншоты · ${shots.length}</h2><p>Нумерация: экран темы / исходный слайд. PNG сохраняйте в shots/ под указанным именем, затем выполните node build.mjs. При отсутствии кадра остаётся честно подписанная рамка.</p><div class="table-scroll"><table><thead><tr><th>Слайд</th><th>Файл</th><th>Что снять</th><th>Статус</th></tr></thead><tbody>${table}</tbody></table></div></main><script>document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.closest('figure').querySelector('code').textContent);b.textContent='Скопировано';}catch{b.textContent='Выделите вручную';}});</script></body></html>`);
fs.writeFileSync(path.join(root,'SCREENSHOTS.md'),`# Тема 7: ${shots.length} скриншотов\n\nСнимать настоящие окна пользователя, не макеты. Только учебные данные. Не изменять рабочий ByteCamp. Не выдавать локальные проверки за работу Google Sheets или GA4. Номер файла — исходный слайд.\n\n| В теме | Исходник | Файл | Что снять | Статус |\n|---|---|---|---|---|\n`+shots.map(s=>`| ${s.lessonSlide} | ${s.sourceSlide} | ${s.file} | ${(s.screen+' '+s.accent).replace(/\n/g,' ')} | ${s.status} |`).join('\n')+'\n');
console.log(`Built ${slides.length} slides; ${shots.length} shots, ${shots.filter(s=>s.status==='captured').length} captured.`);
